### PR TITLE
Working copy support

### PR DESCRIPTION
**Pull request by sneridagh**
as described in https://github.com/plone/volto/issues/748

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Comment by sneridagh** [comment]
@tisto hey do not merge it yet! :)

**Comment by tisto** [comment]
@sneridagh that's not my plan. Just working on the German translations...

**Comment by sneridagh** [comment]
So it's ready, for it to work properly it's required to merge and release:

https://github.com/plone/plone.app.iterate/pull/84

For people in a hurry, both PRs need to be pulled in order to work.

**Review by tiberiuichim — APPROVED** [review]

**Comment by tisto** [comment]
@sneridagh plone.app.iterate 4.0.0 has been released. Can we merge and release this now? Is plone.app.iterate a hard dependency for Volto once this is merged? If that's the case we should create a section in the README that documents those kind of requirements.

**Pull request merged**
