### PR TITLE
Fix block chooser search is not focusable when clicked on add button

### LINKED ISSUE #5866: Block chooser search is not focusable when clicked on add button.
Screenshot 2024-03-11 at 8 29 08 PM

### PR DESCRIPTION
**Pull request by iRohitSingh**
Fix #5866 

https://github.com/plone/volto/assets/61353484/a27b4519-5cb0-4f3c-aebb-5b1a89699ddb

### CODE REVIEW

**Comment by iRohitSingh** [comment]
@sneridagh I debugged this issue and in initial implementation there was autofocus but someone removed it. I am not able to pinpoint the person in gitblame. I readded it.

**Comment by stevepiercy** [comment]
@iRohitSingh it was part of this commit by @sneridagh. He did some other things with autofocus. I'm not clear what one has to do with the other.

**Comment by sneridagh** [comment]
@stevepiercy which commit?

autofocus is meh for a11y things... don't know if that had to be with the removal.

/cc @ichim-david

**Comment by ichim-david** [comment]
> @stevepiercy which commit?
> 
> autofocus is meh for a11y things... don't know if that had to be with the removal.
> 
> /cc @ichim-david

@sneridagh I am in favor of adding the autofocus back as the short version.

You've probably read something similar to this mention https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus#accessibility_concerns.
I have seen examples where once you open something you focus to the first  form element that is focusable such as the first input look at react-aria dialog example https://react-spectrum.adobe.com/react-aria/Dialog.html.

For us since it focuses it on the search input if you hit tab you will get to the other block items from the popup which
is not possible right now so not only are you solving the convenience of the sighted users to have the search focused but you can also now use the keyboard to select a block to add.

**Review by ichim-david — APPROVED** [review]

**Comment by stevepiercy** [comment]
@sneridagh I can't find it now. I may have been mistaken.

**Comment by sneridagh** [comment]
ok! merging.

**Comment by sneridagh** [comment]
@iRohitSingh @ichim-david I'm reverting this PR because it caused a regression:https://github.com/plone/volto/issues/6389

Let's find an alternative whenever possible.

**Pull request merged**
