### PR TITLE
Add support for `preview_image_link` behavior in Volto Image component

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Review by davisagli — APPROVED** [review]
@sneridagh LGTM

**Comment by pnicolli** [comment]
What is the `preview_image_link`? Something new or something I simply did not know that existed?

**Comment by davisagli** [comment]
@pnicolli It's an optional behavior we added in plone.volto last year: https://github.com/plone/plone.volto/pull/49

**Comment by pnicolli** [comment]
Ok yes I had no clue it existed :) LGTM then

**Pull request merged**
