### PR TITLE
[docs] fix exit status of grep in make docs-linkcheckbroken

### PR DESCRIPTION
**Pull request by wolbernd**
https://github.com/plone/documentation/issues/1212

### CODE REVIEW

**Review by stevepiercy — CHANGES_REQUESTED** [review]
Would you please change this target to `docs-linkcheckbroken`?

https://github.com/plone/volto/blob/8701361e08f5e4e0b51097f7001cc71a39dc1413/.github/workflows/docs.yml#L43-L43

**Review by stevepiercy — APPROVED** [review]
w00t!

**Comment by wolbernd** [comment]
@stevepiercy Github tasks are updated. Is there a reason why we only use `docs-linkcheckbroken` and not `docs-test` which would also include spellcheck?

**Comment by stevepiercy** [comment]
@wolbernd our spellcheck dictionary is severely lacking, but we keep whittling away at it. There's also a [major deal-breaker issue with pyenchant](https://github.com/pyenchant/pyenchant/issues/286), and the maintainers have not responded.

**Comment by stevepiercy** [comment]
@wolbernd looks like there is a merge conflict with `CHANGELOG.md`. Would you please resolve it?

**Comment by wolbernd** [comment]
@stevepiercy Should be resolved now

**Comment by stevepiercy** [comment]
Thank you!

**Pull request merged**
