### PR TITLE
Add myst and sphinx config

### PR DESCRIPTION
**Pull request by stevepiercy**
# IMPORTANT

Merge https://github.com/plone/volto/pull/3035 before merging this PR!

----------------

I am now able to do `make docs-html` or `make docs-livehtml` to build the docs using Sphinx and MyST. w00t!

This is the first step toward rapid development of the docs.

The intent here is to allow parallel development of Volto documentation. Whenever a change is made on the main branch in docs, it should be backported to `plone6-docs` (not merged) with a separate PR for peer review.

We also need to ask @ericof to set up automatic CI/CD for `plone6-docs` under plone.org. Please suggest a good hostname.

### CODE REVIEW

**Comment by stevepiercy** [comment]
This PR is now ready for review. Any takers?

**Comment by stevepiercy** [comment]
After this PR is merged, we could set up previews in Netlify or automatic deployment. I found the Netlify preview to be f00kin amazeballs for trying out the new search feature with breadcrumbs in the results.

https://deploy-preview-1176--6-dev-docs-plone-org.netlify.app/search.html?q=MyST&doc_section=contributing

**Review by nileshgulia1 — COMMENTED** [review]
@stevepiercy Should we remove files that are common in Volto and Plone docs?
For instance, `cheatsheet.md` is already serving its purpose on Plone docs.

**Comment by stevepiercy** [comment]
> @stevepiercy Should we remove files that are common in Volto and Plone docs? For instance, `cheatsheet.md` is already serving its purpose on Plone docs.

@nileshgulia1 I do not know. That should be discussed amongst the Volto team because y'all might want to keep it for the stand-alone build or move parts of it. Please revert the commit and create a new issue, so that I can merge this issue.

This PR's _only_ purpose is to add Sphinx and MyST build ability, and from another PR fixes that caused warnings and errors.

**Comment by nileshgulia1** [comment]
ok, I reverted my commit, sorry for the confusion. This is something that we can discuss in subsequent PRs. The rest LGTM.

**Comment by stevepiercy** [comment]
@nileshgulia1 thank you! I created a new issue as a placeholder for that discussion.

**Pull request merged**
