### PR TITLE
Add ability to filter the attributes that are saved in the ObjectBrow…

### PR DESCRIPTION
**Pull request by sneridagh**
…serWidget and add proper object_widget

### CODE REVIEW

**Comment by sneridagh** [comment]
@giuliaghisini for some reason we were not adding a proper `object_widget` in the widget registrations?

I added some documentation too, since I've found the way to instantiate the widget and configure from `InlineForm`.

**Review by tiberiuichim — APPROVED** [review]

**Comment by giuliaghisini** [comment]
> for some reason we were not adding a proper `object_widget` in the widget registrations?

no @sneridagh, there's no reason

**Comment by sneridagh** [comment]
@giuliaghisini ok! Asking just in case I missed something. I added it now.

**Comment by giuliaghisini** [comment]
> @giuliaghisini ok! Asking just in case I missed something. I added it now.

perfect!

**Pull request merged**
