### PR TITLE
Add support for Node 20, drop Node 16

### LINKED ISSUE #4714: NodeJS v20 support
**Is your feature request related to a problem? Please describe.**
NodeJS v20 was released to stable today[^1] and is expected to become the latest LTS in October

[^1]: https://nodejs.org/en/blog/announcements/v20-release-announce

### PR DESCRIPTION
**Pull request by davisagli**
Fixes #4714 

Node.js 16 is no longer supported: https://nodejs.org/en/blog/announcements/nodejs16-eol

### CODE REVIEW

**Comment by davisagli** [comment]
@sneridagh It seems it just works 🎉

**Review by stevepiercy — APPROVED** [review]
It makes me happy when someone uses Vale to check spelling of terms. 🤗

**Comment by sneridagh** [comment]
@davisagli wondering if we should wait until it's officialy LTS (2023-10-24) or add it now.

There is also the Cypress.io concern :) I have to update you about it. Let's talk this evening.

**Comment by davisagli** [comment]
@sneridagh note, when we merge this, we need to update which checks are required in the branch protection rules

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
