### PR TITLE
Work on #1932 to lazy-load react-toastify in Volto

### PR DESCRIPTION
**Pull request by silviubogan**

### CODE REVIEW

**Comment by silviubogan** [comment]
@tiberiuichim I see that react-toastify is used in src/components/theme/App/App.jsx. Are you sure we want react-toastify to be lazy-loaded if it has such a big role and place in Volto?

**Comment by tiberiuichim** [comment]
I think it's fine. The toastify is used as a result of user interaction, AFAIK.

@plone/volto-team thoughts on lazy-loading toastify in App.jsx ?

**Comment by silviubogan** [comment]
@tiberiuichim It is used on user interaction but it also exposes `ToastContainer` and `Slide` which are always used inside App.jsx:

https://github.com/plone/volto/blob/6fd62cb2860bc7cf3cb7c36ea86bfd8bd03247d9/src/components/theme/App/App.jsx#L153-L165

Anyway, I made the changes to App.jsx in an above commit and I am wondering if this part of react-toastify can be lazy-loaded:

https://github.com/plone/volto/blob/6fd62cb2860bc7cf3cb7c36ea86bfd8bd03247d9/theme/themes/pastanaga/extras/main.less#L12

If you have any idea, please let me know.

**Comment by silviubogan** [comment]
@plone/volto-team Many unit tests are not being passed because of something related to Sentry. The following is an example:

image

Should I open a new issue?

**Comment by silviubogan** [comment]
@tiberiuichim Sorry for touching this PR. What was the reason for which you closed this? I don't remember. Is there a branch that continues what I began here? Thanks.

**Pull request closed without merging**
