### PR TITLE
Fixed some errors on recurrences

### PR DESCRIPTION
**Pull request by damiDevRT**
I open this Pull request to resolve a problem with the recurrence component of the event.
The problem was that by removing the end date, millions of occurrences were calculated.
to fix I added the ability to prevent the end date from being reset in the datetime component.

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Review by tisto — APPROVED** [review]
LGTM. I would like @giuliaghisini to have another look at this PR though.

**Comment by tiberiuichim** [comment]
@damiDevRT I suggest, for the future, that you push your branches to the plone/volto remote. tisto sometimes has to make adjustments to the PR, which is easier when it's from a branch he has write access to.

**Review by giuliaghisini — APPROVED** [review]

**Comment by giuliaghisini** [comment]
LGTM!

**Comment by damiDevRT** [comment]
> @damiDevRT I suggest, for the future, that you push your branches to the plone/volto remote. tisto sometimes has to make adjustments to the PR, which is easier when it's from a branch he has write access to.

sorry, this PR is the result of several tests, initially I did not have the permits as I was not part of the plone fondation. Next times I'll do as you said, thank you

**Pull request merged**
