### PR TITLE
fix: folder contents overflow

### LINKED ISSUE #1689: Horizontal overflow of folder contents but no scrollbar available
Adding extra columns through "columns to show" causes a horizontal overflow of the table.
There is horizontal scrollbar available in order to reach the right-most columns.

### PR DESCRIPTION
**Pull request by nileshgulia1**
fixes #1689

### CODE REVIEW

**Comment by nileshgulia1** [comment]
@sneridagh This is a fix for overflowing of contents in the content Table and it still needs a fix.
Screenshot 2021-01-29 at 7 32 10 PM

You can merge this now.

**Comment by tiberiuichim** [comment]
@nileshgulia1 I think the last column should be sticky and not be hidden. Can you add a screenshot based on this PR?

**Comment by nileshgulia1** [comment]
@tiberiuichim JFYI, if you add more and more columns from "SELECT COLUMNS TO SHOW" in the options we get content overflow, I've just introduced a scrollbar on overflow-x.

Screenshot 2021-07-29 at 9 53 58 PM

**Comment by tisto** [comment]
@nileshgulia1 a horizontal scrollbar makes sense to me (just my 2c).

**Comment by nileshgulia1** [comment]
supersede by #2600

**Pull request closed without merging**
