### PR TITLE
fixed auto play of the video

### PR DESCRIPTION
**Pull request by Mattiullah134**
closes https://github.com/plone/volto/issues/4659

Set defaultActive and autoplay to true in the video player component to ensure that videos play automatically when loaded. This resolves issue #4659.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@Mattiullah134 
please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).

**Comment by Mattiullah134** [comment]
I'm new contributor and i'm unable to understand why my branch has conflicts

**Comment by stevepiercy** [comment]
@Mattiullah134 in your local git checkout, check out `master`, pull, checkout your branch, merge master to your branch, resolve any conflicts, push. That will update this pull request. Also no one will review your PR until you deal with https://github.com/plone/volto/pull/4688#issuecomment-1506826815.

**Comment by Mattiullah134** [comment]
@stevepiercy i follow the same steps as you mention above but still my branch is not merge

**Comment by stevepiercy** [comment]
@Mattiullah134 your push was successful and this PR is now updated.

We do not merge pull requests, much less even review them, until you follow the instructions, as I have now said three times in https://github.com/plone/volto/pull/4688#issuecomment-1506826815. Please read the content at those links and follow their instructions.

**Comment by stevepiercy** [comment]
@Mattiullah134 as mentioned, now for the fourth time, see [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), wherein you will find [Change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry).

For the other failed checks, unit tests fail. [Searching the documentation for "unit tests" within "frontend"](https://6.docs.plone.org/search.html?q=unit+tests&doc_section=volto) yields some promising leads.

**Comment by sneridagh** [comment]
@Mattiullah134 Thanks for the contribution, but it's not auto by default because we want it that way.

**Pull request closed without merging**
