### PR TITLE
Adding extraction of videoID from youtube videos url which contain '/live/'

### PR DESCRIPTION
**Pull request by IshaanDasgupta**
Solved #5416 
Added an extra conditional statement for extracting 'videoID' from youtube video urls containing '/live/'

### CODE REVIEW

**Review by ericof — CHANGES_REQUESTED** [review]
Could you, please, add a test for it? I believe we should have this in a function that can be properly tested

**Comment by IshaanDasgupta** [comment]
Sure, I am not familiar with adding tests but I'll look into this.

**Comment by IshaanDasgupta** [comment]
@ericof I have added the tests could you please go through them once as this my first time writing jest tests so if there is something wrong do let me know.

Also I have moved the videoDetails extraction code to a separate function and there was also a issue to video's thumbnails not begin displayed so I also changed the logic to bit to get the correct thumbnail URLs.

**Comment by IshaanDasgupta** [comment]
The first screenshot is from https://demo.plone.org/ where the videos in which the url contains "list" or ".be" dont have their thumbnails displayed, the second one is from my local server. There was a problem with the extraction of the videoID from the urls with "list" and ".be".

Screenshot from 2023-11-25 21-14-00
Screenshot from 2023-11-25 21-17-03

**Review by ericof — APPROVED** [review]
Thanks for taking care of this!

**Pull request merged**
