### PR TITLE
Fix CSS bundling in production mode to be consistent with the current policy in the client bundle

### PR DESCRIPTION
**Pull request by sneridagh**
Right now the order of the CSS resources matches this chain: Loading of `import my-less.less` in add-ons (following the add-on order) -> Loading of the Semantic UI defaults -> Loading of the local theme (either project or add-on based). 

https://github.com/plone/volto/blob/master/src/start-client.jsx#L1-L2

Here is the issue: (https://github.com/plone/volto/issues/3419) If you try to override an add-on CSS from your theme, in dev it does work well, but not in production mode.

It seems that `style-loader` which is used in dev mode preserves the order of the import loading (using the add-ons load order), then semantic and all the theme. However, `MiniCssExtractPlugin` seems that it does not because it bundles the semantic CSS (node_modules) separately from the app (`src`) ones.

With the changes in this PR we are forcing now the bundling of all the CSS in one chunk, so it behaves the same than in dev mode (using the style-loader).

This is the resultant build in a project:

```
  1.04 MB (+489 B)      build/public/static/js/client.fa87ca07.chunk.js
  150.42 KB             build/public/static/css/styles.ab046a0d.chunk.css
  132.22 KB             build/public/static/js/prettier-standalone.fe7158db.chunk.js
  77.88 KB (+77.06 KB)  build/public/static/js/react-dates.7bb4a3fa.chunk.js
  56.77 KB              build/public/static/js/draft-js.9f4d4b12.chunk.js
  46.56 KB (+45.96 KB)  build/public/static/js/rc-time-picker.479c4018.chunk.js
  32.07 KB              build/public/static/js/prettier-parser-html.5cb44c23.chunk.js
  21.63 KB (+21.07 KB)  build/public/static/js/moment.df21a1b4.chunk.js
  16.93 KB              build/public/static/js/29.b472dad7.chunk.js
  15.41 KB              build/public/static/js/immutable.6a920a80.chunk.js
  13.52 KB              build/public/static/js/react-image-gallery.ddc3e376.chunk.js
  10.16 KB              build/public/static/js/30.8117a261.chunk.js
  8.58 KB               build/public/static/js/plone-volto-components-manage-Widgets-RecurrenceWidget-RecurrenceWidget.72473a2e.chunk.js
  8.5 KB                build/public/static/js/react-sortable-hoc.63a6d387.chunk.js
  7.64 KB               build/public/static/js/react-color-lib-Github.181d8932.chunk.js
  6.24 KB               build/public/static/js/react-window.f48f70fc.chunk.js
  6.2 KB                build/public/static/js/diff.a65a739e.chunk.js
  6.06 KB               build/public/static/js/react-select-async-paginate.3abdf618.chunk.js
  4.85 KB               build/public/static/js/react-ga.36c62523.chunk.js
  3.38 KB               build/public/static/js/react-simple-code-editor.2d5c06f7.chunk.js
  3.33 KB (+2 B)        build/public/static/js/react-google-recaptcha-v3.ad27f7b8.chunk.js
  3.21 KB               build/public/static/js/prismjs-components-prism-core.126f5018.chunk.js
  2.65 KB (+1 B)        build/public/static/js/hcaptcha-react-hcaptcha.6c3b5ae8.chunk.js
  2.35 KB               build/public/static/js/react-select-async-creatable.2b3b0e44.chunk.js
  2.02 KB (-26 B)       build/public/static/js/plone-volto-components-manage-Widgets-DatetimeWidget.886c795c.chunk.js
  1.76 KB (-394 B)      build/public/static/js/runtime~client.7bbb2395.js
  1.75 KB               build/public/static/js/datapunt-matomo-tracker-js.498ecbfc.chunk.js
  1.21 KB (+3 B)        build/public/static/js/react-select-async.682033ab.chunk.js
  1.17 KB               build/public/static/js/react-select-creatable.174dc6bd.chunk.js
  1.14 KB               build/chunks.json
  1.1 KB (-15.83 KB)    build/public/static/js/31.ca035014.chunk.js
  945 B                 build/public/static/js/plone-volto-components-theme-View-EventView.8b72dea8.chunk.js
  416 B (+1 B)          build/public/static/js/draft-js-lib-isSoftNewlineEvent.ce8616f5.chunk.js
  289 B                 build/public/static/js/styles.ab046a0d.chunk.js
```

As a side effect of this configuration, now almost all chunks have name now instead of a meaningless number. It could be useful in certain tasks in the future.

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Comment by tiberiuichim** [comment]
I think it would also make sense to change the order of these two lines, as well: 

https://github.com/plone/volto/blob/4a760bde9bc2ea8050d7a16f2b518e244d415536/src/start-client.jsx#L1-L2

**Comment by pnicolli** [comment]
Nice catch. I do not understand why some chunks have grown a lot in size, though.

**Comment by sneridagh** [comment]
@tiberiuichim by changing this, then theme will come first then add-ons.

You won't be able to override (theme) the default look and feel of an add-on.

Also, we can't do this now. This will break so many sites that relied during years in this order.

**Comment by sneridagh** [comment]
@ichim-david I've taken a look at the `style-loader` order in dev mode and for me it's the expected output.

**Comment by sneridagh** [comment]
I can see only good things coming from this one, but let's wait for the Volto Team meeting next week.

**Review by giuliaghisini — APPROVED** [review]

**Comment by sneridagh** [comment]
@tiberiuichim @ichim-david I removed the forced CSS chunk. The 

```
          vendors: false,
          default: false,
```

already does the trick.

```
  1.05 MB    build/public/static/js/client.86d2b6b5.chunk.js
  151.21 KB  build/public/static/css/client.86d2b6b5.chunk.css
  132.22 KB  build/public/static/js/prettier-standalone.40a225d1.chunk.js
  101.01 KB  build/public/static/js/react-dates.6dd52138.chunk.js
  72.23 KB   build/public/static/js/draft-js.a7ad6ed4.chunk.js
  46.56 KB   build/public/static/js/rc-time-picker.3721eaa5.chunk.js
  32.07 KB   build/public/static/js/prettier-parser-html.6a0a4f40.chunk.js
  21.63 KB   build/public/static/js/moment.a2c69142.chunk.js
  16.98 KB   build/public/static/js/28.120e48be.chunk.js
  15.41 KB   build/public/static/js/immutable.08a1899f.chunk.js
  13.52 KB   build/public/static/js/react-image-gallery.2ac449bf.chunk.js
  10.14 KB   build/public/static/js/29.0e83ce3c.chunk.js
  8.59 KB    build/public/static/js/plone-volto-components-manage-Widgets-RecurrenceWidget-RecurrenceWidget.c1f87352.chunk.js
  8.5 KB     build/public/static/js/react-sortable-hoc.e4070e6e.chunk.js
  7.64 KB    build/public/static/js/react-color-lib-Github.8477be4b.chunk.js
  6.24 KB    build/public/static/js/react-window.063945dd.chunk.js
  6.2 KB     build/public/static/js/diff.2bfcd47b.chunk.js
  6.06 KB    build/public/static/js/react-select-async-paginate.7500fe7a.chunk.js
  4.85 KB    build/public/static/js/react-ga.e44ee891.chunk.js
  3.38 KB    build/public/static/js/react-simple-code-editor.65c96ba9.chunk.js
  3.33 KB    build/public/static/js/react-google-recaptcha-v3.dd8ee708.chunk.js
  3.21 KB    build/public/static/js/prismjs-components-prism-core.b2bf6843.chunk.js
  2.65 KB    build/public/static/js/hcaptcha-react-hcaptcha.47c15b2c.chunk.js
  2.35 KB    build/public/static/js/react-select-async-creatable.c6646426.chunk.js
  2.07 KB    build/public/static/js/runtime~client.1e930ee9.js
  2.02 KB    build/public/static/js/plone-volto-components-manage-Widgets-DatetimeWidget.b35e4f5e.chunk.js
  1.75 KB    build/public/static/js/datapunt-matomo-tracker-js.c85d10dd.chunk.js
  1.21 KB    build/public/static/js/react-select-async.b086d8e1.chunk.js
  1.17 KB    build/public/static/js/react-select-creatable.bade3da0.chunk.js
  1.1 KB     build/chunks.json
  1.1 KB     build/public/static/js/30.07683e76.chunk.js
  945 B      build/public/static/js/plone-volto-components-theme-View-EventView.f8d6d441.chunk.js
  895 B      build/public/static/css/plone-volto-components-manage-Widgets-RecurrenceWidget-RecurrenceWidget.c1f87352.chunk.css
  892 B      build/public/static/css/plone-volto-components-manage-Widgets-DatetimeWidget.b35e4f5e.chunk.css
  416 B      build/public/static/js/draft-js-lib-isSoftNewlineEvent.1b9a80e8.chunk.js
```

**Review by ichim-david — APPROVED** [review]

**Review by nileshgulia1 — APPROVED** [review]

**Pull request merged**
