### PR TITLE
Hyphenation block chooser labels

### PR DESCRIPTION
**Pull request by ksuess**
Fix https://github.com/plone/volto/issues/2548

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Review by sneridagh — APPROVED** [review]

**Comment by tisto** [comment]
@sneridagh that's definitely a helpful fix, especially for German labels. Thanks, @ksuess!

I am playing devil's advocate here, isn't that a breaking change since we change the HTML structure? I guess it is highly unlikely that someone customized the blocks chooser. Though, I guess we should make a rule that every change in the HTML structure is at least fully documented, what do you think?

**Comment by tiberiuichim** [comment]
I don't think it's a breaking change in this case, as the "external api" of BlockChooser hasn't changed.

**Comment by nzambello** [comment]
I agree with @tiberiuichim

**Comment by tisto** [comment]
@tiberiuichim @nzambello didn't we add a new span element here and therefore change our public API (the HTML structure of the component)? 

https://github.com/plone/volto/pull/2549/files#diff-301c0d5d89f802bfc2c42e8dab539e6a5a7a5706aa8f8f64e01b3341084e7da5R128

**Comment by ksuess** [comment]
Let me see if there is a way to avoid a change of the html.

**Comment by tisto** [comment]
Just for the record: the only reason I am so pedantic here is that I would like us to come up with a set of clear rules about breaking changes that we all can rely on in the future. This discussion is important. This has nothing to do with the PR itself, which is fine.

**Comment by ksuess** [comment]
It's great that you have an I on such subjects, @tisto!

**Comment by tiberiuichim** [comment]
IMHO the HTML structure of components is allowed to change without declaring it a breaking change. Here's my reasons of thinking this:

- if we regard Volto as a self-contained entity and the HTML change has side-effects in other parts (for example, css styling rules), then Volto also has the "fix" for that change, in the form of an updated CSS stylesheet.
- I don't consider breaking component shadowing to be a sufficient form of breaking change. The shadowing mechanism is at least on the level of monkey-patching in terms of "things that are possible, but shouldn't be encouraged". We've worked hard and continue to work on creating an official API so that shadowing is not required. Even more, I think right now the recommended approach should be "if you find that you need shadowing, do it now, be prepared that it would break in the future, but also try to fix your need in Volto, by coming up with a proper extension point".

**Comment by nzambello** [comment]
I guess that we have two different concerns everybody is feeling, surely is what I think myself:
- As a maintainer of the product Volto, I want to consider a breaking change something is literally breaking projects or changing internal APIs without retrocompatibility (semver)
- As Volto integrator, having some components customized or a custom theme, I'd like to have an highlight of what is changing under the hood in the HTML because I'll need to take action for that

I wouldn't consider this case as breaking because we added a span, but I understand that similar cases could affect a project theme or something else, so we should highlight a change in HTML.

So, could we consider this type of cases as minor or patch but show a change in html to integrators and developers through the changelog? Maybe using a label or a custom section.

**Pull request merged**
