### PR TITLE
Add support for sphinxcontrib-youtube and alt tags for videos

### LINKED ISSUE #5301: [docs] add sphinxcontrib.youtube to docs requirements
After we upgrade the docs theme, we can install [sphinxcontrib.youtube](https://github.com/sphinx-contrib/youtube). This will avoid linkcheckbroken issues.

See https://github.com/plone/documentation/issues/1549

### PR DESCRIPTION
**Pull request by stevepiercy**
This PR needs to be merged before the main documentation PR (coming soon).

Closes #5301.

----
📚 Documentation preview 📚: https://volto--6486.org.readthedocs.build/

### CODE REVIEW

**Comment by stevepiercy** [comment]
@sneridagh while I'm in this file, should we update any of the listed trainings?

https://volto--6486.org.readthedocs.build/tutorials/index.html

**Comment by sneridagh** [comment]
@stevepiercy maybe add the volto-light-theme one?

**Comment by stevepiercy** [comment]
@sneridagh will do, but hit me up in Discord. I have questions. I'll merge this PR now, cuz it's holding up another PR. I'll add VLT training in a separate PR.

**Review by davisagli — APPROVED** [review]

**Comment by stevepiercy** [comment]
Issue created to track updating the page content https://github.com/plone/volto/issues/6491

**Pull request merged**
