### PR TITLE
Add french translations

### PR DESCRIPTION
**Pull request by bsuttor**
This is a first step. I suppose some translations have to be improved, but I assume, it can be done later.

### CODE REVIEW

**Comment by tisto** [comment]
@bsuttor thanks! If I am not mistaken we have to enable French in Volto in a few other places as well. @terapyon didn't we create documentation at Ploneconf in Ferrara how to add a new language?

**Comment by terapyon** [comment]
@tisto No, we didn't create a document. @tisto have prepared Japanese env, and I translated to Japanese.

**Comment by bsuttor** [comment]
@tisto If you talk about [volto doc about "Contributing translations for a unsupported language"](https://docs.voltocms.com/customizing/i18n/#contributing-translations-for-a-unsupported-language), I can not add french on transiflex at this moment, I made a request 2 weeks ago to be added into plone5 translators, but I have no response from now

**Comment by bsuttor** [comment]
FYI, I try to start volto from sources with this branch, here my changes (git diff)
```
-  isMultilingual: false,
-  supportedLanguages: ['en'],
+  isMultilingual: true,
+  supportedLanguages: ['en', 'fr'],
```
And my content (on footer for example) is translated in french

**Comment by tisto** [comment]
@bsuttor in which file do you have this diff?

**Comment by bsuttor** [comment]
@tisto src/config/index.js

**Comment by tisto** [comment]
I will merge this now. We can look into the other issue I raised later.

**Pull request merged**
