### PR TITLE
Revive the Styleguide docs

### PR DESCRIPTION
**Pull request by tiberiuichim**
WIP, but working good so far. The old mdx files from component-docs branch need some love

### CODE REVIEW

**Comment by tiberiuichim** [comment]
There's now about (by my guestimation) 20% components documented by styleguidist. I've done about 70% of the existing components/theme .md files (from the old @sneridagh + @nileshgulia1 PR), still need work but it's mostly routine work now.

My impression so far:

- we really really need to export unconnected components. For some of them it is hard to demonstrate various settings because the exported components takes its information directly from the Redux store.
- it's lovely to see components documented with proptypes and available for preview.  See screenshot:
Screenshot 2020-09-20 193331

**Comment by tiberiuichim** [comment]
That's about as far as I'll take this PR right now. Next steps, as far as I see them:

- figure out a way to integrate the styleguidist docs into docs.voltocms.com. It generates a static bundle (I've uploaded a preview here: https://tiberiuichim.github.io/ ) so it should be easy to integrate. 
- About 50% of the existing .md files haven't been revised. The existing, working, doc files show that it's relatively easy to create a new such file.
- I've disabled styleguidists's automatic component example because there are some components (in particular the Block components) which are named very similarly: Edit/View, and it's not easy to distinguish between them. I've tried following the styleguidist docs on how to add naming annotations, but it didn't go, so I've disabled that feature for now.
- Depending on where we want to go with this, we might need to make adjustments to Volto's code base: export unconnected components, etc.

**Comment by victorfda** [comment]
@tiberiuichim nice work!

Only for the record, just in case you didn't notice: this spring I was playing with Storybook: https://github.com/plone/volto/tree/storybook

at that time, it felt like Styleguide dist was a bit abandoned and that the community was switching to the shiny Storybook. 

I researched a bit on the available plugins that could give us all the features that we would like to have there too.
* mdx support
* auto playground setup
* props autodoc
* viewports

as nice to have. Did you identify some other nice to have features?
Hope this information is helpful!

**Comment by sneridagh** [comment]
LOL wrong user! :)

**Comment by tiberiuichim** [comment]
@sneridagh I've tried storybook but I didn't get too far with it. I didn't like the fact that it made it difficult to see what's wrong with it, it just swallowed errors and didn't show any components. I would, of course, prefer to have storybook integrated, it looks nicer and offers better controls.

**Comment by nileshgulia1** [comment]
@tiberiuichim @sneridagh Indeed. Storybook is better and gives more power when we need to keep track of UI component props, state, and context. Whereas using `styleguidist` writing detailed API and usage documentation can attract newcomers to learn about our component APIs.

**Review by nileshgulia1 — COMMENTED** [review]
Thanks @tiberiuichim . LGTM

**Comment by sneridagh** [comment]
@tiberiuichim I tried it locally and it's currently broken:

```
ReferenceError: webpack is not defined
ReferenceError: webpack is not defined
    at defaultModify (/Users/sneridagh/Development/plone/volto/razzle.config.js:57:9)
    at modify (/Users/sneridagh/Development/plone/volto/razzle.config.js:230:27)
    at module.exports (/Users/sneridagh/Development/plone/volto/node_modules/razzle/config/createConfig.js:591:14)
    at webpackConfig (/Users/sneridagh/Development/plone/volto/styleguide.config.js:82:24)
    at mergeWebpackConfig (/Users/sneridagh/Development/plone/volto/node_modules/react-styleguidist/lib/scripts/utils/mergeWebpackConfig.js:40:67)
    at _default (/Users/sneridagh/Development/plone/volto/node_modules/react-styleguidist/lib/scripts/make-webpack-config.js:132:53)
    at createServer (/Users/sneridagh/Development/plone/volto/node_modules/react-styleguidist/lib/scripts/create-server.js:17:56)
    at server (/Users/sneridagh/Development/plone/volto/node_modules/react-styleguidist/lib/scripts/server.js:12:48)
    at commandServer (/Users/sneridagh/Development/plone/volto/node_modules/react-styleguidist/lib/bin/styleguidist.js:132:20)
    at Object.<anonymous> (/Users/sneridagh/Development/plone/volto/node_modules/react-styleguidist/lib/bin/styleguidist.js:75:5)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

any idea?

**Comment by tiberiuichim** [comment]
I think it's an "optimization" that I've done to razzle.config.js.
https://github.com/plone/volto/blob/8e5663f9d6610e56cc7cad43241f3a1be66074c1/razzle.config.js#L47

I've renamed 'webpack' to 'webpackObj' and didn't restart volto after that, to test it. Should be easy to fix, just rename it back, though I don't like initializing the plugins from the passed webpack, should initialize them (I think?) from proper resolved import.

**Comment by tiberiuichim** [comment]
Closing in favour of https://github.com/plone/volto/pull/2065

**Pull request closed without merging**
