### PR TITLE
Solved Edit breaks by broken Short Names

### PR DESCRIPTION
**Pull request by pranayjoshi**
Solved #5407 . Everytime a User enters an ineligible character, the code will restrict from entering the next character. This will continue until the user removes the last character.

### CODE REVIEW

**Comment by pranayjoshi** [comment]
Made necessary Adjustments @stevepiercy

**Comment by pranayjoshi** [comment]
@stevepiercy would you like to add the "review" badge for this as well?

**Comment by stevepiercy** [comment]
@pranayjoshi done, but do you not have access to add labels to a PR you create? Also can you request reviews? This might be a permissions issue with the Contributors Team, and if so, then I need to let the appropriate people know. Thank you!

**Comment by pranayjoshi** [comment]
> @pranayjoshi done, but do you not have access to add labels to a PR you create? Also can you request reviews? This might be a permissions issue with the Contributors Team, and if so, then I need to let the appropriate people know. Thank you!

I don't think I have the persons. I appreciate your efforts.

**Comment by stevepiercy** [comment]
@pranayjoshi yeah, actually the Contributors Team has only the role of "Read", which has [limited permissions](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role). Thanks for verifying.

**Comment by davisagli** [comment]
@pranayjoshi Your fix for the IdWidget here looks good, but the branch is currently a mess that I cannot merge because it also includes your unrelated change from https://github.com/plone/volto/pull/5442. It's important to start each change in a new branch from main, so that they don't get mixed together until we decide to merge something. Could you please create a new branch that only has the changes related to the IdWidget fix?

**Pull request closed without merging**
