### PR TITLE
Set contents property Exclude from navigation for #4855

### PR DESCRIPTION
**Pull request by rexalex**
Volto contents - set properties Exclude from navigation - bad request.
Since in the metadata the of the page exclude_from_nav is boolean, I set it to boolean also in ContentsPropertiesModal.
Solves the #4855.

### CODE REVIEW

**Review by avoinea — APPROVED** [review]
LGTM

**Review by pnicolli — CHANGES_REQUESTED** [review]
Also remove the messages yes and no from line 73 and rerun yarn i18n to update locales.

**Comment by sneridagh** [comment]
@Tishasoumya-02 didn't you run into this issue the other day?

**Comment by sneridagh** [comment]
@rexalex please could you complete what @pnicolli is commenting? Thanks!

**Comment by Tishasoumya-02** [comment]
yes, @sneridagh  , but thinking it was a backend error , I ignored it at that time.

**Comment by sneridagh** [comment]
@rexalex could you please take care of @pnicolli suggestions? Thanks!

**Comment by sneridagh** [comment]
@rexalex if you amend the comments by @pnicolli we are good to go.

**Comment by rexalex** [comment]
> @rexalex if you amend the comments by @pnicolli we are good to go.

**Comment by rexalex** [comment]
@sneridagh @pnicolli added changes. Sorry for the delay

**Review by sneridagh — APPROVED** [review]

**Review by davisagli — APPROVED** [review]

**Pull request merged**
