### PR TITLE
Changed identifier field for password reset to 'username'

### PR DESCRIPTION
**Pull request by giuliaghisini**
Added config.settings.useEmailAsLogin (default:false) to know which field display on password reset

### CODE REVIEW

**Comment by giuliaghisini** [comment]
if it's possibile we'd love to have this pr in volto 15 (and not 16)

**Comment by davisagli** [comment]
I think it depends on the `plone.use_email_as_login` registry setting.

**Comment by sneridagh** [comment]
@davisagli right, thanks! 
@giuliaghisini I would follow the same policy here as we did with the other settings from the registry. I would create a setting in the config and tie that to it.

**Comment by giuliaghisini** [comment]
> @davisagli right, thanks! @giuliaghisini I would follow the same policy here as we did with the other settings from the registry. I would create a setting in the config and tie that to it.

ok!

**Comment by giuliaghisini** [comment]
@sneridagh @davisagli 
added 'useEmailAsLogin' config option in volto for now. 
We will implement the control panel for plone.use_email_as_login registry setting and use it later.

**Comment by giuliaghisini** [comment]
@sneridagh @davisagli 
added 'useEmailAsLogin' config option in volto for now. 
We will implement the control panel for plone.use_email_as_login registry setting and use it later.

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
