### PR TITLE
fix secondary button behaving as type submit

### PR DESCRIPTION
**Pull request by nileshgulia1**
related to #2181 
In `Form.jsx` we do validation checks and show toast in case there're errors. At the same time we let semantic-ui Form handle  these errors and render them inside the Form itself. Can we just rely on one of the two? or move the validation errors on bottom and remove the toast completely. what do you think @sneridagh @giuliaghisini ?

### CODE REVIEW

**Comment by giuliaghisini** [comment]
i think toast is super usefull if you have many tabs in your form on submit, and fields with errors are  not in current tab.. i'm not fully agree to remove the toast notification

**Comment by sneridagh** [comment]
totally agree with @giuliaghisini ... the toasts display other kind of errors too... I do not think it's redundant.

**Comment by nileshgulia1** [comment]
Thanks @giuliaghisini for the comments. I identified the real issue and modified PR accordingly.

**Review by giuliaghisini — APPROVED** [review]

**Review by avoinea — APPROVED** [review]

**Comment by nileshgulia1** [comment]
Cannot reproduce anymore.

**Pull request closed without merging**
