### PR TITLE
Use type info instead of id type as icon title in the folder contents

### PR DESCRIPTION
**Pull request by mamico**
Use type info instead of id type as icon title in the folder contents. 
Type info is for humans and eventually translated.

before:
image

after:
image

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Review by pnicolli — APPROVED** [review]

**Comment by tiberiuichim** [comment]
I think the "Pagina" title would be dependent on the current locale?

**Comment by erral** [comment]
@tiberiuichim yes that response depends on the backend language, plone.restapi handles the translation of the portal_type and other items in the frontend

**Review by sneridagh — APPROVED** [review]
Does this works in p.restapi already, or it's due to merge?

**Comment by sneridagh** [comment]
Oh yeah, it's brain serialization, merging!

**Pull request merged**
