### PR TITLE
Open link in new tab

### PR DESCRIPTION
**Pull request by singhcoder694**
Changed all the links in Repo from only target='_blank' to target={settings.openExternalLinkInnewTab ? '_blank' : '_self'} as per issue #5693

### CODE REVIEW

**Comment by stevepiercy** [comment]
@singhcoder694 all required statuses must pass. See [Change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry) and [Code quality](https://6.docs.plone.org/volto/contributing/index.html#code-quality). We don't review failing pull requests.

**Comment by ichim-david** [comment]
@singhcoder694 you don't modify the *.test.jsx.snap files, that happens by doing the following:
1. run the jest tests locally by running in the root of the volto repo:
   pnpm --filter @plone/volto test
2. once you get failures you will get the option to hit u to update the tests
3. look at every test or code analysis failure and run the required commands to test and fix
https://github.com/plone/volto/blob/main/packages/volto/package.json#L55
Maybe you need eslint in which case you run:
pnpm --filter @plone/volto lint-fix
or prettier or stylelint depending on the changes that you've made.

**Review by davisagli — CHANGES_REQUESTED** [review]
Instead of making this change in many places, it would be better to update those places to use the UniversalLink component, which already pays attention to this setting. UniversalLink is supposed to be the consistent way to make links in volto; if we don't use it, then we have inconsistencies like this.

**Comment by davisagli** [comment]
Thanks for your efforts, but we'd like a solution which centralizes the check for this setting in the UniversalLink component, rather than checking it in many places in the code. Also the PR is now outdated and incomplete, so I will close it.

**Pull request closed without merging**
