### PR TITLE
fix- #5537

### PR DESCRIPTION
**Pull request by ujjwaleee26**
Fixed typo `pnp` to `pnpm` in developing-core.md file

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]

**Comment by ujjwaleee26** [comment]
I just installed the lastest volto release 16.3.0 announced and comiited the changes , now PR is in `@plone/components Expected — Waiting for status to be reported` for many errors, is there anything wrong?

**Comment by davisagli** [comment]
@ujjwaleee26 I'm not sure but those checks are not relevant to this change, so I'll bypass them and merge.

**Comment by davisagli** [comment]
@ujjwaleee26 In the future please give PRs a title that means something when I look at it, like "Fix documentation typo"

then put "Fixes #5537" in the description of the PR. This way github will automatically close the issue after the PR is merged.

**Comment by ujjwaleee26** [comment]
> @ujjwaleee26 In the future please give PRs a title that means something when I look at it, like "Fix documentation typo"
> 
> then put "Fixes #5537" in the description of the PR. This way github will automatically close the issue after the PR is merged.

Okay @davisagli . I will be carefull

**Pull request merged**
