### PR TITLE
Browse button coming out of segment (issue#606) fixed

### PR DESCRIPTION
**Pull request by lkttyagi**

### CODE REVIEW

**Comment by lkttyagi** [comment]
@nileshgulia1  i tried to merge from master but the same error

**Comment by lkttyagi** [comment]
@tisto @sneridagh can anyone help me with this .why my travis -ci terminating .it is asking for some surge login credentials and after that build terminated ?

**Comment by tisto** [comment]
@lkttyagi seems this is unrelated to your PR. We upload robot test results to surge.sh to being able to see the output. Will look into it.

**Comment by nileshgulia1** [comment]
I cannot able to reproduce this anymore.

**Pull request closed without merging**
