### PR TITLE
Fix updating snapshots on pnpm test

### PR DESCRIPTION
**Pull request by Hrittik20**
Fixes: #5783

### CODE REVIEW

**Comment by ichim-david** [comment]
@Hrittik20 adding the -u flag means you update the snapshots regardless if you want todo that or not. You want to run the test, see that it fails because most of the time you made a mistake and hence tests fail.
There are instances where yes you make changes that require testing snapshot update but then you can mention that you want to update the test.

You didn't understand the issue @ksuess added and what she proposed.

If you look there are :ci commands
https://github.com/plone/volto/blob/main/package.json#L18
and non :ci commands. 
She proposes to modify the test command use from packages/volto
https://github.com/plone/volto/blob/main/packages/volto/package.json#L43
and add a new test:ci command and modify the scripts where test is used to be test:ci

This way if someone runs the tests from the root of the monorepo they can update the
tests since the test run allows to select the action todo
run-mode

**Review by ichim-david — CHANGES_REQUESTED** [review]
See previous comment

**Comment by Hrittik20** [comment]
@ichim-david Apologies for the misunderstanding. So will the issue be solved if I modified the [ package](https://github.com/plone/volto/blob/main/package.json) like this :
`"test": "pnpm --filter @plone/volto run test",
  "test:ci": "pnpm --filter @plone/volto run test:ci", `

**Comment by sneridagh** [comment]
@Hrittik20 you can use:

```
pnpm test -- -u
```

It does the trick, by passing args to pnpm scripts (as it did always, it's not a pnpm trick).
If you do not mind, I'd close this one.

**Pull request closed without merging**
