### PR TITLE
Fix logging in test-acceptance-server commands

### PR DESCRIPTION
**Pull request by davisagli**
Start the acceptance image with a pseudo-tty, this fixing a buffering issue where the console output was not shown until exiting.

### CODE REVIEW

**Comment by davisagli** [comment]
@sneridagh Why is the changelog check complaining? This is a change to the root level of the repository, not a package.

**Review by ichim-david — APPROVED** [review]
@davisagli
Thanks for your work! I felt bad if this was the only thing needed but seeing the extra
pull requests added for plone.app.robotframework made me happy you've tackled this issue!

**Comment by sneridagh** [comment]
@davisagli @ichim-david It was like this because of something... I had to remove the tty. I barely recall it, but I think it was something in CI? well, we will find out...

**Comment by davisagli** [comment]
@sneridagh Well, I wondered about that, but the acceptance tests passed, so... ¯\_(ツ)_/¯

**Pull request merged**
