### PR TITLE
Fixing style in blockquote

### LINKED ISSUE #1601: Blockquote: error when text has some style
**Short:** If a text inside a blockquote has some styles (bold, italic for example), the view breaks.
**Steps to reproduce:**
- Go to edit mode of a page in Volto
- Add some text in a text block
- Add some more text to that block in a new line using shift+enter keys
- Add some style to some words (for example bold)
- Mark all the text you have just written and select the blockquote option for it
- Save the page

Result: The page breaks.
Expected: we see linebreaks and styles in blockquote

This bug is related to the changes made in #1249

### PR DESCRIPTION
**Pull request by iFlameing**
Fixes #1601 

@cekk can you review this?

### CODE REVIEW

**Comment by cekk** [comment]
better, but there are still some problems. Probably i'm finding some edge-cases but my clients can do worse things:
- add a new block
- insert some text (aaa)
- shift + enter (new line)
- add some other text (bbb)
- select all the text and select blockquote
- select the first row and make it BOLD
- shift + enter (create a new line between the two already created)
- type some letters (ccc)
- save

expected:

**aaa
ccc**
bbb

got:

**aaa ccc**
bbb

btw there is the same problem with callouts too (here it seems that you haven't already managed split lines)

**Comment by tisto** [comment]
@cekk @iFlameing it would be cool if we would have Cypress tests for the scenarios that Andrea describes.

**Comment by iFlameing** [comment]
@cekk @tisto I investigated the test case which you mentioned above. But it is not related to code but it is related to the draftjs how It handles another tag like(strong). Draftjs handle us an array of content that is present in a blockquote, but when we introduce a strong tag then it gives us a react object of that element and we just render it.
The problem with the above test case is draftjs wrapping both sentences into a single strong tag without br tag.

I am attaching a screenshot in which you can clearly see that there is an enter tag between aaa and ccc but it is not rendered properly. @tisto we need to discuss how we can handle it.

Screenshot from 2020-06-21 20-27-18

**Comment by iFlameing** [comment]
@tisto I think that we can now solve it. I will look into this tomorrow.

**Comment by sneridagh** [comment]
@iFlameing see my last commit has a generic test for ToHTML structures. We now need to fill it with every imaginable use case.

**Review by tiberiuichim — APPROVED** [review]
I've tested the code, looks good

**Comment by sneridagh** [comment]
@iFlameing adding a link is also broken, and the callout is totally broken when used with inline styles too.

**Comment by tiberiuichim** [comment]
Heh, spoke too soon.

**Comment by iFlameing** [comment]
@sneridagh @tiberiuichim can you review this once again.
I know that I am not following DRY but will look into it.

**Comment by tiberiuichim** [comment]
@iFlameing there's 4 instances of that breakline adding code in that module... It really should be a separate function.

**Comment by iFlameing** [comment]
@tiberiuichim Will look into this tomorrow. Can you please try to break this code because we really need a good test case for proof.

**Comment by sneridagh** [comment]
Closing, since it's draftJS issue and it seems quite outdated.

**Pull request closed without merging**
