### PR TITLE
fix: objectbrowsernav key + aria label fields

### PR DESCRIPTION
**Pull request by nzambello**
Fixes the `key` so if elements in different folders have the same name, we won't have rendering issues (I had), @id is unique.
Fixes some aria-labels because the id is not much human-readable, while the title does so it's more pleasant to hear.

### CODE REVIEW

**Review by pnicolli — APPROVED** [review]
LGTM

**Review by tisto — APPROVED** [review]
LGTM

**Comment by sneridagh** [comment]
A number of Cypress tests already relies on them, should be fixed.

Could break a lot of project specific tests...

**Review by giuliaghisini — APPROVED** [review]

**Comment by nzambello** [comment]
> A number of Cypress tests already relies on them, should be fixed.
> 
> Could break a lot of project specific tests...

Fixed that 👍

**Pull request merged**
