### PR TITLE
Allowing user to click on the breadcrumbs of objectBrowser

### PR DESCRIPTION
**Pull request by iFlameing**

### CODE REVIEW

**Review by nileshgulia1 — APPROVED** [review]

**Review by tisto — COMMENTED** [review]
@iFlameing functionality-wise this LGTM. I would do some small style adjustments:

Edit-Page (1)

We can handle the path shortener feature request in a different PR/discussion.

**Comment by iFlameing** [comment]
@tisto I fixed the first two issue :)

**Review by tisto — APPROVED** [review]
LGTM

**Comment by tisto** [comment]
Edit-Page (2)

**Comment by iFlameing** [comment]
@sneridagh  @tisto can you please merge this :)

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
