### PR TITLE
Dx fields validation

### PR DESCRIPTION
**Pull request by avoinea**
See #1246 
* Fix Date only widget
* Add Email, URL widgets
* Improve Form front-end field validation.
* Improve Form validation on back-end validation errors.

### CODE REVIEW

**Comment by tiberiuichim** [comment]
Maybe it would be a good idea to create a "text widget factory". TextWidget already supports custom types of text inputs using the typeTranslations and the type parameter, so instead of having extra components, the TextWidget component could be reused.

Also, regarding errorList. I wonder why other Volto widget don't have it. I haven't checked, but I thought semantic-ui takes care of error display on widgets?

**Comment by sneridagh** [comment]
@avoinea We broke something in Guillotina with this one :( Can you imagine what it is by looking at the cypress tests?





> Also, regarding `errorsList`. I wonder why other Volto widget don't have it. I haven't checked, but I thought semantic-ui takes care of error display on widgets?

@tiberiuichim yes, Semantic UI forms has the "errors" props, they used to work, but only on backend validation.

**Comment by tisto** [comment]
@avoinea the Guillotina build is green as far as I can see. Please rebase and let's get that one merged...

**Comment by avoinea** [comment]
@tisto Looks good, now!

**Comment by avoinea** [comment]
@tisto @sneridagh Can we merge this PR?

**Review by tiberiuichim — APPROVED** [review]

**Comment by avoinea** [comment]
Needs some cosmetics.

**Comment by nileshgulia1** [comment]
@avoinea Are you still woking on this PR?

**Comment by avoinea** [comment]
@nileshgulia1 Nope, it's ready for review and merge.

**Comment by tisto** [comment]
@giuliaghisini @cekk @nzambello @pnicolli a review from you folks on this PR would be great!

**Review by tisto — APPROVED** [review]
LGTM

**Comment by tisto** [comment]
@giuliaghisini @cekk @nzambello @pnicolli last chance for a review. I plan to merge this before our Volto team meeting call today. :)

**Pull request merged**
