### PR TITLE
build(deps): Constrain, pin, upgrade API versions

### PR DESCRIPTION
**Pull request by rpatterson**
Avoid misleading CI errors/failures, real user issues, etc. when new versions of
dependencies/requirements are released or upstream dependencies or constraints change.

Use [existing support in `zc.buildout` for managing
versions](http://www.buildout.org/en/latest/getting-started.html?highlight=update-versions-file#pinned-versions-1)
to capture version constraints required by this buildout that override the base Plone
version pins and automatically update the version pins in a separate file for
reproduciblity.  With these changes, as developers change requirements and/or
constraints, the pins in `./versions.cfg` should be updated when `$ ./bin/buildout` is
run and thus signal version changes to developers in VCS status.  These changes also add
a `$ make upgrade-versions` target to capture how to update all requirements to the
latest versions.

Note that since this changes version management and pins versions that weren't
previously pinned (a good thing) there's some risk this will result in CI
errors/failures that aren't necessarily related to these changes.  IOW, these changes
may reveal some hidden existing issues.  When these changes are merged, similar
unrelated CI errors/failures may be revealed in other branches.  IOW, there's some risk
this could be disruptive to the development community.  I can't think of any specific
way that would happen, CI should already be using the most recent versions, but it's
important to consider.

### CODE REVIEW

**Comment by rpatterson** [comment]
Note that I based this on top of the branch for #2901 since it comes out of the discussion there.  I can rebase onto `origin/master` and force push if that's more desirable.

**Comment by tisto** [comment]
@rpatterson I like the approach. Though, I'd like to play around with it before we make a final decision. If we go with this, we should make it a best practice in general.

**Comment by tiberiuichim** [comment]
There's some issues with comments on version lines, see https://github.com/plone/volto/pull/2928#issuecomment-996654273

**Comment by sneridagh** [comment]
Sorry for not having time to look at it properly until now. Also, sorry again for leaving the buildout in a bad shape last week. My bad! I just fixed it, please sync with master.

I tried your changes and I ran `make build-backend` in the root and it did nothing... I ran also `make clean` then again `make build-backend` and it breaks.

As @tisto said, I found the approach interesting, to be honest I didn't know about this buildout feature, however, I'm lost in Makefile magic tricks. If you are not around and something fails, I don't know who is going to maintain it if something needs to be changed or improved.

As I said also yesterday [in the other PR](https://github.com/plone/volto/pull/2901#discussion_r768356803), this buildout is of "convenience" so you don't have to put your own Plone build if you need to develop Volto. Also the whole Plone development/deployment is improving quickly lately. The idea is the community abandon buildout, and we are not going to recommend it anymore to newcomers. New docker images are being also developed based in pip installs.

Also, as Plone 6 develops, we will need a more sophisticated way to deal with CI and adapt it to Plone current practices, add all the Plone 6 stack properly (as buildout coredev does), and test the thing along with the latests checkouts of the packages stack. Mr.Roboto might have to be improved as well... It's something we discussed in the Steering Circle last week.

So all this will have to be rethought and refactored at some point soon.

Let's wait for @tisto and @tiberiuichim to weigh in too.

**Comment by rpatterson** [comment]
> There's some issues with comments on version lines

Hmm, it's not an issue for me locally, @tiberiuichim.  Are you reporting that it's not working for you?  If yes, can you include details?  My local checkout is using `./eggs/zc.buildout-2.13.4-py3.9.egg`, what is yours using?  If someone is having issues, my best guess would be an older `zc.buildout` version.  If that's the case, then we can just add the appropriate version constraint so that a sufficiently new version is used.

Regardless, there were comments on version lines prior to my changes and my changes just preserve them.  So any issues with those comments are unrelated to this PR, no?  May I consider this as resolved since it's unrelated to this PR's changes?

**Comment by rpatterson** [comment]
> please sync with master.

Doing so now.

> I tried your changes and I ran `make build-backend` in the root and it did nothing... I ran also `make clean` then again `make build-backend` and it breaks.

Would you mind including your console output when reporting issues in your feedback, @sneridagh?  It helps a great deal in addressing things.  For example, it helps clarify what statements like "it did nothing" and "it breaks" mean.  As another example, `$ make ...` will echo the commands it runs which helps narrow down what may be wrong with targets and prerequisites.  Thanks in advance!

> I'm lost in Makefile magic tricks

I'm happy to elaborate and clarify and I can do so in comments so that others can benefit as well.  Please list the specific things that are unclear and I'll address them.

> If you are not around and something fails, I don't know who is going to maintain it if something needs to be changed or improved.

There's no reason you have to use `$ make ...` to use this buildout feature.  Feel free to treat the `./Makefile` as a place to capture *how* to do tasks and not necessarily as *the* way to do them.  I tried to comment it so it can be used as such and I'll improve on that once I get the aforementioned details.  I'm also not a big fan of "what if no one knows X" as a reason not to use a tool correctly, especially when it saves time in the inner loop of development.

> Also the whole Plone development/deployment is improving quickly lately. The idea is the community abandon buildout, and we are not going to recommend it anymore to newcomers.
> ...
> So all this will have to be rethought and refactored at some point soon.

Excellent!  What did I miss in the developer-oriented docs in this checkout that directed me away from using buildout?  In the meantime, since this is going away soon'ish anyways, then there's no reason not to merge these minor improvements so we can close out this PR and stop discussing a dying technology.  Rejecting minor improvements now because of forthcoming, aspirational major refactoring in the future feels like a close cousin to allowing the perfect to be the enemy of the good.

**Comment by tiberiuichim** [comment]
@rpatterson I've added my comment as a way of saying you should be aware of those problems, and fix them here too. 

I'm a fan of Makefiles. They're self-documenting and I find them easier to read and better then stashing all our scripts in package.json. I don't have an opionion on the buildout versioning thing, but in terms of Makefile, the changes are basic and they're good fixes.

**Comment by rpatterson** [comment]
> @rpatterson I've added my comment as a way of saying you should be aware of those problems, and fix them here too.

Ah, thanks for clarifying!  And yeah, I ran into the merge conflicts just now.  I'm working on them.

I still suspect a `zc.buildout` version constraint would be The Right Way (tm) to address any issues with inline comments.  OTOH, I am not a big fan of inline comments in general, so not a hill I'll be dying on.  ;-)

**Comment by sneridagh** [comment]
> Would you mind including your console output when reporting issues in your feedback, @sneridagh? It helps a great deal in addressing things. For example, it helps clarify what statements like "it did nothing" and "it breaks" mean. As another example, `$ make ...` will echo the commands it runs which helps narrow down what may be wrong with targets and prerequisites. Thanks in advance!

Sorry, but it "literally" did nothing:

https://user-images.githubusercontent.com/486927/146835743-49bb60a5-60dd-4d21-9d5c-42ab8da0c1b7.mov

And it broke:

```
❯ make build-backend
bash: line 1: ./bin/buildout: No such file or directory
make[1]: *** [.installed.cfg] Error 127
make: *** [build-backend] Error 2
```

https://user-images.githubusercontent.com/486927/146835853-9ecfecee-a053-472a-9f28-c40c19940dca.mov

It does not break for you?

**Comment by rpatterson** [comment]
> Sorry, but it "literally" did nothing:

Cool, thanks for clarifying!  I often find that people may mean "my assessment is that your code didn't do anything" *or* "It exited with status == 0 and produced no output on stdout or stderr" when they say "nothing".  So being specific really helps me at least.  And copying and pasting console output is an efficient way to be specific.  Thanks for the videos, though!

> ```
> ❯ make build-backend
> bash: line 1: ./bin/buildout: No such file or directory
> make[1]: *** [.installed.cfg] Error 127
> make: *** [build-backend] Error 2
> ```

Thanks, this one helps in particular.  Clearly there's a problem with the target prerequisites in `./Makefile` if this is happening.  Digging in.

> It does not break for you?

Not so far, but I'm doing a clean checkout test now to see if I can reproduce this,

**Comment by sneridagh** [comment]
Cool! Sorry to be that short in my assessments, but (like today) the other day was far too late, had a long day, and still looking at community things and answering to issues/PRs and mails, my bad. Or either I answer in the cell phone (also bad) when I should take care of other things 😩 

Anyways, FYI, I released Volto 14 this evening, so we are free to start merging things again. I would still like to @tisto to take a look at the final outcome of this PR though, he's been busy lately, but hoping he could do it at the right time.

We are short in hands in the community, as you might know, so please understand my concerns about introducing complexity in Makefiles, beyond the basics. However if you say it's not that complex, it's enough for me.

**Comment by rpatterson** [comment]
> > ❯ make build-backend
> > bash: line 1: ./bin/buildout: No such file or directory
> > make[1]: *** [.installed.cfg] Error 127
> > make: *** [build-backend] Error 2
> > ```

Actually, this output doesn't make sense to me in that the commands being run aren't being echoed.  At the very least you should see `+ make -C ./api/ build`.  This should happen because of the following variables at the top of `./Makefile`:

    SHELL:=bash
    .ONESHELL:
    .SHELLFLAGS:=-xeu -o pipefail -O inherit_errexit -c
    .SILENT:

Are you aware of anything in your environment that might affect this, @sneridagh?  Can you paste the output of `$ $ bash --version`?

**Comment by rpatterson** [comment]
> > > ```
> > > ❯ make build-backend
> > > bash: line 1: ./bin/buildout: No such file or directory
> > > make[1]: *** [.installed.cfg] Error 127
> > > make: *** [build-backend] Error 2
> > > ```
> 
> Actually, this output doesn't make sense to me in that the commands being run aren't being echoed. At the very least you should see `+ make -C ./api/ build`. This should happen because of the following variables at the top of `./Makefile`:

I was able to reproduce this issue locally after adding [a `./Makefile` target to perform a clean build test in a fresh git worktree](https://github.com/plone/volto/commit/3574ef64e88314fdafa3bf8bce5d1aedc02cc820).  I pushed that change to [my other more appropriate PR](#2901) and [merged it here](https://github.com/plone/volto/commit/067a780e5b979ece83aa1dc7918933ab81ea3aa4).  The bug was mine and was a simple `./Makefile` syntax error.  I've pushed [the fix](https://github.com/plone/volto/commit/9d9b59a328ad1140bd76b315116437df5561af13).

I'm still concerned about the missing output in your shell, @sneridagh so I hope I can still get answers to those questions.

**Review by sneridagh — COMMENTED** [review]
Hey @rpatterson sorry for taking so much time into reviewing this... 

LGTM, but I tried these commands:

```
❯ make test-clean
bash: -c: line 1: unexpected EOF while looking for matching `)'
bash: -c: line 2: syntax error: unexpected end of file
make: *** [test-clean] Error 2

❯ make clean
bash: -c: line 2: syntax error: unexpected end of file
make[1]: *** [clean-tmp-worktrees] Error 2
make: *** [clean] Error 2
```

and failed as shown. I removed all the api folder and started clean. Could you please take a look? 

Question: When you build the backend, it updates the versions.cfg. The changes are meant to be pushed and update the repo afterwards?

The rest LGTM.
Thanks!

**Comment by sneridagh** [comment]
@rpatterson ping!

**Comment by sneridagh** [comment]
Hey @rpatterson ! how about this one? And how it relates to the last PR for the redundant build? Should I merge that one, then this one? Thanks!!

**Comment by rpatterson** [comment]
> Hey @rpatterson sorry for taking so much time into reviewing this...

Apologies for losing track of this one, @sneridagh!

> and failed as shown. I removed all the api folder and started clean. Could you please take a look?

Are you using GNU make?  Can you paste the output of:

```
$ make --version
```

> Question: When you build the backend, it updates the versions.cfg. The changes are meant to be pushed and update the repo afterwards?

As I understand how this buildout feature works, that should only happen when you explicitly run `$ make -C ./api/ upgrade-versions` or when something isn't pinned.  IOW, if you add a new dependency to `./api/src/plone.restapi/setup.py` or make a change in `./api/version-constraints.cfg`.  That's how I like it to work, as a developer it signals to me when I've changed the depdencies and lets me know I need to add a new pin.

**Comment by rpatterson** [comment]
> Are you using GNU make? Can you paste the output of:

I just merged master and was able to run both of those targets successfully, so I'm guessing that this is an issue with the version of make.  Please do still paste that output.  If you're on OS X and your make is BSD's or some other variant, you can also try [installing GNU make](https://formulae.brew.sh/formula/make#default) and using `$ gmake ...`.

**Comment by sneridagh** [comment]
@rpatterson I tested it with GNU make and worked well... indeed should be an incompatibility of using the OSX one.

**Comment by sneridagh** [comment]
Merged!

**Pull request merged**
