### PR TITLE
Control panel for relations

### PR DESCRIPTION
**Pull request by ksuess**
- Inspect relations
- Edit relations
- Add relations to arbitrary targets
- Batch edit relations
- Second tab with actions to fix broken relations. 

**TODO**
- [x] Inspect relations
- [x] Modify relations: Add relation. Delete relation.
- [x] Implementation of service in plone.restapi ( ->  https://github.com/plone/plone.restapi/pull/1602)
- [x] Stats: how many relation elements per relation
- [x] Actions to fix broken relations (two actions: "rebuild" and "regenerate intids and rebuild relations")
- [x] many relations: fetching batch per batch. No. Search by source and target has to be narrowed down by UI user.
- [x] Filter by target: title, path
- [x] Filter by source: title, path
- [x] Add potential targets to add more relations
- [x] Add potential sources to add more relations
- [x] Bug fix in upcoming plone.api 2.0.3 "Create relation only if there is no existing one" https://github.com/plone/plone.api/pull/507

relations panel
Inspect and modify relations
  
fix relationsl
Fix relations

**Nice to have**
- [ ] ? Filter by target: content type, review state, …

### CODE REVIEW

**Comment by pbauer** [comment]
I like the ability to filter by source and target.

But I don't really understand how the output in the screenshot should work. When relations always point from one content item to another content what is then "Chassis" etc? 
I would prefer to duplicate the same UI as it is used in classic with links to source and to target. Or change the classic UI as well if there is better proposal. So far in classic inspecting looks like this:

rels
backrels

**Comment by ksuess** [comment]
A binary relation is a subset of the cartesian product of source set and target set. This UI provides this cartesian product as a matrix with checkboxes with event handlers to add or delete a relation.
The event handler adds or delete a relation element and gives a confirmation with a toast.
Apart from this, batch editing is possible via the checkbox row on top: check 'Chassis' and all displayed sources (filter by search field or filter by filter on the right side) get a relation to 'Chassis'.

The example above shows that 'Light system' has relation 'comprisescomponentpart' to ['Chassis', 'Electronics','Navigation System']
'Navigation System' has one relation of type  'comprisescomponentpart': the one to 'Electronics'

**Comment by erral** [comment]
does this PR add an action to get the relations of a given object? That would be useful too.

**Comment by erral** [comment]
Yes I mean exactly that.

Nowadays when we have a relation field in an object, to be able to get the related objects, we index the UID of the objects and then query the catalog to get that information. If an action is available, we can use that action that under the hood calls this endpoint and this way getting the related items could be easier.

**Comment by ksuess** [comment]
Oh my, now I get it, you mean a Volto action to fetch the relations! 
@pbauer started working on endpoints for relations in general and the relations controlpanel. 
In this PR I provide (will provide) Volto actions for relations in general and the relations control panel, which will attack these endpoints. So these actions can be taken for whatever you want to do with relations in Volto. How the actions will look like (and are already drafted here) with parameters relation name/type, backrelation, etc can be seen in Philips elaborated documentation for the future endpoints on the backend side: <will paste the link later. Netlify preview of PRs needs to be fixed>

**Comment by avoinea** [comment]
@ksuess @pbauer This PR needs some love :)

**Comment by ksuess** [comment]
I am prepared. Now I need the plone.restapi endpoint please, @pbauer. 
https://github.com/plone/plone.restapi/issues/1432#issuecomment-1279761099
_No endpoint on context, but one single endpoint /@relations on portal root.
@relations deals with the source/target/relation parameters._

**Comment by ksuess** [comment]
Did you know that you can manage your relations in Volto? Check it out! 
^ @nileshgulia1 @avoinea @tiberiuichim @pnicolli @sneridagh @fredvd @giuliaghisini @tisto @claudiaifrim @JeffersonBledsoe @pbauer @spereverde

**Comment by ksuess** [comment]
UI recomendations are turned into code. Tests are green. Let's review!

**Comment by tisto** [comment]
@ksuess I am currently writing the official roadmap for Plone 6.x. I am adding a link to the documentation for every PLIP. Do we have any kind of documentation for the relations control panel?

I'd also like to give people proper credit. Did anyone help you with this or did you work on this on your own?

**Comment by stevepiercy** [comment]
@ksuess @tisto I think this is the User Manual for it. [Finding links and references to the current page](https://6.docs.plone.org/volto/user-manual/links-to-item.html).

There's also developer docs:

- [Link Integrity](https://6.docs.plone.org/plone.restapi/docs/source/endpoints/linkintegrity.html)
- [Relations](https://6.docs.plone.org/plone.restapi/docs/source/endpoints/relations.html)
- [Relations](https://6.docs.plone.org/plone.api/relation.html)
- [`plone.api.relation`](https://6.docs.plone.org/plone.api/api/relation.html)

I hope that captured all of them. This was a huge effort!

**Comment by ksuess** [comment]
> @ksuess I am currently writing the official roadmap for Plone 6.x. I am adding a link to the documentation for every PLIP. Do we have any kind of documentation for the relations control panel?

No, control panels are not documented.
The relations control panel has a superb user experience  ;-) and is therefore self-explaining.


> I'd also like to give people proper credit. Did anyone help you with this or did you work on this on your own?

The relations control panel is my work.

**Pull request merged**
