### PR TITLE
cssnano.co is dead, use web.archive.org instead

### PR DESCRIPTION
**Pull request by stevepiercy**

### CODE REVIEW

**Comment by stevepiercy** [comment]
@tiberiuichim you were the author of this page, and a link is now dead for an external site. Is the content still relevant? I assume it is, so I used a web.archive.org link, but if it is not, then I would prefer to remove the irrelevant content and link.

**Comment by ichim-david** [comment]
> @tiberiuichim you were the author of this page, and a link is now dead for an external site. Is the content still relevant? I assume it is, so I used a web.archive.org link, but if it is not, then I would prefer to remove the irrelevant content and link.

@stevepiercy there is something wrong with the website but the package is still in active development. I would simply link to github https://github.com/cssnano/cssnano

**Comment by stevepiercy** [comment]
Thanks for the lead. I subscribed to https://github.com/cssnano/cssnano/issues/1569. Let's leave this PR open for now, and give them some time to respond. If they fix it, I'll close this PR, else point to the repo root.

**Comment by stevepiercy** [comment]
Closing in favor of https://github.com/plone/volto/pull/5853

**Pull request closed without merging**
