### PR TITLE
UniversalLink and ConditionalLink accepts also an item to link to.

### PR DESCRIPTION
**Pull request by giuliaghisini**
if item is of @type Link (has the remoteUrl property), a direct link to remoteUrl is generated if user is not logged.

This avoids the passage from the Link detail view page even when users are not authenticated. Especially when Link-type objects appears in listing blocks.

### CODE REVIEW

**Review by sneridagh — APPROVED** [review]

**Review by tiberiuichim — APPROVED** [review]
Can we have some documentation for the UniversalLink? It starts to get big and handle all sort of cases.

**Comment by giuliaghisini** [comment]
> Can we have some documentation for the UniversalLink? It starts to get big and handle all sort of cases.

where we could put this components'documentation?

**Review by nzambello — APPROVED** [review]

**Comment by tiberiuichim** [comment]
One option would be a story for Storybook, something like this:

https://github.com/plone/volto/blob/7216d1db01ee391332014152af37ca1ef7cb883b/src/components/manage/Toolbar/Dropdown.stories.js

Or a new page under https://docs.voltocms.com/recipes/

**Comment by giuliaghisini** [comment]
> One option would be a story for Storybook, something like this:
> 
> https://github.com/plone/volto/blob/7216d1db01ee391332014152af37ca1ef7cb883b/src/components/manage/Toolbar/Dropdown.stories.js
> 
> Or a new page under https://docs.voltocms.com/recipes/

i've added the storybook for UniversalLink

**Review by tiberiuichim — APPROVED** [review]

**Pull request merged**
