### PR TITLE
Block search engines from indexing content on Netlify preview builds

### PR DESCRIPTION
**Pull request by stevepiercy**
See https://github.com/plone/documentation/issues/1619

### CODE REVIEW

**Comment by stevepiercy** [comment]
https://deploy-preview-5725--volto.netlify.app/robots.txt looks good.

No headers got set. I'm looking into why.

**Comment by stevepiercy** [comment]
Actually the header does get set on Netlify only. I looked in the wrong place:

Screenshot 2024-02-01 at 2 47 50 AM

**Comment by ksuess** [comment]
I wonder if it would be enough in every Netlify "site" but plone/documentation to set the option "branch deploy" to none.

grafik

It remains the preview, which is per Netlify default prevented to be indexed by `X-Robots-Tag: noindex`.

**Comment by stevepiercy** [comment]
There is always at least one production deploy, which is either `6.0` for docs or `main` for volto. Setting it to `None` would be the default branch. I set both docs and volto to do just that. These PRs are still needed.

**Comment by stevepiercy** [comment]
See Netlify docs: https://docs.netlify.com/site-deploys/overview/#branches-and-deploys

**Comment by ksuess** [comment]
Yes, one published deploy always seems to be provided by Netlify. I also do not see a way to prevent every deploy but the preview, which is indeed where handy.
Approving.

**Review by ksuess — APPROVED** [review]

**Pull request merged**
