### PR TITLE
Bump razzle to razzle 3.2 (canary)

### PR DESCRIPTION
**Pull request by tiberiuichim**
This is testing version of razzle. See [razzle release page](https://github.com/jaredpalmer/razzle/releases/tag/v3.2.0-canary.1) for the basics. The biggest would be experimental support for react-refresh.

### CODE REVIEW

**Comment by tiberiuichim** [comment]
For some reason tests no longer run successfully with `yarn test`, but they do run with `yarn jest`. The answer is probably somewhere here: https://github.com/jaredpalmer/razzle/blob/canary/packages/razzle/scripts/test.js

**Comment by tisto** [comment]
@tiberiuichim "yarn jest"? WTF? :)

**Comment by tiberiuichim** [comment]
@tisto: `yarn jest` is the same as running `node_modules/.bin/jest`, in my case my shell is not configured for node_modules integration

**Comment by sneridagh** [comment]
Superseded by #1967

**Pull request closed without merging**
