### PR TITLE
Mark empty listings for optional hiding

### PR DESCRIPTION
**Pull request by ksuess**
Fix https://github.com/plone/volto/issues/4393

This does not modify the markup except that it adds a CSS class.

### CODE REVIEW

**Comment by ksuess** [comment]
Any objection?

**Comment by ksuess** [comment]
Despite ready, I would close this PR satisfied, with https://github.com/plone/volto/pull/3602 having an option to hide a "no result" listing at all, including the heading.

**Comment by sneridagh** [comment]
@ksuess can we merge both https://github.com/plone/volto/pull/3602 and this one?

/cc @erral @ionlizarazu

**Comment by ksuess** [comment]
Closed in favor of https://github.com/plone/volto/pull/4474

**Pull request closed without merging**
