### PR TITLE
Use debug library to optionally show i18n and shadowing errors

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Review by tiberiuichim — COMMENTED** [review]
I don't think it's needed to prefix the var with RAZZLE. I'd go for "VOLTO_DEBUG", so we can reuse the var, maybe?

**Comment by tiberiuichim** [comment]
Ah, or rather, we should use that debugger library so we can do 

```
DEBUG="volto" yarn start
```

I think it's being used by superagent, I always do like `DEBUG="superagent"`. Also, we use it in our yo generators.

**Comment by sneridagh** [comment]
This? https://www.npmjs.com/package/debug

I like it!

**Comment by sneridagh** [comment]
DEBUG=volto:i18n
DEBUG=volto:shadowing

and then DEBUG=volto:* ?

**Comment by tiberiuichim** [comment]
@sneridagh Yes yes, that would be the best

**Pull request merged**
