### PR TITLE
Internationalization add urser form

### PR DESCRIPTION
**Pull request by wesleybl**

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Comment by wesleybl** [comment]
@sneridagh by mistake I committed directly to the 16.x.x branch, to make a backport. See if I need to revert. Sorry for the mistake.

**Comment by sneridagh** [comment]
@wesleybl I guess that reverting will add more noise even. No worries but please pay more attention to it. Create always a backport PR from the squashed commit in master. Target it to the milestone 16.x.x

**Comment by davisagli** [comment]
@sneridagh Should we add a branch protection rule for the 16.x.x branch so this can't happen by accident?

**Comment by sneridagh** [comment]
@davisagli done.

**Pull request merged**
