### PR TITLE
Fix race condition in rendering the toolbar in multilingual sites after saving a page

### PR DESCRIPTION
**Pull request by pnicolli**
This happens very rarely but we saw it happen in production. The PATCH to the server goes through and the saving happens, then the user is rerouted to the view, the content reducer is reset and if the rendering happens at that time, before the GET response comes, the view breaks.

Also, in this PR is a minor fix for the content reducer that currently loses locking info when the GET_CONTENT_SUCCESS action comes.

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]
I've noticed the problem too

The worse part, as far as I'm concerned, is that at no point should the store.content be completely replaced. https://github.com/plone/volto/issues/3649

It implies a problem with the lock API design. If possible, the full content should be refresheed together with the lock (if no other solution is found).

**Comment by sneridagh** [comment]
I tried to fix that also, but it turns out the lock mechanism is broken. Maybe we should revisit it and rethink it again.

**Review by avoinea — APPROVED** [review]

**Comment by erral** [comment]
We have faced this too.

**Comment by pnicolli** [comment]
> I tried to fix that also, but it turns out the lock mechanism is broken (see tests). Maybe we should revisit it and rethink it again.

@sneridagh Yes it could probably benefit from a rework, but I believe that a very small fix like this could be released in the meantime. This is still breaking multilingual sites from time to time, when I forget to backport this customization to new clients.

**Comment by pnicolli** [comment]
Closing because fixed in #4377

**Pull request closed without merging**
