### PR TITLE
upgrade semantic-ui to 2.0.3

### PR DESCRIPTION
**Pull request by nileshgulia1**
#2176 
#### changelog
https://github.com/Semantic-Org/Semantic-UI-React/releases/tag/v2.0.0

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Comment by tiberiuichim** [comment]
This PR should be brought up to date.

**Review by nzambello — APPROVED** [review]

**Comment by nileshgulia1** [comment]
@sneridagh @tiberiuichim Can we merge this please?

**Comment by tisto** [comment]
@nileshgulia1 upgrading Semantic UI two versions requires careful consideration and extensive testing. We have to go through the full changelog of Semantic UI and figure out where we could have breaking changes. I did not look into this but my gut feeling is that this requires a breaking changes release of Volto. We have to wait until @sneridagh and I are back from holidays (2 weeks) before we can consider this to be merged. In any case, it would be good if lots of folks try this out in their projects to see if that breaks anything.

**Comment by nileshgulia1** [comment]
@tisto I agree, I've already started testing this in some of my local projects. It'd be great if it get used in a good number of volto projects, so that we can identify visual breaking changes.
The only reason of hurry is, there're some issues I'm facing with older version of semantic-ui, which might got already resolved in latest versions(let's say in dropdowns). It'd be great if we can give it a priority and identify the cons here.

**Comment by tiberiuichim** [comment]
@sneridagh can we plan to merge this? We're getting questions from the design team why we're using ancient version.

**Comment by nileshgulia1** [comment]
I've been using the latest semantic-ui in projects like FISE, so far haven't come across any issues.

**Comment by sneridagh** [comment]
@nileshgulia1 @tiberiuichim I took a look at the changelog and seems ok to me. Let's release it standalone, just in case.
@nileshgulia1 could you please take a look to the conflicts?

**Comment by nileshgulia1** [comment]
@sneridagh Sure

**Pull request merged**
