### PR TITLE
Recurrence widget

### PR DESCRIPTION
**Pull request by giuliaghisini**
there are still some tests to do, but if anyone wants to try and test it it would be highly appreciated!

### CODE REVIEW

**Comment by giuliaghisini** [comment]
All cypress tests are now available.

**Comment by tisto** [comment]
@giuliaghisini I noticed that merging this PR would significantly increase the size of the first js chunk:

````
File sizes after gzip:

  599.08 KB (+160.39 KB)  build/static/js/5.c4c82c88.chunk.js
  154.34 KB (+6.44 KB)    build/static/js/client.34072d1d.chunk.js
  100.02 KB (+3.08 KB)    build/static/css/5.373ed562.chunk.css
  27.61 KB                build/static/js/7.b41e8d28.chunk.js
  15.27 KB (-69 B)        build/static/css/client.fb882f73.chunk.css
  14.3 KB                 build/static/js/9.25dc75d5.chunk.js
  13.51 KB                build/static/js/8.c498712e.chunk.js
  8.88 KB (+418 B)        build/static/js/14.f06210b5.chunk.js
  8.72 KB (+938 B)        build/static/js/13.a659693e.chunk.js
  8.58 KB (-24.34 KB)     build/static/js/10.e4f548d1.chunk.js
  7.96 KB (+3.59 KB)      build/static/js/12.a781ae50.chunk.js
  7.63 KB (-1.31 KB)      build/static/js/16.cefa7078.chunk.js
  7.6 KB (+1.5 KB)        build/static/js/17.928a4e86.chunk.js
  6.25 KB (-2.46 KB)      build/static/js/15.61d2060c.chunk.js
  4.52 KB (-4.38 KB)      build/static/js/11.114be683.chunk.js
  3.48 KB (-73.94 KB)     build/static/js/6.3f4e4c9f.chunk.js
  1.92 KB                 build/static/js/react-select-async-creatable.cf1080b5.chunk.js
  1.46 KB (-190 B)        build/static/js/plone-volto-components-theme-View-EventView.65f5e6f6.chunk.js
  1.37 KB (-378 B)        build/static/js/runtime~client.68370e51.js
  1.18 KB                 build/static/js/react-select-creatable.70754a4a.chunk.js
````

Would it be possible to lazy-load the recurring widget js? I understand that this new widget requires more libs that will increase the overall bundle size. Though, we should try to keep the initial bundle as small as possible.

**Comment by tisto** [comment]
@giuliaghisini that looks a lot better:

````
File sizes after gzip:

  438.75 KB (+425.24 KB)  build/static/js/8.67676e62.chunk.js
  148.08 KB (-6.26 KB)    build/static/js/client.b0850aea.chunk.js
  96.95 KB                build/static/css/8.6e205dd0.chunk.css
  77.42 KB                build/static/js/4.3cd5ee64.chunk.js
  32.93 KB                build/static/js/2.66cbaa1b.chunk.js
  27.62 KB (+13.31 KB)    build/static/js/9.95827861.chunk.js
  26.67 KB                build/static/js/0.42d84cc5.chunk.js
  15.58 KB (+318 B)       build/static/css/client.ffdb23d8.chunk.css
  14.3 KB (+9.78 KB)      build/static/js/11.39c13eda.chunk.js
  13.51 KB (+4.93 KB)     build/static/js/10.c1f09368.chunk.js
  9.32 KB (+1.69 KB)      build/static/js/16.30576377.chunk.js
  9.29 KB (+1.69 KB)      build/static/js/17.08f328fc.chunk.js
  9.24 KB (+1.28 KB)      build/static/js/12.2e16286c.chunk.js
  9.1 KB                  build/static/js/21.4aefba3b.chunk.js
  8.82 KB (+2.57 KB)      build/static/js/15.42191293.chunk.js
  8.45 KB                 build/static/js/plone-volto-components-manage-Widgets-DatetimeWidget.cb16290d.chunk.js
  8.13 KB (-768 B)        build/static/js/14.2960123c.chunk.js
  7.8 KB                  build/static/js/19.a92789ec.chunk.js
  7.76 KB                 build/static/js/20.b8b69e26.chunk.js
  6.42 KB                 build/static/js/18.f94d82f6.chunk.js
  4.7 KB (-4.02 KB)       build/static/js/13.2ed720cc.chunk.js
  4.14 KB                 build/static/js/1.90b73de8.chunk.js
  3.39 KB                 build/static/css/4.983e23b6.chunk.css
  1.75 KB (+384 B)        build/static/js/runtime~client.e36edd6b.js
  1.46 KB (+1 B)          build/static/js/plone-volto-components-theme-View-EventView.84e219c9.chunk.js

✨  Done in 48.63s.
````

**Comment by tisto** [comment]
Seems the recurrence widget Cypress test fails on CI.

**Comment by giuliaghisini** [comment]
> Seems the recurrence widget Cypress test fails on CI.

The error was on default values, fixed widget and updated tests.

**Comment by giuliaghisini** [comment]
@tisto now it's ready to merge!

**Comment by giuliaghisini** [comment]
@tisto @tiberiuichim @pnicolli

**Comment by tisto** [comment]
@giuliaghisini I am ready to merge and release this. Though, there seems to be a minor z-index problem in the recurring overlay:

Screenshot 2020-07-29 at 14 29 07

I also noticed that clicking on the "Add date" datepicker at the bottom of the modal leads to a scrollbar in the modal and the datepicker popup is behind the bottom part of the modal. Though, I guess this could be a Semantic UI problem with modals.

**Comment by tisto** [comment]
@giuliaghisini I would merge this PR now, you can fix those issues in a separate PR. I am a little bit afraid of running into merge conflicts with this PR since I left it open for way too long, sorry for that!

**Comment by tisto** [comment]
Bundle size comparison:

````
File sizes after gzip:

  436.99 KB (+423.48 KB)  build/static/js/8.8123bedf.chunk.js
  148.9 KB (+191 B)       build/static/js/client.a80dcf0f.chunk.js
  102.15 KB               build/static/js/4.681fd6e6.chunk.js
  96.97 KB                build/static/css/8.1903f034.chunk.css
  32.93 KB                build/static/js/2.0ef9bb2a.chunk.js
  27.62 KB (+13.31 KB)    build/static/js/9.09187cd7.chunk.js
  26.67 KB (-3.54 KB)     build/static/js/0.87f3aabe.chunk.js
  15.78 KB (+250 B)       build/static/css/client.91026630.chunk.css
  14.3 KB (+5.37 KB)      build/static/js/11.fd5963fd.chunk.js
  13.51 KB (-19.41 KB)    build/static/js/10.3e8f82d2.chunk.js
  9.71 KB (+3.58 KB)      build/static/js/17.5e690233.chunk.js
  9.46 KB (+114 B)        build/static/js/16.38037cf7.chunk.js
  9.29 KB (+4.88 KB)      build/static/js/12.fd5ab0f7.chunk.js
  9.14 KB                 build/static/js/21.b9426174.chunk.js
  8.86 KB (+64 B)         build/static/js/15.69f1f1ad.chunk.js
  8.82 KB (+6.59 KB)      build/static/js/plone-volto-components-manage-Widgets-DatetimeWidget.9d7bdc5c.chunk.js
  8.18 KB (-346 B)        build/static/js/14.11492232.chunk.js
  7.84 KB (+374 B)        build/static/js/19.f5488387.chunk.js
  7.8 KB (-1 KB)          build/static/js/20.cdf7b9a6.chunk.js
  6.46 KB (-1.03 KB)      build/static/js/18.3561de68.chunk.js
  4.73 KB (-3.1 KB)       build/static/js/13.65096e18.chunk.js
  4.14 KB                 build/static/js/1.9baa586b.chunk.js
  3.39 KB                 build/static/css/4.983e23b6.chunk.css
  1.75 KB (+15 B)         build/static/js/runtime~client.9728021f.js
  1.46 KB (-189 B)        build/static/js/plone-volto-components-theme-View-EventView.7866f713.chunk.js

✨  Done in 40.95s.
````

**Comment by tisto** [comment]
@giuliaghisini merged! Thank you! You rock!!!

**Comment by giuliaghisini** [comment]
> @giuliaghisini I would merge this PR now, you can fix those issues in a separate PR. I am a little bit afraid of running into merge conflicts with this PR since I left it open for way too long, sorry for that!

sorry i read your comment only just now.. ok, we can fix that issues in a separate PR!

**Comment by giuliaghisini** [comment]
@tisto fixed z-index problems for datetime widget. 
I'm sorry, but I was wrong to push and i pushed directly to master instead of making a branch and pr. I tried to revert the commit, but master is rightly protected. My commit is 
https://github.com/plone/volto/commit/c0444f462b8dbd31f83c5aa829ca659df1f8718f

Sorry again, it's friday and i need holidays :-)

**Comment by tisto** [comment]
@giuliaghisini no worries. Thanks for the quick fix! Hope you can enjoy holidays soon! :)

**Pull request merged**
