### PR TITLE
Add hamburger menu animation

### PR DESCRIPTION
**Pull request by danalvrz**
Regarding https://github.com/plone/volto/issues/2022

- Added custom CSS animation, so it's not dependent on third party library.

### CODE REVIEW

**Comment by davisagli** [comment]
@sneridagh Can we include this for 17? It removes a dependency and about 2kb from the css bundle.

**Comment by sneridagh** [comment]
@davisagli I would leave this as 17 only, mark it as breaking.

**Comment by davisagli** [comment]
@sneridagh sorry, that was my intention.

**Comment by sneridagh** [comment]
No worries, I pushed for this today so I took care.

**Pull request merged**
