### PR TITLE
Initial implementation of the Album View component

### PR DESCRIPTION
**Pull request by AlexBueckig**
Initial implementation of the Album View using semantic-ui ImageGroups and Modals.

### CODE REVIEW

**Comment by AlexBueckig** [comment]
Here is a preview of the current album view:

Gallery1
Gallery2

**Comment by sneridagh** [comment]
@AlexBueckig What's the status here? Did you signed up the contributor's agreement?

**Comment by sneridagh** [comment]
Fixes #1066

**Comment by sneridagh** [comment]
@wkbkTill did you sign up the Plone Contributor Agreement? I remember you mention you did. Maybe there's a mismatch between the mails you've provided and the one you've commited this with?

Also, what's the status here? Can we merge?

/cc @AlexBueckig

**Comment by wkbkhard** [comment]
I wrote with Alex today and he said if the view itself is likeable it can be merged. We can do it on the sprint if you like!

**Comment by wkbkTill** [comment]
I'm sorry but I don't know where the problem is. I've signed the agreement at the beethoven sprint and verified the mail adress :/

**Comment by sneridagh** [comment]
For the record, all the contributors signed the CLA, only they made the commit with the wrong email.

**Pull request merged**
