### PR TITLE
Update middleware.ts

### PR DESCRIPTION
**Pull request by aliomarmohamed**
I want to commit this changes

### CODE REVIEW

**Comment by davisagli** [comment]
Thanks but this doesn't look like a helpful change.

**Comment by stevepiercy** [comment]
@aliomarmohamed please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html).

**Comment by aliomarmohamed** [comment]
> @aliomarmohamed you need to sign the Plone Contributor Agreement to merge this pull request.
> 
> Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

I already signed

**Comment by aliomarmohamed** [comment]
> Thanks but this doesn't look like a helpful change.

thank you , I just want to know how to contribute  , plone is the first open source project  I worked on , maybe I need some help

**Pull request closed without merging**
