### PR TITLE
wrap objectBrowserWidget with FormFieldWrapper

### LINKED ISSUE #1969: ObjectBrowserWidget should use FormFieldWrapper
FormFieldWrapper enables some additional functionality for all fields, such as `wrapped` and `columns`. This should be standard for all Volto widgets.

### PR DESCRIPTION
**Pull request by nileshgulia1**
fixes #1969

### CODE REVIEW

**Review by tiberiuichim — CHANGES_REQUESTED** [review]
I would have expected to see the file size go down, do we still need the internal grid?

**Comment by nileshgulia1** [comment]
@tiberiuichim I have used grid from `FormFieldWrapper`, but using this inline style scares me https://github.com/plone/volto/blob/6fd62cb2860bc7cf3cb7c36ea86bfd8bd03247d9/src/components/manage/Widgets/FormFieldWrapper.jsx#L127

**Comment by nileshgulia1** [comment]
@tiberiuichim I think its ready now, You can have a second look!

**Review by tiberiuichim — APPROVED** [review]

**Comment by nileshgulia1** [comment]
@sneridagh its ready , can merge it.

**Pull request merged**
