### PR TITLE
Fix for the long lasted issue when creating links in newly created te…

### PR DESCRIPTION
**Pull request by sneridagh**
…xt blocks not showing as links until you save.

### CODE REVIEW

**Comment by sneridagh** [comment]
All props for this one to @avoinea !!

**Comment by sneridagh** [comment]
@avoinea why the tests are failing?

**Comment by avoinea** [comment]
Because they were wrongly recorded :smile: 

Just kidding, I'll take a look.

**Comment by avoinea** [comment]
@sneridagh It looks like the focus on `componentWillUnmount` was the problem. I don't know why we'd want to focus on unmount?! :thinking: Removed it completely!

**Comment by sneridagh** [comment]
Yeah, strange... I also can’t remember why we left it like this... I will investigate a bit.

**Comment by sneridagh** [comment]
Probably my bad... 


https://github.com/plone/volto/commit/5b43e08f056fafe62f1e3da0e11e16ea6ac1687a

I can’t see now any use for that!

**Pull request merged**
