### PR TITLE
fix classname, warning in customization paths

### LINKED ISSUE #2297: Remove warning for "foreign" files in customization folders
```
The file .../schema.jsx doesn't exist in the @plone/volto (.../components/manage/Blocks/Title/schema.jsx), unable to customize.
```

This type of warning that appears when you customize a Volto component and you add some files in the same folder, I don't think it's needed.

### PR DESCRIPTION
**Pull request by nileshgulia1**
fixes #2297 and #2298

### CODE REVIEW

**Review by avoinea — APPROVED** [review]
LGTM.

**Comment by nileshgulia1** [comment]
@sneridagh @tiberiuichim What do you think, we merge it?

**Comment by tiberiuichim** [comment]
@nileshgulia1 The BlockToolbar change is fine.

For the other changes, it needs to be removed. As far as I recall, Victor thought the logging should stay.

**Comment by nileshgulia1** [comment]
Fixed in #2361

**Pull request closed without merging**
