### PR TITLE
changed docs folder structure

### PR DESCRIPTION
**Pull request by ktsrivastava29**
Earlier the folder structure was this plone/volto/docs/source/, one had to migrate one folder inside to access its files, I've know changes the folder structure to plone/volto/docs/.

fix: https://github.com/plone/volto/issues/3093

### CODE REVIEW

**Comment by ktsrivastava29** [comment]
@stevepiercy since a separate repo has been maintained for this (which I appreciate), I didn't realize at first I'd have to make adjustments there as well but now I've made the possible changes you can be find it here https://github.com/plone/documentation/pull/1198

**Comment by stevepiercy** [comment]
@ktsrivastava29 FYI, Volto has its stand alone docs because the developers like to be able to keep code and docs together, especially for the storybook, and it builds faster. At the same time, Plone Documentation includes Volto as a frontend.

**Comment by ktsrivastava29** [comment]
@stevepiercy Thank You for sharing this, I got a clearer picture of it now.

**Comment by ktsrivastava29** [comment]
@stevepiercy The tests are failing maybe we need to merge this [PR](https://github.com/plone/documentation/pull/1198) first.

**Comment by stevepiercy** [comment]
The Netlify builds fail because its configuration still looks for docs files in `docs/source`. That needs to be changed.

Before this item can be merged:

- [ ] Approval from a maintainer that moving the docs files up a directory is a good idea. (I do not want to make this decision without a maintainer's approval.)
- [ ] Resolve conflicts between volto's `master` and your `docs` branches.
- [ ] Configure Netlify to build out of `docs`. That's up to me or one of the other Netlify Plone Team members.
- [ ] Force rebuild to test for a successful docs build.
- [ ] After merge of this issue, merge https://github.com/plone/documentation/pull/1198

**Comment by ktsrivastava29** [comment]
@stevepiercy should i start a new discussion on this here [community.plone?](https://community.plone.org/)

**Comment by stevepiercy** [comment]
> @stevepiercy should i start a new discussion on this here [community.plone?](https://community.plone.org/)

No. The discussion is already taking place here, and we do not want one discussion topic in multiple places.

Let's get @sneridagh or @tiberiuichim to offer their opinion. Please be patient for a response.

**Comment by sneridagh** [comment]
@ktsrivastava29 agreed, all the elements of @stevepiercy list should be addressed first.

Also, if you have signed the contributor agreement already, please open a branch on the repo itself, then open the PR from the repo itself. So the GitHub Actions are run properly and we can push also fixes to the branch.

**Comment by ktsrivastava29** [comment]
@sneridagh to start a new pr, I'd have to close this one, so should I create another branch in this repo itself as you said and close this one?

**Comment by stevepiercy** [comment]
You can push your local branch to this repo directly instead of your fork. You might need to configure your local git remotes, adding this repo as "upstream".

**Comment by davisagli** [comment]
This PR is old and incomplete, so I'll close it.

**Pull request closed without merging**
