### PR TITLE
Allow search block variations to be restricted to internal use

### PR DESCRIPTION
**Pull request by ksuess**
Fix https://github.com/plone/volto/issues/3050

And it adds a first search block test!

### CODE REVIEW

**Comment by tiberiuichim** [comment]
@ksuess The addition of the test is really nice.

I wonder about the `variations_internal`. What is the use case? Is this something that's provided by Volto? Can it be formalized, in one way or another?

**Comment by ksuess** [comment]
> I wonder about the `variations_internal`. What is the use case? Is this something that's provided by Volto? Can it be formalized, in one way or another?

The use case is a search block in an administrative view for bulk editing. 
Problem is, that a variation is always in the search block variation field options for the editor. To achieve that a variation is not listed in this options i need to patch / shadow the SearchBlockView component or propose a change for Volto like this PR.
 
Instead of introducing a new `config.blocks.blocksConfig.listing.variations_internal`, an alternative way to distinguish between variations would be to introduce a new option of the variation itself `notforeditors`.

```
        config.blocks.blocksConfig.listing.variations: [
          ...config.blocks.blocksConfig.listing.variations,
          {
            id: 'subsriptions',
            isDefault: true,
            title: 'Subscriptions',
            template: ListingSubscriptions,
            fullobjects: true,
            notforeditors: true,
          },
        ],
```

**Comment by tiberiuichim** [comment]
One way to do this would be something like this:

- The end goal is for you to be able to write a custom schemaEnhancer for the search block which can enable/disable the variations in the select, based on the role of the user
- I can see that [here](https://github.com/plone/volto/blob/ce0657fd2357608dce34a9cfdaed2e222e1941b9/src/helpers/Extensions/withBlockSchemaEnhancer.js#L119-L142), if we switch the order of "apply schema enhancer" and "add the select field to the schema", you'll have the chance to tweak the variations select options, from your own custom schema enhancer. The only thing that's missing would be that variable or property that could be used, from the schema enhancer, to understand if the variations select options should be tweaked or not. I don't know how you discriminate between the "special editors" and "regular editors", maybe there's some easily accessible information in the system that can be grabbed by the HOC and passed to the schema enhancers?

**Comment by ksuess** [comment]
Obsolete: Immitate "SearchBlockView" with component "ListingBody" with appropriate props. And compose with "withQueryString" and "withSearch". No registration of config.blocks.blocksConfig.listing.variations needed. See https://github.com/plone/volto/issues/3050#issuecomment-1146857684

**Pull request closed without merging**
