### PR TITLE
`aria-*` attributes are now parsed correctly by jsx-lexer 2.0

### PR DESCRIPTION
**Pull request by stevepiercy**
## Before

Screen Shot 2022-07-15 at 2 26 02 AM

## After

Screen Shot 2022-07-15 at 2 26 10 AM

### CODE REVIEW

**Comment by stevepiercy** [comment]
This change does not cause the test failure. OK to merge?

**Comment by nileshgulia1** [comment]
> This change does not cause the test failure. OK to merge?

Yes, try restarting the build, maybe!

**Review by nileshgulia1 — APPROVED** [review]
Lgtm

**Comment by stevepiercy** [comment]
Rerunning the failed tests worked. Flaky things, them thar tests.

**Pull request merged**
