### PR TITLE
Upgrade to ESLint 6

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by sneridagh** [comment]
@tisto we can’t upgrade to eslint 6 without fixing several issues that it brings... I tried several times without success :(

**Comment by sneridagh** [comment]
@tisto Now I fully remember: 

https://docs.voltocms.com/upgrade-guide/#alpha-16-is-a-brownbag-release

I had to revert and release a17: https://github.com/plone/volto/commit/9efc231b188fca707c31e186f5821ef10a5cf4e0

We had problems with the run/build process when used from a project. The problem was not in Volto itself, but on how in a project the dependencies are looked up:

**Comment by tisto** [comment]
@sneridagh I had problems with eslint-config-react-app at first as well. Between your shot and mine was a major version upgrade to eslint-config-react-app 5.x. Maybe worth another shot?

**Comment by sneridagh** [comment]
@tisto sure let’s try it out. I can test it on a project this evening or tomorrow morning.

**Pull request merged**
