### PR TITLE
i18n for EventDatesInfo

### PR DESCRIPTION
**Pull request by mbarde**
to fix https://github.com/plone/volto/issues/3438

### CODE REVIEW

**Comment by erral** [comment]
I think that this suggestion does not work. I think that we need something with parameters like in Classic UI:

https://github.com/collective/plone.app.locales/blob/master/plone/app/locales/locales/plone.pot#L8866-L8883

**Comment by tiberiuichim** [comment]
@mbarde Yes, we need a full message with params, as @erral is suggesting. 

See the example in the docs:

```
function () {
  const messages = defineMessages({
    greeting: {
      id: 'app.greeting',
      defaultMessage: 'Hello, {name}!',
      description: 'Greeting to welcome the user to the app',
    },
  })

  return intl.formatMessage(messages.greeting, {name: <b>Eric</b>})
}
```

at https://formatjs.io/docs/react-intl/api/#formatmessage

**Comment by erral** [comment]
Last week I tried unsuccessfully to build such messages, trying to keep existing HTML, but it should be possible like @tiberiuichim suggests

**Comment by davisagli** [comment]
Closing since this is out of date and not our preferred solution.

**Pull request closed without merging**
