### PR TITLE
Support allowedBlocks within Text block / BlockChooser

### PR DESCRIPTION
**Pull request by avoinea**
See integration: https://github.com/eea/volto-group-block

### CODE REVIEW

**Review by sneridagh — APPROVED** [review]
LGTM

@avoinea @tiberiuichim wondering if we should document this somehow, somewhere. (Also things like this one).

**Comment by tiberiuichim** [comment]
@sneridagh I think we should start really building the styleguidist-based docs. Then it becomes obvious where things should be documented (or at least they're documented somewhere, instead of nowhere).

**Comment by tiberiuichim** [comment]
@sneridagh At EEA it was decided to go for Styleguidist and showcase each addon, complete with its components, it becomes hard to keep track of everything that's available and makes communication across companies easier.

**Comment by tisto** [comment]
Without having a strong opinion on the actual decision I think it would make things a lot easier if Volto core and the core contributing companies use the same technology to document stuff...just my 2c.

**Comment by tiberiuichim** [comment]
@tisto It would be nice to have Storybook, if available and we'd use it at EEA as well (for sure), but there's also an urgent need to adopt something. If we can't use Storybook then we have to go for Styleguidist.

**Review by tiberiuichim — APPROVED** [review]

**Comment by sneridagh** [comment]
@tiberiuichim crap, I merged from master into this one, I hope I didn't break anything in blocks_form branch

**Comment by tiberiuichim** [comment]
@sneridagh no worries :) nothing is broken, it was bound to receive master at one point

**Pull request merged**
