### PR TITLE
Better handling of the click outside events

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by avoinea** [comment]
volto-slate toolbar basic text manipulation:

slate-bold

**Comment by avoinea** [comment]
[slate-metadata-mentions](https://github.com/eea/volto-slate-metadata-mentions)

slate-metadata-mentions

**Comment by avoinea** [comment]
[accordion-block](https://github.com/eea/volto-accordion-block)

accordion-block

**Comment by avoinea** [comment]
[columns-block](https://github.com/eea/volto-columns-block)

columns-block

**Comment by sneridagh** [comment]
Still not working, since floating elements attached outside (like the objectBrowser and the slate toolbar which are created and attached in the Body) falls outside. In the browser we have control, but in the toolbar we don't. That also prevents any other custom implementation that does the thing right, since from a11y perspective attaching things in the body is the correct way to go.

**Review by avoinea — APPROVED** [review]

**Pull request merged**
