### PR TITLE
Fix broken current folder by default in content browser for image lin…

### PR DESCRIPTION
**Pull request by sneridagh**
…ks, solves #1860

### CODE REVIEW

**Comment by sneridagh** [comment]
:tada: First PR in four months 🎉

**Comment by tisto** [comment]
w00t!

**Comment by tiberiuichim** [comment]
I think the main issue at hand is that ImageSidebar should be using ObjectBrowserWidget. ObjectBrowser should be hidden away behind registered widgets. Which reminds me, we have this [doc](https://docs.voltocms.com/blocks/editcomponent/#objectbrowserwidget) which explains how one could register ObjectBrowserWidget for links and images. Why don't we do that directly? Why not just have them available by default and use them in Volto's codebase?

**Comment by tiberiuichim** [comment]
> 
> 
> 🎉 First PR in four months 🎉

Hoping for many many more!

**Review by tiberiuichim — APPROVED** [review]

**Pull request merged**
