### PR TITLE
Fix sharing page after using Pluggables

### LINKED ISSUE #3557: Sharing is broken
**To Reproduce**
- create content
- try to share it with a group
- no groups shown to share with

**Versions**
Volto 16

Plugs are breaking the sharing. I think https://github.com/plone/volto/pull/3372 should be reverted or fixed.

BTW Why does this view need to have plugs? IMHO if a customization of the sharing view is need, then shadow. It's an edge case, isn't it? The introduction of plugs here in sharing needs to be discussed. At least it should work correctly with any change.

/cc @JeffersonBledsoe

### PR DESCRIPTION
**Pull request by JeffersonBledsoe**
Fixes #3557

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
The title of this PR says WIP. It is indeed still work in progress?

**Comment by JeffersonBledsoe** [comment]
> The title of this PR says WIP. It is indeed still work in progress?

Updated the title! I believe this fixes the issue, just wanted to check with the original issue reporter that everything is all good before requesting a merge :)

**Review by ksuess — APPROVED** [review]
Thank you for fixing the sharing!

**Comment by ksuess** [comment]
@sneridagh, would say this is ready.

**Pull request merged**
