### PR TITLE
Fix error: no such file or directory, open 'addon-testing-project/jsconfig.json' in addon clone command

### LINKED ISSUE #5239: @plone/scripts doesn't work with @plone/generator-volto alpha
**Describe the bug**
I tried using `@plone/scripts` to create an app for an addon with `@plone/generator-volto@7.0.0-alpha.10` but it doesn't work. I get the error:

```
Using addon-testing-project/src/addons
Cloning volto-blocks-grid from https://github.com/kitconcept/volto-blocks-grid.git...
✓ cloned volto-blocks-grid at addon-testing-project/src/addons/volto-blocks-grid
✓ update volto-blocks-grid to branch main
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'addon-testing-project/jsconfig.json'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at writeConfigFile (/home/user/.npm/_npx/d7641ae7b413ed98/node_modules/mrs-developer/src/index.js:325:8)
    at develop (/home/user/.npm/_npx/d7641ae7b413ed98/node_modules/mrs-developer/src/index.js:306:26)
    at async runGitGenerator (file:///home/user/.npm/_npx/d7641ae7b413ed98/node_modules/@plone/scripts/addon/generators.js:77:3) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'addon-testing-project/jsconfig.json'
}

Node.js v20.6.1
```

**To Reproduce**

1. `npm install --global @plone/generator-volto@7.0.0-alpha.10`
2. `npx -p @plone/scripts addon clone https://github.com/kitconcept/volto-blocks-grid.git --branch main --canary`

**Expected behavior**
app created.

**Additional context**

`jsconfig.json` was removed in: https://github.com/plone/volto/commit/08e384b638a79cbdd177bbe0177bf1a681369f62

But it is used here: https://github.com/plone/volto/blob/410b1e9ba577115a4eb39b27938975c9d9812a67/packages/scripts/addon/generators.js#L79

### PR DESCRIPTION
**Pull request by wesleybl**
In `@plone/generator-volto` > 7.0.0-alpha.6, we no longer have `jsconfig.json`, but `tsconfig.json`. So let's test if `jsconfig.json` exists and use it if it does. If it doesn't exist, we use `tsconfig.json`

Fixes #5239

### CODE REVIEW

**Review by sneridagh — APPROVED** [review]

**Comment by sneridagh** [comment]
@wesleybl FYI the add-on clone command is to be deprecated in favor of the docker approach, but for now, it will stay in scripts.

**Comment by wesleybl** [comment]
@sneridagh I'm using this command to bootstrap the development of an addon, not just for testing. Is there any other option for this? I think docker complicates things a little, because not all IDEs access the container's filesytem.

**Review by pnicolli — APPROVED** [review]

**Review by tiberiuichim — APPROVED** [review]

**Review by tiberiuichim — APPROVED** [review]

**Comment by sneridagh** [comment]
@wesleybl I'm ok to leave it there while there are still people using it. What I meant is that it would render unmaintained at some point. Also, we should point people to the recommended approach and not give several options for the same purpose.

**Comment by wesleybl** [comment]
@sneridagh can you please make a new release of `@plone/scripts`?

**Comment by sneridagh** [comment]
@wesleybl done.

**Comment by sneridagh** [comment]
https://github.com/plone/volto/releases/tag/plone-scripts-3.0.1
https://www.npmjs.com/package/@plone/scripts

**Comment by davisagli** [comment]
@sneridagh @wesleybl volto also needs to be updated to use the new release: https://github.com/plone/volto/blob/main/package.json#L244

**Pull request merged**
