### PR TITLE
Add storybook setup in scaffolding

### PR DESCRIPTION
**Pull request by tiberiuichim**
Based on https://github.com/plone/volto-quanta-project/tree/master/.storybook

I've added integration with addons `razzle.extend.js` main webpack modifier.

I think this is a simplistic setup right now, I think with a bit of effort we can change the main.js to load the addons from the package.json and then run storybook on all of them. I don't know. Thoughts on this?

CC @plone/volto-team

### CODE REVIEW

**Comment by pnicolli** [comment]
Iirc, I have a working setup that includes addons as well. I wanted to share it but found no time yet. I will let you know asap.

**Comment by tiberiuichim** [comment]
@pnicolli Can you take a look at this setup? If there's anything else needed in it? Otherwise, from my perspective, it's "good to go".

**Comment by sneridagh** [comment]
@tiberiuichim @pnicolli merging it for now.

**Comment by pnicolli** [comment]
Yeah, sorry, I was really swamped with other things. I will prepare a separate PR shortly for addons

**Pull request merged**
