### PR TITLE
Use Plone's language cookie

### PR DESCRIPTION
**Pull request by cekk**
Without using **I18N_LANGUAGE** cookie we have the problem that edit interface (the one that came from Plone api) and toolbar aren't in the right language in LanguageSelector component because Volto use a different cookie (**lang**).

I'm not a master in js tests so i don't know how to test this. If we need some tests, someone can help me?

### CODE REVIEW

**Comment by cekk** [comment]
@tisto is it normal that the ci fails on runnig Plone buildout? I haven't touched that part

**Comment by tisto** [comment]
@cekk not really. Seems like there is a buildout version conflict with plone.schema>=1.2.1.

**Comment by tisto** [comment]
@cekk could you try to rebase with master please? I just merged https://github.com/plone/volto/pull/1786. This should fix it.

**Comment by tisto** [comment]
I am wondering about the reason not to use the Plone cookie name in the first place...

**Review by tiberiuichim — APPROVED** [review]
LGTM, maybe merge master? I think tisto has made the required changes to buildout.cfg

**Comment by cekk** [comment]
i should have rebased it this morning

**Review by avoinea — APPROVED** [review]

**Comment by sneridagh** [comment]
@cekk added a missing lang cookie in the server part. LGTM.

It fixes a very annoying issue. The question is if that should be controlled via a cookie in the backend... when, other translations do not require the cookie to work (e.g the types dropdown)

**Pull request merged**
