### PR TITLE
fix the issue-#5359.

### PR DESCRIPTION
**Pull request by gauravsingh94**
Fixed the icon position of the event recurrence.

Final output will look like this.

Screenshot from 2023-11-05 10-37-25

### CODE REVIEW

**Comment by stevepiercy** [comment]
@gauravsingh94 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).

**Comment by gauravsingh94** [comment]
@stevepiercy 
Suppose I get verified in 2 days then this pr will ready for merge or I have to again make a pr after getting verified?

**Comment by gauravsingh94** [comment]
@stevepiercy I have signed the plone contributor agreement but it is not updated here.

**Comment by stevepiercy** [comment]
> @stevepiercy I have signed the plone contributor agreement but it is not updated here.

https://6.docs.plone.org/contributing/first-time.html#plone-contributors-team

> New users, including GSoC applicants, are assigned to the Contributors Team _within a few days after they have signed and returned the Plone Contributor Agreement_. [emphasis added]

**Comment by stevepiercy** [comment]
> Suppose I get verified in 2 days then this pr will ready for merge or I have to again make a pr after getting verified?

@gauravsingh94 please do not close and reopen PRs for the same issue. Be patient.

Meanwhile within the link I previously posted [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), please read and follow [Change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry) and [Specific contribution policies of projects](https://6.docs.plone.org/contributing/index.html#specific-contribution-policies-of-projects). I hope I do not have to post more links to sections within the same pages that I have already asked you to read and follow.

**Comment by stevepiercy** [comment]
Closing due to no follow up. Please reopen after you resolve your GitHub email issue.

**Pull request closed without merging**
