### PR TITLE
Added anchor tag!

### PR DESCRIPTION
**Pull request by ishaan9006**
In reference to #4580.

Wrapped the label with an anchor tag and set the target to _blank to open linked items in a new tab.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@ishaan9006 for further guidance:

- https://6.docs.plone.org/volto/developer-guidelines/contributing.html
- https://6.docs.plone.org/contributing/index.html#making-contributions-on-github

**Comment by ishaan9006** [comment]
@stevepiercy Hey! Where exactly do I have to sign the Plone Contributor Agreement? I mean there is no button or something like that in http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html

**Comment by stevepiercy** [comment]
> @mister-roboto @stevepiercy Hey! Where exactly do I have to sign the Plone Contributor Agreement? I mean there is no button or something like that in http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html

I gave you links to version 6 docs, but you refer to version 5 docs. I don't know what to say.

**Comment by stevepiercy** [comment]
Oh, wait a minute, @mister-roboto is a jerk bot, giving out the wrong link. How do we fix that?

**Comment by gforcada** [comment]
@stevepiercy the link is here: https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/subscriber.py#L279

**Comment by stevepiercy** [comment]
PR submitted: https://github.com/plone/mr.roboto/pull/112

**Comment by falgunmpatel** [comment]
Sir @sneridagh, @stevepiercy and @tiberiuichim,
I closed this pull request as it is no more relevant to this issue. So core developers do not have to waste their time reviewing the obsolete PR. 

Should I have done this? Or I have done something wrong?

Thank You

**Comment by stevepiercy** [comment]
@falgunmpatel do not close another contributor's PR without asking them first. That is very rude. It in fact created more work for core developers, because now we have to respond to your poor judgment. Reopening.

The proper response would be to apologize to the original contributor and promise not to do that again.

Core maintainers may close PRs if they are obsolete, but this one is not. The original issue is still open.

**Comment by falgunmpatel** [comment]
> @falgunmpatel do not close another contributor's PR without asking them first. That is very rude. It in fact created more work for core developers, because now we have to respond to your poor judgment. Reopening.
> 
> The proper response would be to apologize to the original contributor and promise not to do that again.
> 
> Core maintainers may close PRs if they are obsolete, but this one is not. The original issue is still open.

Hey @ishaan9006, I am really sorry for my rude behavior in closing your PR. I hope that you will forgive me.
I would take care of this in future.
Since I am new to open source contributions, it will take a while for me to get to know the best practices.

Also thanks to @stevepiercy for guiding me with my new journey.

**Comment by sneridagh** [comment]
Thanks @ishaan9006 for your contribution, but since the duplicated PR and that you didn't go forward with this one, closing in favor of: #4600

**Pull request closed without merging**
