### PR TITLE
be able to extend volto

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
@robgietema fyi, the tests are passing--it seems like a coveralls issue.

**Comment by sneridagh** [comment]
@vangheem what happened with the builds? I'm restarting them right now.

**Comment by ebrehault** [comment]
@sneridagh maybe a NodeJS version thing?

Apparently in Docker you use 8.11.4, but in Travis you do install nvm 8.11.3 (which is probably good enough) but you do not use it.

Don't you think you should add `nvm use 8.11.3` in your before_install?

Of course, maybe it is not related, just saying.

**Comment by sneridagh** [comment]
@ebrehault good catch! Thanks, I will give it a try.

**Comment by tisto** [comment]
Travis is still failing with:

`Module not found: Can't resolve '~/../locales' in '/home/travis/build/plone/volto/src'`

https://travis-ci.org/plone/volto/jobs/494573587

**Comment by vangheem** [comment]
We should probably close this PR and just move all locales registration and settings to the config module.

**Comment by sneridagh** [comment]
Hi all! Closing this PR, since we will address multilingual and language registration in Volto 5 following a dynamic import approach given a set of chosen languages. Hugs!

**Pull request closed without merging**
