### PR TITLE
Adding basic PWA functionality

### LINKED ISSUE #937: Turn Volto into a PWA
- Add the basic manifest.json and neccessary boilerplate
- Add an application shell for better loading experience

### PR DESCRIPTION
**Pull request by iFlameing**
Fixes #937. I tested on my local environment and its working fine. I have attached a gif for your reference. @tisto can you review this :)

ezgif com-video-to-gif (1)

### CODE REVIEW

**Comment by iFlameing** [comment]
@tisto can you review this? please!!

**Comment by iFlameing** [comment]
I am closing and re-opening so that mister-roboto stop commenting.

**Comment by tisto** [comment]
@iFlameing is the PWA feature something we can enable/disable? I think create-react-app ships with a PWA but does not enable it by default. Maybe that's worth looking into.

**Comment by iFlameing** [comment]
@tisto I have created a new pr #1196  related to this because this pr is very old. I rebased it but it is failing the plone and guillotina test. I think that it will be refixed if you restart the travis ci. But I am closing this for now.

**Pull request closed without merging**
