### PR TITLE
Refactor hero

### PR DESCRIPTION
**Pull request by tiberiuichim**

### CODE REVIEW

**Comment by ArmanKukreti** [comment]
@avoinea is this issue "Refactor hero #4295" still open?

**Comment by tisto** [comment]
@sneridagh did we remove the hero block when we introduced the teaser block?

**Comment by sneridagh** [comment]
@tisto no, we didn't. They serve different purposes, one teases, the other don't.

**Comment by ichim-david** [comment]
Hero block has been removed from Volto core given the draftjs dependency as noted in 
https://6.docs.plone.org/volto/upgrade-guide/index.html#draftjs-dependency-and-text-table-and-hero-blocks-removed

I will close this pull request but not delete the branch in case someone wants to move the hero code to an add-on and integrate these changes from here in that add-on.

**Pull request closed without merging**
