### PR TITLE
Storybook logo component

### PR DESCRIPTION
**Pull request by danalvrz**
Added Logo component to storybook

### CODE REVIEW

**Comment by sneridagh** [comment]
@danalvrz could you please resolve the conflicts? Thanks!

**Comment by danalvrz** [comment]
@sneridagh done! Sorry for the delay

**Comment by tiberiuichim** [comment]
@danalvrz I think the biggest issue right now, and the reason why the PR is not merged yet, is uncertainty about the copyright of  the image. Either we include an attribution (and we ensure that we have the legal right to include that image), or include an image that can be freely used, for sure. I propose we go for including another image. Maybe something that's used on semantic-ui website? Thanks!

**Comment by stevepiercy** [comment]
I would suggest that the image be replaced with an official Plone logo. That would also reduce the image size from a bloated 1.02Mb to 4Kb.

plone-logo

**Comment by danalvrz** [comment]
@tiberiuichim @stevepiercy thanks for the help! I had changed the image for a Plone logo on a different branch that was merged already. But this update reduces the image's size by half, so it works even better.

**Review by tiberiuichim — APPROVED** [review]

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
