### PR TITLE
update control panel layout

### PR DESCRIPTION
**Pull request by danalvrz**
Regarding https://github.com/plone/volto/issues/4789

### CODE REVIEW

**Comment by danalvrz** [comment]
@ksuess I need to keep working on it, for the tests to pass, and to implement the checkbox change. I will work on it on Monday, but feel free to make any changes in the meantime!

**Comment by ksuess** [comment]
@danalvrz Looks good to me, but needs some work to be responsive. Can you fix this? Thanks.

image

**Comment by ksuess** [comment]
@danalvrz Please rebase your branch, I've made a change in mine https://github.com/plone/volto/tree/relations-control-panel

**Comment by danalvrz** [comment]
@ksuess yes, I'll fix the responsiveness and rebase

**Comment by danalvrz** [comment]
@ksuess I removed the `sticky` property for the labels because it was breaking the table's layout when horizontally scrolling. But I can revert that change.
Screenshot
Screenshot 2023-05-22 at 12 11 57 2

**Comment by ksuess** [comment]
That looks much better. 
I suggest to work with the grid gap to achieve the distance between source options and target options.
image

**Comment by ksuess** [comment]
Well, it is a challenge, but the sticky labels of the targets is in my eyes important to be able to manage the relations.

**Comment by ksuess** [comment]
For testing purpose, to create a lot of content with a lot of relations, you can create example conten with:
image

**Comment by danalvrz** [comment]
> That looks much better. I suggest to work with the grid gap to achieve the distance between source options and target options. 

Using the grid gap was the right call!

**Review by ksuess — APPROVED** [review]
LGTM, thank you @danalvrz !

**Pull request merged**
