### PR TITLE
Fix event date view

### PR DESCRIPTION
**Pull request by nileshgulia1**
#632 
-cc @sneridagh

### CODE REVIEW

**Comment by sneridagh** [comment]
@nileshgulia1 Can you please do a couple of changes? 

We cannot ship it just like this:

screenshot 2019-02-27 at 15 43 34

We need to make it a bit more human. Plone does this, which is not also super fancy, but it is something...

screenshot 2019-02-27 at 15 43 34

We need to use momentjs (we already have it in Volto) to make it look nicer. Please can you take a look at it?

Also, I want you to add a proper EventView for the Event content type (add it to the default config), https://github.com/plone/volto/blob/70dcec18eb48e40387e42e4f2cf733f9adf9dc58/src/config/Views.jsx#L18 So we are not reusing the DocumentView.

**Comment by sneridagh** [comment]
@nileshgulia1 I know that there is no mockup for it, but can you please also make it show all the fields that are in the Event content type? Like location, etc... Take a look into the Plone template to know which ones are shown (the ones in the main tab, except the metadata (change etc..) )

**Comment by tisto** [comment]
@nileshgulia1 do you plan to continue to work on this?

**Comment by nileshgulia1** [comment]
@tisto Yes, already done some research on it, currently busy here. I will
continue it maybe next week.

**Comment by pnicolli** [comment]
Continued work on this during Beethoven Sprint. Up to now, we have a view that shows all fields except recurrence. Also, i18n and some tests are needed.

**Comment by pnicolli** [comment]
Added more tests. Will have a look at recurrence in the next few hours, at least for the View.

**Comment by tisto** [comment]
@pnicolli what's the status of this PR? Still WIP or something we should review/look into?

**Comment by nileshgulia1** [comment]
@tisto I started to look into it where @pnicolli left-off.
Just started implementing the recurrence for the `View.` 
Not sure How it should look for the` Edit` though .

**Comment by pnicolli** [comment]
@tisto Unfortunately I don't remember the precise state of the PR but I think it was still waiting for recurrence handling. The conf took most of my energy in the last weeks, we are releasing the final version of the site (the one with the schedule!) in the next few days, I would have some time to work on other things after that, but it's completely ok if @nileshgulia1 goes on from where I left off, I have other PRs I can work on :)

Nilesh, if you find anything that I wrote that you want to discuss, feel free to contact me or comment the code directly here.

**Comment by pnicolli** [comment]
I noticed a bug I introduced in the right column with open-end events and added a quick fix for it.
I see there are improvements for recurrence. Let me know @nileshgulia1 if you need anything and if you will keep working on this, having events working (at least having a default view for them) is becoming more and more important while showing Volto to other people :)

**Comment by nileshgulia1** [comment]
@pnicolli Hi. Thanks for quick fixes. I'm looking forward to add more conditionals for event occurring biweekly, 'on specific days' and 'repeating events' etc. 
Expect this to be finished (at least covering major of the conditionals) by the end of this week.

**Comment by nileshgulia1** [comment]
@pnicolli I think the basic functionality for recurrence is implemented now. Can you please do a quick sweep review and let me know of any changes?

**Comment by nileshgulia1** [comment]
@pnicolli Thanks for reviewing. I didn't noticed any such libraries exist for parsing of recurrence rules. But yes using [rrule.js](https://github.com/jakubroztocil/rrule) make sense and reduces lot of efforts.

**Comment by sneridagh** [comment]
@pnicolli yeah better stick to known libraries that already focus in the problem and solves it.

**Comment by pnicolli** [comment]
@sneridagh Exactly, the widget is not part of this PR, this one just shows the recurrence info coming from Plone. @giuliaghisini is developing the widget in a separate branch. Would you prefer to have a Draft PR about that in order to see the state of the development?

Regarding this PR: Yeah, the reason why I kept them together is that they are related and are based on the same date formatting function. I will commit new names in a few minutes.
Also, one other minor reason why I kept them together is that the ``View`` folder is beginning to be quiet bloated with files imho, so we could maybe think of some different structure for v5...

**Comment by sneridagh** [comment]
@pnicoli It’s fine! No draft PR required at all! Thanks for the info!

**Pull request merged**
