### PR TITLE
Change the width of overlay

### LINKED ISSUE #4399: Link Integrity overlay is too narrowed

### PR DESCRIPTION
**Pull request by iFlameing**
Fixes #4399 

@tisto  screenshot

Screenshot 2023-02-06 at 5 00 16 PM

### CODE REVIEW

**Comment by sneridagh** [comment]
@iFlameing context? btw, looks too wide...

**Comment by iFlameing** [comment]
@sneridagh New screenshot

Screenshot 2023-02-14 at 7 07 35 PM

**Comment by iFlameing** [comment]
> @iFlameing context? btw, looks too wide...

When we haver large text in overlay it not looks good. So I changed the size to medium.

**Comment by iFlameing** [comment]
I will add changelog tomorrow morning.

**Comment by sneridagh** [comment]
@iFlameing changelog please

**Comment by iFlameing** [comment]
@sneridagh done.

**Review by davisagli — APPROVED** [review]

**Pull request merged**
