### PR TITLE
Fix addon registry

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by avoinea** [comment]
@sneridagh It seems to be ok now but the addons are not listed in control-panel:

### Before:

before

### After

after

**Comment by sneridagh** [comment]
@avoinea I know, I filtered only for "registered" === Declared in `package.json` `addons` key now. Do you think that it's useful that it shows all of them?

**Comment by sneridagh** [comment]
So addons in addons are not showing now.

**Comment by avoinea** [comment]
@sneridagh Would helpful to show them all. At least in our case :smile:

**Comment by sneridagh** [comment]
Problem is that we can't differentiate "addons" from non addons (libs) in dev

**Comment by avoinea** [comment]
@sneridagh Then I think we can leave with it :smile: As we have the kitkat version, we can easily track the included addons :wink:

**Review by avoinea — APPROVED** [review]

**Comment by sneridagh** [comment]
Then we will be in square one again, since will be addons there that will not being really applied. (Eg. Ones coming from volto.config.js)

**Review by tiberiuichim — APPROVED** [review]

**Comment by tiberiuichim** [comment]
I think this would be useful to show in the control panel: 

https://github.com/plone/volto/blob/74723c5c3500797bcc517ec5416b4f7889c3b782/addon-registry.js#L268-L272

**Comment by sneridagh** [comment]
Nice! Will do!

**Pull request merged**
