### PR TITLE
Refactor CT icons helper: add getContentIcons

### PR DESCRIPTION
**Pull request by nzambello**
Moved getIcon into unique helper getContentIcons, which is extendable in config.
Added default icons in config/ContentIcons.
Used getContentIcons helper for ContentsItem and ObjectBrowser.
Added this feature in docs.

In Volto projects, you can configure this for custom content types like:

```js
import * as config from '@plone/volto/config';
import courseSVG from './icons/course.svg';

export const settings = {
  ...config.settings,
  contentIcons: {
    ...config.settings.contentIcons,
    Course: courseSVG,
};
```

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Review by tisto — APPROVED** [review]
@nzambello awesome new feature! I am just wondering if this is a breaking change. getIcon still exists and can be used. Therefore this should be a backward compatible change even when people have customized views, right?

**Review by giuliaghisini — APPROVED** [review]

**Comment by nzambello** [comment]
> @nzambello awesome new feature! I am just wondering if this is a breaking change. getIcon still exists and can be used. Therefore this should be a backward compatible change even when people have customized views, right?

Right, but the helper have been moved and this could be considered breaking even if was not used anywhere and in components were using their own methods.
So I guess this could be considered breaking but not much 😂
I think this should be released in a minor for semver.

**Review by sneridagh — APPROVED** [review]

**Comment by tisto** [comment]
> > @nzambello awesome new feature! I am just wondering if this is a breaking change. getIcon still exists and can be used. Therefore this should be a backward compatible change even when people have customized views, right?
> 
> @tisto Right, but the helper have been moved and this could be considered breaking even if was not used anywhere and in components were using their own methods.
> So I guess this could be considered breaking but not much 😂
> I think this should be released in a minor for semver.

You mean this line here, right?

https://github.com/plone/volto/pull/1981/files#diff-f3a239449bbebaac8df3a75ce26114955a8ef7a2b7f768ce0a83bdae7e8972b4L21

That's technically a breaking change then. As long as we do not differentiate between a public and an internal API, all API/helpers changes are breaking changes.

**Comment by tisto** [comment]
I'd say it is time for another major release. Can we add a short paragraph to the upgrade guide? @sneridagh what do you think?

**Comment by sneridagh** [comment]
Indeed, in fact, we already have a good bunch of things in store for Volto 9. I pretend to make the proposal tomorrow at the meeting.

**Comment by nzambello** [comment]
I'd have another feature to add to this I guess. I'm trying to add fontawesome icons for our project CTs but that's not simple right now.

**Comment by nzambello** [comment]
> I'd have another feature to add to this I guess. I'm trying to add fontawesome icons for our project CTs but that's not simple right now.

Ok, I figured out that's ok, I needed to import svgs directly as in Volto

**Comment by tisto** [comment]
@plone/volto-team we need a couple of lines in the upgrade guide. Then this one is good to go into 9.x.x.

**Comment by nzambello** [comment]
> @plone/volto-team we need a couple of lines in the upgrade guide. Then this one is good to go into 9.x.x.

@tisto done

**Review by avoinea — APPROVED** [review]

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
