### PR TITLE
fixed Responsive Error in login page

### PR DESCRIPTION
**Pull request by SayanDeveloper**
I have solved the issue #3250 

Before :
oldPlone

After : 
newPlone

@fredvd @stevepiercy

### CODE REVIEW

**Comment by fredvd** [comment]
@SayanDeveloper this comment is not about the contents of your PR but a workflow change we're at the moment discussing and impelenting  in the community. :-)

@sneridagh @mauritsvanrees @davisagli @stevepiercy 

In this case, since the contributors agreement has not been signed, an authorised volto dev IMHO shouldn't approve and run the workflows. fix the 'legal' blocker first before we others spend more time on fixing code etc. I have seen 2 PR's recently where everything was fixed and then someone didn't understand and/or didn't want to sign the CA and it's hangimg now.

On the other hand, when the developer is onboard and added to the contributors team and the Plone organisation on GitHub, how do we pick up and continue from here?

Suggestion:  we could add that in the mr.roboto text and make the author/owner responsable?  "when you receivd confirmation that your CA has been processed, ping a developee to check this PR again?

another nice to have: can we block the worklows while the CA hasn't been signed? wishfull thinking maybe.

**Comment by SayanDeveloper** [comment]
But sir I have already sent the signed agreement document to the mentioned email ID. If possible pls verify my agreement.

Thank you.

**Comment by fredvd** [comment]
> But sir I have already sent the signed agreement document to the mentioned email ID. If possible pls verify my agreement.

Ah, that's great. :-) The community member processing your contributors agreement is not the same person as the people who will be assisting you in getting your contribution reviewed and merged. So that will take some time, for which you will have to have some patience.

And that is what's my comment about, how to make sure that you as a first time contributor are not waiting too long, once you have been added to our Contributors Team, so you can continue working on your contribution.

**Comment by SayanDeveloper** [comment]
okay got it :-)

**Comment by stevepiercy** [comment]
@fredvd let's take the workflow discussion to a new issue https://github.com/plone/volto/issues/4632, and leave this PR for just the content.

**Pull request closed without merging**
