### PR TITLE
Fix search block input clear button doesn't reset the search

### PR DESCRIPTION
**Pull request by iFlameing**

### CODE REVIEW

**Review by sneridagh — APPROVED** [review]

**Comment by ionlizarazu** [comment]
I think this should be managed by the `onTriggerSearch` function. With this modifications the url doesn't change when the last char is removed from the input.

**Comment by sneridagh** [comment]
@ionlizarazu good catch. The idea is to merge this one, then https://github.com/plone/volto/pull/4698, so both have to get along.

@iFlameing could you please take a look?

**Comment by ionlizarazu** [comment]
@sneridagh I would reverse the merging order.
We have deeply tested  #4698 and i think is a good improvement wich is not directly related with this bugfix.
Also, it would be desirable to have more intense tests for the search block to prevent this kind of issues, right? (I'm working on some tests for this PR)

**Comment by ionlizarazu** [comment]
I've pushed some tests that I think are the minimum for the seach block live mode input. We should also test the not live searching mode, but I haven't gotten that far :sweat_smile:

**Comment by sneridagh** [comment]
@iFlameing @ionlizarazu the other PR has been around for a while, could we amend and finish this one?

**Comment by ionlizarazu** [comment]
I've added the pending not live search block tests, and all are passing, but I don't know why is failing the grid-block test

**Comment by ionlizarazu** [comment]
Ready for me @sneridagh @iFlameing @erral

**Pull request merged**
