### PR TITLE
Replace `parcel` with `tsup`. Better types, better tsconfig. Move to ESM.

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Review by davisagli — APPROVED** [review]
@sneridagh What does adding `type` in the imports do?

**Comment by sneridagh** [comment]
@davisagli type declares the import "Typescript only", so the interpreter knows that it does not belong to the code, so it strips it on build time when transpiling. It's a best practice nowadays. This is enforced by the `tsconfig` option "verbatimModuleSyntax".

I'm trying to come up with a golden `tsconfig` for all our browser libs, then one for the Node ones. I think we are near.

**Comment by davisagli** [comment]
@sneridagh So the type system can't even tell which things are types without giving manual hints? Pssh.

**Review by pnicolli — APPROVED** [review]

**Comment by sneridagh** [comment]
@davisagli it can, but sometimes it seems it has a hard time doing it, so it's better to explicit tell him :) It kind of makes sense in a bundler world!

**Pull request merged**
