### PR TITLE
Fix the css issue of browse button in Add Image Default Tab

### PR DESCRIPTION
**Pull request by uwaiszaki**

### CODE REVIEW

**Comment by nileshgulia1** [comment]
@uwaiszaki What's the status ?

**Comment by uwaiszaki** [comment]
@nileshgulia1  . I have added margin there.

**Comment by nileshgulia1** [comment]
@uwaiszaki try to rebase with the master branch and check if its fixed?

**Comment by uwaiszaki** [comment]
@nileshgulia1 . Still not working

**Pull request closed without merging**
