### PR TITLE
Adding support for URL in sidebar search

### PR DESCRIPTION
**Pull request by iFlameing**
Screenshot 2021-06-10 at 6 31 21 PM

### CODE REVIEW

**Review by sneridagh — APPROVED** [review]

**Comment by sneridagh** [comment]
@iFlameing can we have a Cypress test for this?

**Comment by tisto** [comment]
@sneridagh @iFlameing so you can type or paste a path into the sidebar search field (e.g. "/this-is-me") now and the sidebar will then show this content, right? What happens if a user paste a full URL (e.g. "https://mycompany.com/this-is-me")?

We should have indeed Cypress tests for all two (or three scenarios) mentioned above.

**Comment by iFlameing** [comment]
@sneridagh @tisto I haven't added the cypress test for the full URL because in cypress we have different URL and `flattento appurl` not doing it's job.

**Comment by iFlameing** [comment]
@sneridagh I don't know why cypress is failing. I saw that in master it is also failing.

**Comment by iFlameing** [comment]
@tisto @sneridagh Now we have the cypress test for this feature.

**Comment by iFlameing** [comment]
@tisto @sneridagh I will merge this after the greens CI. It is already approved and we have a cypress test for it.

**Pull request merged**
