### PR TITLE
Contents contrast UI

### PR DESCRIPTION
**Pull request by sah246ir**

### CODE REVIEW

**Comment by sah246ir** [comment]
> @sah246ir STOP!
> 
> I gave you the correct procedure for contributing in [#5312 (comment)](https://github.com/plone/volto/pull/5312#issuecomment-1759274868).
> 
> If you close this PR and open another for the same issue, I will block you from the Plone organization, because you have repeatedly not followed our contributing guidelines. You have [opened and closed 7 pull requests in 2 days](https://github.com/plone/volto/pulls?q=is%3Apr+is%3Aclosed+author%3Asah246ir).
> 
> Please follow our guidelines. Thank you!

im really sorry i will never repeat this practice. it's my first contribution. sorry again!

**Comment by stevepiercy** [comment]
It's a learning process. That's why I am trying to guide you to the correct procedure. We want to keep reviews and discussion about a pull request in one pull request, not eight.

If you need more information about how to do the right procedure, please ask. Thank you!

**Comment by Wagner3UB** [comment]
@sah246ir Hi, this isn't the correct way to address this issue, you don't need to change the text color. The blue color is not accurate, it deviates significantly from our color palette. In fact, you don't need to change the color entirely, just make adjustments to it.

Please look at the 'site.variables' file to find the correct color variable to use, and also check the 'table.overrides' file, I believe that's where these changes should be made.

**Comment by sah246ir** [comment]
> @sah246ir Hi, this isn't the correct way to address this issue, you don't need to change the text color. The blue color is not accurate, it deviates significantly from our color palette. In fact, you don't need to change the color entirely, just make adjustments to it.
> 
> Please look at the 'site.variables' file to find the correct color variable to use, and also check the 'table.overrides' file, I believe that's where these changes should be made.

i tried putting the styles in the overrides but the changes are not visible on the page.whereas they are visible if i include them in the less file.

**Comment by Wagner3UB** [comment]
@sah246ir I'm sorry, but these problems need to be solved differently. I can't explain how it should be done right now. I suggest studying about Volto and its [foundation here](https://training.plone.org/). Furthermore, if I were to explain how it's done, I would have solved it, not you.

**Comment by stevepiercy** [comment]
Closing due to no follow up. Please reopen if you want to fix your PR.

**Pull request closed without merging**
