### PR TITLE
Alias controlpanel

### PR DESCRIPTION
**Pull request by andreiggr**
Alias/Url Management interface from control panel & object
See: https://github.com/plone/volto/issues/1178

### CODE REVIEW

**Comment by ksuess** [comment]
The new control panel looks pretty good! 
May I suggest to give a confirmation via toast after adding an alias?

**Comment by andreiggr** [comment]
> The new control panel looks pretty good! May I suggest to give a confirmation via toast after adding an alias?

Agree. Toast notifications would look good for this case.

**Comment by giuliaghisini** [comment]
agree with @ksuess

**Review by avoinea — APPROVED** [review]
LGTM.

**Comment by avoinea** [comment]
@sneridagh As the Plone RestAPI part https://github.com/plone/plone.restapi/pull/1398 was merged and release I think it's safe to go on with this one also.

**Pull request merged**
