### PR TITLE
Block EditForm to allow editing blocks in sidebar, with schema 

### PR DESCRIPTION
**Pull request by tiberiuichim**
A simple Form.jsx-derived component that can render a schema as a form, in the block editing sidebar.

The schema is modeled after the serialization of Dexterity content types schema.

So, a schema can be:

```js
const IframeSchema = {
  title: 'Embed external content',

  fieldsets: [
    {
      id: 'default',
      title: 'Default',
      fields: [
        'url',
        'align',
        'privacy_statement',
        'privacy_cookie_key',
        'enabled',
      ],
    },
  ],

  properties: {
    url: {
      title: 'Embed URL',
    },
    align: {
      title: 'Alignment',
      widget: 'align',
      type: 'string',
    },
    privacy_statement: {
      title: 'Privacy statement',
      description: 'Short notification text',
      widget: 'cktext',
    },
    privacy_cookie_key: {
      title: 'Privacy cookie key',
      description: 'Identifies similar external content',
    },
    enabled: {
      title: 'Use privacy screen?',
      description: 'Enable/disable the privacy protection',
      type: 'boolean',
    },
  },

  required: ['url'],
};

export default IframeSchema;
```

And then the code that uses this would be:

```jsx
import schema from './schema.js';

<SidebarPortal selected={this.props.selected}>
          <BlockEditForm
            schema={schema}
            title={schema.title}
            onChangeField={(id, value) => {
              this.props.onChangeBlock(this.props.block, {
                ...this.props.data,
                [id]: value,
              });
            }}
            formData={this.props.data}
          />
</SidebarPortal>
```

### CODE REVIEW

**Comment by sneridagh** [comment]
@tiberiuichim I can sneak that in into Volto 6 too. Is it ready?

**Comment by tiberiuichim** [comment]
@sneridagh That would be nice. My plan was to have some validation included as well, but it can be added later on as a new feature.

**Comment by tiberiuichim** [comment]
@sneridagh I'm at a place with no good internet connection, so I can't do a lot of development right now, but I'll try to add some documentation.

**Comment by sneridagh** [comment]
@tiberiuichim no problem! We can add the docs later too!

**Comment by sneridagh** [comment]
@tiberiuichim thanks!

**Pull request merged**
