### PR TITLE
New tiles chooser

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by sneridagh** [comment]
@robgietema @tisto it would be great if you could review it so I can cut a release before next week training.

**Comment by tisto** [comment]
@jackahl @steffenri could you write a cypress test next week for the tiles choose pls?

**Comment by sneridagh** [comment]
@tisto regarding hiding the title and description tiles, there's a setting for that, but unwired yet. I will wire it now.

**Comment by tisto** [comment]
@sneridagh works great! Will merge now.

**Pull request merged**
