### PR TITLE
Relative querystring

### PR DESCRIPTION
**Pull request by jackahl**
Fix for #1861

### CODE REVIEW

**Comment by sneridagh** [comment]
@jackahl I think the code you removed is required in order for the relative query to work. If I recall correctly @pnicolli did that:

https://github.com/plone/volto/pull/747/commits/f0797dc90f9d63387d3abe6c5259340e1386e14a

Are you sure now we can remove it? Most probably we can, due to the relative querystring-search improvements, but we need to be sure.

**Comment by sneridagh** [comment]
@pnicolli do you have time to take a look?

**Comment by jackahl** [comment]
@sneridagh at least for the tests I did it worked. In one of our projects, we even had the issue of the current code not returning the correct items, but my changes actually doing so (admittedly I could not reproduce the failure in lain volto). Do you know who touched that part of the API endpoint last and could give some insight?

**Comment by sneridagh** [comment]
@jackahl Piero did it, I asked him for a review. 

Anyway, it seems that was a temporary fix, waiting for the good solution (querystring context-aware) given this comment: https://github.com/plone/volto/pull/747#issuecomment-570940292

In case that Piero is busy, just go ahead.

**Comment by tisto** [comment]
@iFlameing could you write a Cypress test for this please?

```
Given a page that contains two documents "news item one" and "news item two"
   and two documents "about us" and "contact" on the portal root
When I add a listing block with a relative path query criteria with the value "."
 Then the listing block shows two items
   and "news item one" shows up in the listing block
   and "news item two" shows up in the listing block
   and "about us" does not show up in the listing block
   and "contact" does not show up in the listing block
```

**Comment by iFlameing** [comment]
@tisto You can see the cypress test in #1870

**Pull request merged**
