### PR TITLE
Translations german: Unauthorized, Login/Register

### PR DESCRIPTION
**Pull request by ksuess**

### CODE REVIEW

**Comment by ksuess** [comment]
@plone/volto-team test failure seems to be unrelated, can you have a look, thank you.

**Comment by sneridagh** [comment]
Master was red, just merged the fix https://github.com/plone/volto/pull/2087, please rebase and try again.

**Comment by ksuess** [comment]
thank you, @sneridagh!
@tisto, would you mind reviewing the german translation change for login and registration, thanks.

**Review by tisto — APPROVED** [review]

**Comment by tisto** [comment]
Thanks @ksuess!

**Comment by ksuess** [comment]
This pull request is about the first impression for a client user. 
Please make a release. The current situation is quite embarrassing. 

> Falls Sie noch keinen Zugang haben, Registrierungsformular Sie sich bitte zunächst.

> Sie versuchen eine geschützte Seite aufzurufen, bitte Einloggen zuert.

**Comment by sneridagh** [comment]
@ksuess https://github.com/plone/volto/releases/tag/10.7.0

**Pull request merged**
