### PR TITLE
Add outline to toolbar buttons

### LINKED ISSUE #6311: Toolbar buttons don't provide a focus outline [SC 2.4.7]
https://www.w3.org/TR/WCAG22/#focus-visible

Currently we don't have any focus indicator for the buttons in the toolbar. This is confusing when using a keyboard to navigate the site and is a failure of the WCAG 2.X success criterion noted in the title

### PR DESCRIPTION
**Pull request by JeffersonBledsoe**
Fixes #6311 

## Current progress

Screenshot 2024-09-24 at 16 56 59

Screenshot 2024-09-24 at 16 59 54

### CODE REVIEW

**Comment by JeffersonBledsoe** [comment]
@ichim-david Checks all green now. Not sure if this needs design input from anybody else but it's ready for merging from my perspective

**Review by giuliaghisini — APPROVED** [review]

**Review by Wagner3UB — APPROVED** [review]

**Comment by pnicolli** [comment]
A behavior that I have recently seen in good component libraries is to only add the outline when navigating with the keyboard, while avoiding it when clicking things, because that's redundant. I haven't looked into how to do that, but I think it would be a nice improvement here.

**Comment by ichim-david** [comment]
> A behavior that I have recently seen in good component libraries is to only add the outline when navigating with the keyboard, while avoiding it when clicking things, because that's redundant. I haven't looked into how to do that, but I think it would be a nice improvement here.

@JeffersonBledsoe this is why we had focus-visible selector instead of simply focus to ensure the outline shows up when using the keyboard navigation.  I would set it back as well to avoid outlines when mouse clicking

**Review by sneridagh — APPROVED** [review]
LGTM if someone promises me no outline will show when clicking 😂

**Review by pnicolli — APPROVED** [review]

**Pull request merged**
