### PR TITLE
Fix for issue #4561 location.assign replace with  location.replace

### PR DESCRIPTION
**Pull request by AbhishekCS3459**
@tiberiuichim Please review this Pull Request.

### CODE REVIEW

**Comment by AbhishekCS3459** [comment]
@mister-roboto where to get plone Contributors Agreement ??

**Comment by Azzam1503** [comment]
@AbhishekCS3459 https://plone.org/foundation/contributors-agreement

**Comment by saadkhan011** [comment]
Hi @mister-roboto 
   Is this issue still open can I work on it

**Comment by AbhishekCS3459** [comment]
> Hi @mister-roboto 
>    Is this issue still open can I work on it

Hey I am working on this issue, You should try to find another issue.

**Comment by stevepiercy** [comment]
@mister-roboto is a bot.

@AbhishekCS3459 @saadkhan011 in addition to the sage advice of our resident bot, please read contributing guidelines and follow their instructions:
- https://6.docs.plone.org/contributing/index.html
- https://6.docs.plone.org/volto/developer-guidelines/contributing.html

You must also open a PR from the repo, not your fork, to run GitHub Actions. This PR shall not be merged from an external fork.

**Comment by AbhishekCS3459** [comment]
> @mister-roboto is a bot.
> 
> @AbhishekCS3459 @saadkhan011 in addition to the sage advice of our resident bot, please read contributing guidelines and follow their instructions:
> - https://6.docs.plone.org/contributing/index.html
> - https://6.docs.plone.org/volto/developer-guidelines/contributing.html
> 
> You must also open a PR from the repo, not your fork, to run GitHub Actions. This PR shall not be merged from an external fork.

@stevepiercy Can you please let me know what are the reasons my pr got rejected so that I can solve it.

**Comment by stevepiercy** [comment]
Are you saying that you did not read my comment, the content at the links, or the result of GitHub workflows at the end of this issue? I'm sorry, but I don't know how else to help you. Please let me know what you specifically do not understand.

**Comment by stevepiercy** [comment]
https://6.docs.plone.org/contributing/index.html#granting-permission-to-publish

> ## Granting permission to publish
> Before you contribute, you must give permission to publish your contribution according to the license we use. You may give that permission in two ways.
> 
> - Sign the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement). This method also covers contributions to Plone code. It is a one-time only process.
> - In every pull request or commit message, include the following statement.
> 
>   > I, [full name], agree to have this contribution published under Creative Commons 4.0 International License (CC BY 4.0), with attribution to the Plone Foundation.

**Pull request closed without merging**
