### PR TITLE
Fix links, add commits

### LINKED ISSUE #3128: Links to GitHub should refer to a specific commit
There are a few links in the docs that refer to a specific lines in files that have been updated after the docs were written. These links should refer to a specific commit, or better yet, copy-paste the source code into the docs to avoid link rot.

- volto/upgrade-guide/index.md:378 - https://github.com/plone/plone.volto/blob/main/src/plone/volto/upgrades.py#L6-L64
- volto/recipes/environment-variables.md:70 - https://github.com/plone/volto/blob/master/api/buildout.cfg#L29-L40
- volto/developer-guidelines/language-features.md:32 - https://github.com/tc39/proposals/blob/HEAD/finished-proposals.md#finished-proposals

Could I get someone familiar with these links to update them?

### PR DESCRIPTION
**Pull request by sneridagh**
Fixes #3128

### CODE REVIEW

**Comment by sneridagh** [comment]
@stevepiercy the last one is legit, so I left it.

**Review by stevepiercy — APPROVED** [review]

**Comment by stevepiercy** [comment]
Looks good, just needs a changelog.

**Comment by stevepiercy** [comment]
I take that back. Would you please also pull in these changes to `conf.py`, specifically the settings `linkcheck_anchors` and `linkcheck_retries`, and any links in the volto docs that should be excluded by `linkcheck_ignore`?

https://github.com/plone/documentation/pull/1195/files

**Comment by stevepiercy** [comment]
I went ahead and pushed a commit with those changes I asked for, since I was inside it anyway. @sneridagh would you please review? Thank you!

**Comment by sneridagh** [comment]
@stevepiercy LGTM

**Review by stevepiercy — APPROVED** [review]

**Comment by stevepiercy** [comment]
I pushed a commit for changelog. When build is green, OK to merge.

**Pull request merged**
