### PR TITLE
Block chooser search

### PR DESCRIPTION
**Pull request by bipoza**
As a first step to this issue https://github.com/plone/volto/issues/1488, I have created a search input in the BlockChooser component to ease selecting blocks.

This seach box, filters the available blocks filtering by title.

https://user-images.githubusercontent.com/26112509/139233792-9a62e5bb-4416-4bbb-b842-4bd66514bdd5.mov

I think that activating this the component using a shortcut would be nice, but it required some thinking.
What do you think?

I keep working on doing some improvements.

### CODE REVIEW

**Comment by tiberiuichim** [comment]
I wonder if we should also search in variation titles. @sneridagh what do you think?

**Comment by bipoza** [comment]
I like the idea of being able to search by variations.
It helps a lot to find options that we cannot see from the block chooser.

https://user-images.githubusercontent.com/26112509/150611949-5c46f931-ad73-43e8-a4fa-16ecacacddbc.mov

**Comment by sneridagh** [comment]
Yes, why not... I also think it's valuable.

**Comment by tiberiuichim** [comment]
@bipoza I like the idea. It would be nice to show the variation title somehow, though the current design makes that difficult.

**Comment by bipoza** [comment]
> @bipoza I like the idea. It would be nice to show the variation title somehow, though the current design makes that difficult.

@tiberiuichim I have integrated it in a minimalist way. But I don't know if it's the best way.

Here an example. Any help or idea will be appreciated ;)

https://user-images.githubusercontent.com/26112509/150649107-b7d8b6b7-b4a3-47f4-b156-62db4e0f7219.mov


On the other hand, in the last [commit](https://github.com/plone/volto/pull/2787/commits/8907809e4d5bf51dde68dbdb0b0456b8bdfe3114) I added multilanguage filter support.

block_search_cat

**Comment by tiberiuichim** [comment]
@bipoza Nice, I like it.

**Comment by sneridagh** [comment]
@bipoza what's the status of this? Should we review it and push it for happen during the Beethoven Sprint?

**Comment by tiberiuichim** [comment]
@sneridagh Rob's PR to volto-slate is pretty close to finished... maybe 30 minutes of work, to make Alin happy. https://github.com/eea/volto-slate/pull/239

**Comment by bipoza** [comment]
> @bipoza what's the status of this? Should we review it and push it for happen during the Beethoven Sprint?

@sneridagh This is currently finished. It would be nice if you could review it during the Beethoven Sprint.

**Comment by bipoza** [comment]
> > @bipoza what's the status of this? Should we review it and push it for happen during the Beethoven Sprint?
> 
> @sneridagh This is currently finished. It would be nice if you could review it during the Beethoven Sprint.

**Comment by bipoza** [comment]
@sneridagh Have you had time to review it?

**Comment by sneridagh** [comment]
Sorry, this one was somehow lost at the bottom of the pantry. :) 

We have to shake it again and make it happen.

**Comment by erral** [comment]
I rebased with master, let's see the tests.

**Comment by ionlizarazu** [comment]
@sneridagh this is ready

**Review by sneridagh — APPROVED** [review]

**Comment by sneridagh** [comment]
@bipoza @ionlizarazu @erral @tiberiuichim sorry that it took so long to merge this one. I love it.

**Pull request merged**
