### PR TITLE
Read listing block schema from configuration registry

### PR DESCRIPTION
**Pull request by pnicolli**
This is to make the schema easier to customize. It becomes as easy as overriding the `blockSchema` key of the listing block with something imported from a file like this:

```javascript
import ListingBlockSchema from '@plone/volto/components/manage/Blocks/Listing/schema';

export const schemaListing = (props) => {
  const baseSchema = ListingBlockSchema(props);

  // customize schema

  return baseSchema;
}
```

I'm not sure if `schemaEnhancer` is an option for customization here, it is listed in the docs as the go-to way for customizing schema for variations, but not for the entire block.

### CODE REVIEW

**Comment by tiberiuichim** [comment]
100% this.

https://github.com/plone/volto/blob/a7e3e08a9d8fa4a829cad04c13566f117004ce30/src/helpers/Blocks/Blocks.js#L431-L432

We should set `blockSchema` in all components, it's setting an example and the only way form defaults are properly computed. What's more, my impression is that the schema should be injected into the block components (and fully under the control of the schemaEnhancers), rather then instantiated from the block edit components. See https://github.com/plone/volto/issues/4103

There's another use case that I hit recently: the data that we present to the block view should be based on the schema. Let's assume that I have a variation where I add a new field. I use the variation, set a value for the field, but then change the variation. The field widget is no longer presented, but the value is recorded in the block data, which leads to bugs.

**Comment by tiberiuichim** [comment]
@pnicolli It's possible to set a schemaEnhancer for the block, also for the variations. The block's schemaEnhancer is applied last.

So its: `blockSchema -> variation schemaEnhancer -> block schemaEnhancer`

**Comment by sneridagh** [comment]
+1 we need to make all the blocks (stock and add-ons) to use this approach. 

I'd say it's not breaking... what about you?

**Comment by pnicolli** [comment]
Yeah I don't think this is breaking anything.

**Comment by pnicolli** [comment]
I'm not sure I understood if something is missing here in your opinion, or if this is just a little forgotten, I forgot it myself in the last week. @sneridagh @tiberiuichim

**Review by tiberiuichim — APPROVED** [review]

**Comment by tiberiuichim** [comment]
@pnicolli My views on this PR are like this:

In the ideal scenario the listing block schema should not need to be computed/acquired by any listing block components, it should be automatically injected as a prop from the Volto's Edit block machinery. 

We could go with the changes here, but with the understanding that it's a temporary fix.

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
