### PR TITLE
Toolbar bottom section opacity fix

### PR DESCRIPTION
**Pull request by ichim-david**
Also sidebar full-width button should be hidden when sidebar is collapsed

### CODE REVIEW

**Comment by ichim-david** [comment]
@sneridagh Those Plone 6 test failures look fishy to me.
There is no way my opacity changes when the sidebar is collapsed would crash the plone rest API response 
test-failures
cypress-failure

**Comment by ichim-david** [comment]
@sneridagh here is a gif with my changes demonstrating what this pull request fixes
volto-icon-opacity

**Comment by sneridagh** [comment]
@stevepiercy why Netlify is building this one? It has no docs changes.

**Review by sneridagh — APPROVED** [review]

**Comment by stevepiercy** [comment]
> @stevepiercy why Netlify is building this one? It has no docs changes.

I'm not sure. Netlify should honor this line in `netlify.toml`:

https://github.com/plone/volto/blob/a1230dc38579d7161333828ad1aca54c9f4354ff/netlify.toml#L5

Per: https://docs.netlify.com/configure-builds/ignore-builds/#mimic-default-behavior

**Comment by stevepiercy** [comment]
Strange, the log indicates that it attempted to honor that command, but evidently it continued.

https://app.netlify.com/sites/volto/deploys/626fa8ee753aab00087830de#L14

Other recent deploy previews were canceled, including when this PR got merged to `master`.

https://app.netlify.com/sites/volto/deploys/626fb23578ceb100084897b7#L14

`¯\_(ツ)_/¯`

**Pull request merged**
