### PR TITLE
basque translation

### PR DESCRIPTION
**Pull request by erral**

### CODE REVIEW

**Review by davisagli — APPROVED** [review]
Approving though I can't review the translations. Feel free to merge or ask another Basque speaker to review.

**Comment by erral** [comment]
I usually wait @sneridagh to merge, but I can merge the translations without problems (the same goes for the spanish ones). I am pretty sure that we are the only ones that use Volto in basque and perhaps even in spanish :P

**Comment by sneridagh** [comment]
Yeah go ahead! We agreed that any Volto Team member can merge any PR that involves fixes if any other member has approved it. 

For locales I'd say same policy as p.a.locales applies.

**Comment by erral** [comment]
Ok, thanks. The point here is that I don't have the Merge pull request button enabled :confused:

**Comment by sneridagh** [comment]
Uh, I'll look into that!

**Review by sneridagh — APPROVED** [review]

**Comment by sneridagh** [comment]
and now?

**Pull request merged**
