### PR TITLE
Fixed client copy mutation, cleanup up move mutation for consistency

### PR DESCRIPTION
**Pull request by pnicolli**

### CODE REVIEW

**Comment by ichim-david** [comment]
@pnicolli @sneridagh it seems that the path needs to be allowed to be set for these crud operations, I noticed another pull request added https://github.com/plone/volto/pull/6301/files#diff-ca875ccb3b13f54d06884d6a8d9a696d1d331322bcc0c06ef618e083ce147eb4R11 that does something similar to Pierro's pull request but for querystring-search.

**Review by sneridagh — APPROVED** [review]
LGTM

@ichim-david do you think that this collides with the PR you mention? Or you wanted to raise attention to the other as well?

**Comment by ichim-david** [comment]
> LGTM
> 
> @ichim-david do you think that this collides with the PR you mention? Or you wanted to raise attention to the other as well?

Just raised awareness that it seems that the path needs to be added in several places

**Comment by pnicolli** [comment]
> Just raised awareness that it seems that the path needs to be added in several places

Yeah that's true, these will need to be fixed as we start using the library.

**Pull request merged**
