### PR TITLE
Refactored cell.jsx to functional component

### PR DESCRIPTION
**Pull request by Raman-Luhach**
Refactored cell.jsx from class-based to functional-based component.

This is my first contribution to volto. Please give feedback and I will try to rectify that.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@Raman-Luhach thank you for your contribution! Here are some things to address.

The change log check fails with this message https://github.com/plone/volto/actions/runs/10047245268/job/27768503949?pr=6182. You need to move the change log entry to the appropriate package, `packages/volto-slate`, per [Change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry).

Next run acceptance tests locally before creating a pull request according to [Acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html). Two GitHub workflows currently fail. That could be a flaky test. When you run tests locally, it is easier to compare against GitHub workflows and debug the issue. If tests pass locally, but fail in GitHub workflows, then post a comment with details and ask for assistance if you need help.

Finally keep your feature branch current with `main`. See [Update your pull request from your fork](https://6.docs.plone.org/contributing/first-time.html#update-your-pull-request-from-your-fork).

**Comment by stevepiercy** [comment]
@Raman-Luhach CI checks still fail. Please resolve them.

**Comment by stevepiercy** [comment]
@sneridagh this is another PR that was not listed in #4460, but that list may have been before the monorepo and splitting out volto-slate. Please advise.

**Comment by davisagli** [comment]
This is already in progress in #4963

**Pull request closed without merging**
