### PR TITLE
Added translations to spanish @macagua

### PR DESCRIPTION
**Pull request by macagua**
- Spanish translation.

### CODE REVIEW

**Comment by macagua** [comment]
@sneridagh please, can you check out, if all ok, merge it?

**Comment by tisto** [comment]
@macagua Travis fails because your i18n is outdated. Please re-run "yarn i18n", commit and push.

**Comment by tisto** [comment]
@macagua it seems there are some files missing. Please check the Japanese translation PR: https://github.com/plone/volto/pull/951/files

**Comment by macagua** [comment]
@tisto with the command ``yarn i18n:check`` show the following error:
```
yarn run v1.19.2
error Command "i18n:check" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by macagua** [comment]
@tisto @sneridagh done!

**Comment by tisto** [comment]
@macagua in order to ensure a high code quality we try to always do code reviews before merging pull requests. Please do not merge your own pull requests in the future. Please also squash the PR in order to keep our git history clean and make sure you delete your branch afterwards.

**Comment by macagua** [comment]
@tisto I understand, I will take all your suggestions into account, for the next time! Thanks for the patience!

**Pull request merged**
