### PR TITLE
translation docs

### PR DESCRIPTION
**Pull request by erral**

### CODE REVIEW

**Comment by stevepiercy** [comment]
I started a review, and then I remembered. There already exists a guide for translations.

https://6.dev-docs.plone.org/volto/recipes/i18n.html

I will note that it is hidden under "Development Recipes", so perhaps either its name is not so great or this is not the best location.

**Comment by stevepiercy** [comment]
Adding links to issues in `plone/documentation` as a reference for a more complete picture.

- https://github.com/plone/documentation/pull/1268
- https://github.com/plone/documentation/issues/1267
- https://github.com/plone/documentation/pull/1265

**Comment by erral** [comment]
I think we can close this because all docs were integrated in the created skeleton branch

**Comment by stevepiercy** [comment]
As far as Volto is concerned, we now have a [top-level entry point for i18n/l10n](https://6.dev-docs.plone.org/i18n-l10n/index.html), which in turn directs readers to the specific [Volto implementation details](https://6.dev-docs.plone.org/volto/recipes/i18n.html).

I'm closing this issue as complete.

**Pull request closed without merging**
