### PR TITLE
Table Block: Naming of options and labels

### PR DESCRIPTION
**Pull request by iFlameing**
Fixes https://github.com/plone/volto/issues/2376

@tisto  screenshot

 
Screenshot 2021-04-30 at 4 40 30 PM

### CODE REVIEW

**Comment by ksuess** [comment]
sorry for interfering: It would help a lot to stay up to date with speaking titles.

**Comment by iFlameing** [comment]
@sneridagh I made the changes which @ksuess wanted :)

**Comment by ksuess** [comment]
@iFlameing I am really sorry that I did not explained what I meant good enough. I was not talking about the changes itself but the **Pull Request title** "Fixing translation of sidebar" that I changed to "Table Block: Naming of options and labels".

It is **in general** easier for me I and I think for all of us, if PRs have a title that makes clear what it wants to change.

**Comment by sneridagh** [comment]
@ksuess I agree, we have to make an effort on the PR titles (and descriptions), specially if no issue is related.

However, we thought that instead of leaving "orphan" these translations, we should maintain the ids. 

Also, related: do we want to go back to labels for ids, instead of the full English translation? I don't recall now the Plone policy /cc @erral

**Comment by sneridagh** [comment]
@iFlameing Since you based your fix in the previous commit, the msgstr are still wiped out :( Could you please create a new one?

**Pull request closed without merging**
