### PR TITLE
Fix SelectWidget vocabulary load on second component mount

### PR DESCRIPTION
**Pull request by avoinea**
See #2655

### CODE REVIEW

**Review by sneridagh — APPROVED** [review]

**Review by tiberiuichim — APPROVED** [review]

**Comment by avoinea** [comment]
Ha found another bug within ArrayWidget :smile: video on the way.

**Comment by avoinea** [comment]
https://user-images.githubusercontent.com/323385/133118481-47fb14d5-dd78-45de-942c-da80ef87061d.mp4

**Comment by avoinea** [comment]
Ok, the search one seems deeper:

https://github.com/plone/volto/blob/ec386e1b276138e6be0730b2aea1f798af2a2a4c/src/components/manage/Widgets/ArrayWidget.jsx#L289-L294

@sneridagh I think we can merge this for now, and treat the search issue in a separate issue/PR

**Comment by sneridagh** [comment]
Mmmm I already experienced this on duplicated widgets for the same vocabulary, so great to have a fix! However, never experienced that last one... I even fix a search issue lately, I thought that is behaving well (eg. the languages selector in the control panel.

Might help to know exactly the type of field/vocab and the instantiation and the resultant widget.

**Comment by sneridagh** [comment]
@avoinea do you need this in 13?

**Comment by avoinea** [comment]
@sneridagh Nope, already on 14 alpha. #yolo :)

**Pull request merged**
