### PR TITLE
Fullscreen sidebar

### PR DESCRIPTION
**Pull request by avoinea**
See #1345

### CODE REVIEW

**Comment by avoinea** [comment]
@tisto @sneridagh Please let me know if this is the right way of doing PRs?!

Then I can re-do the other PRs this way.

**Comment by tisto** [comment]
@avoinea thanks! Looks good!

**Comment by avoinea** [comment]
@rexalex signed the contributors agreement. Could someone take a look, please, @tisto ?!

**Comment by tisto** [comment]
@avoinea can we hide the <> icons on mobile? expanding does not make much sense on mobile.

**Comment by sneridagh** [comment]
@avoinea Several Albert comments, if you are willing to take a look at them too, while you are on this:

* The sidebar should be full size in height in mobile, because the icons are confusing, so you are tempted to use the x to close the sidebar. 
* The animation is too elastic for such a big element, can we use default ease-in ease-out one?
* Starting with the sidebar closed in mobile would be huge too, but I know it's a bit of effort, and we need a JS mobile detector (I already have used one, maybe I can take care of it).

**Comment by avoinea** [comment]
@tisto @sneridagh Should we merge this PR?

**Pull request merged**
