### PR TITLE
Added default placeholder for videos to embed them more lightly

### PR DESCRIPTION
**Pull request by giuliaghisini**
If no placeholder image was upload in sidebar, there wasn't a default placeholder for videos, and for YouTube and Vimeo videos, the iframe was immediately inserted on the page, causing the loading of all the resources of the iframe. 

If there were several videos on the page, the amount of uploaded assets was multiplied by the number of videos. This significantly slowed down page loading and performances.

Now, if no placeholder image is selected from user in sidebar, a default placeholder is loaded from YouTube or Vimeo to prevent the direct insertion of the iframe in the page.

### CODE REVIEW

**Comment by giuliaghisini** [comment]
@sneridagh @tiberiuichim

**Comment by giuliaghisini** [comment]
@sneridagh @tiberiuichim

**Review by sneridagh — APPROVED** [review]
LGTM, but please sync with master and fix the acceptance tests.

Also: I've made the cut already, master is v16 alpha. If that's not ok, please let me know, we can backport it to 15.x.x branch. Same for the last PR you've sent.

**Comment by giuliaghisini** [comment]
@sneridagh now is totally green!
if it possibile, we'd like to have this in volto 15 and not in volto 16 alpha

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
