### PR TITLE
New components: ObjectWidget, ObjectListWidget

### PR DESCRIPTION
**Pull request by silviubogan**
I have developed the widgets from this ticket: https://github.com/plone/volto/issues/1512 and I added tests, ready for PR and ready to be merged.

# Screenshots

# Summary

* new unit tests that pass (with snapshots and click simulation)

* the two components are registered in Volto config and tested in the
GUI, and the used strings are translatable

* there are some remaining TODO comments, mostly related to external
bugs

### CODE REVIEW

**Comment by tiberiuichim** [comment]
Those widgets assume a new schema extension, that the fields in a schema define a property called "schema", which is a Javascript object with another schema.

**Comment by tiberiuichim** [comment]
The ObjectListWidget also uses a modal to edit its content, this might now be convenient for everything. Maybe a new version of it can be developed, one that inline edits its content list.

**Comment by sneridagh** [comment]
@silviubogan it seems that it's something related with surge saving the content of the artifacts.

@tisto can you take a look?

BTW, @silviubogan @tiberiuichim we have to discuss the UI of the widgets whenever possible, I think it should be improved. Sorry for being out for some days, and coming out of the blue, but what kind of objects it can hold? and how we get the schema of that?

**Comment by tiberiuichim** [comment]
@sneridagh sure, that's to be expected. I'm available online on slack and discord, msg me whenever you have the time.

**Comment by tiberiuichim** [comment]
Split in a separate addon, for now at https://github.com/eea/volto-object-widget/

This makes it easier to test and document the widget (as there are no Volto components that use them).

**Pull request closed without merging**
