### PR TITLE
Addon configuration loading

### PR DESCRIPTION
**Pull request by tiberiuichim**
Just some docs for now, code will come soon.

### CODE REVIEW

**Comment by sneridagh** [comment]
@tiberiuichim first shot on it, let me know what do you think!!

**Comment by sneridagh** [comment]
@tiberiuichim I have to test it yet on production, it would be great if you could do that as well.

**Comment by tiberiuichim** [comment]
This branch still needs a lot of work. The current problem is related to webpack's dynamic imports. See https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import

I don't think it's worth pursuing dynamic imports, even if we make it work, the generated bundles would be sub-optimal (we'll no longer benefit from tree-shaking).

I'm working on an approach where we generate a js file that has the addon loading code. This ensures that webpack gets to "see" the package that we want to include in the bundle and keep its static import mechanism.

**Comment by tiberiuichim** [comment]
The PR is ready to be merged. @tisto @robgietema

**Comment by tisto** [comment]
@tiberiuichim awesome!!! Will try to find some time during the next days to look into it...

**Comment by tisto** [comment]
@tiberiuichim just wondering: do you use this in production?

**Comment by tiberiuichim** [comment]
@tisto no, not yet. There's a complete Volto project that you can clone and test it:
https://github.com/eea/volto-slate-project

```
git clone https://github.com/eea/volto-slate-project
cd volto-slate-project
yarn install
yarn start
```

I can't promise I can put this into "staging" pretty soon, as we're quite busy developing features.

**Comment by tisto** [comment]
@tiberiuichim can you please rebase? @robgietema approved the PR, so I will just have another look and then merge and release that thing!

**Comment by tisto** [comment]
@giuliaghisini @pnicolli @nzambello @cekk if possible I'd like to have a review from you folks as well. Just to make sure you are ok with that. That's a big and important decision. :)

**Comment by tiberiuichim** [comment]
The builds have passed, I'm not sure why their status is yellow.

**Comment by tisto** [comment]
@tiberiuichim I guess Travis hiccups. I will do another release, then merge this one tomorrow and do another release.

**Comment by tisto** [comment]
@tiberiuichim thank you Tiberiu. You rock! That's a big step forward for Volto!!!

**Comment by tiberiuichim** [comment]
@tisto thanks! 

Volto's future is very exciting. I'm happy to be able to work on that.

**Comment by tisto** [comment]
@tiberiuichim which PR is next? :)

**Pull request merged**
