### PR TITLE
Refs #850 - Show save/cancel on control panels

### PR DESCRIPTION
**Pull request by avoinea**
See #850

### CODE REVIEW

**Comment by tisto** [comment]
Travis is failing for all three builds. I do not see the re-run build button any longer in the Travis UI, otherwise, I could just re-run the build to see if the problem persists.

**Comment by tisto** [comment]
@avoinea can you please rebase?

**Comment by sneridagh** [comment]
How is that the GH Actions didn't run?

**Comment by tisto** [comment]
Maybe because the branch is not on the same repo?

**Comment by tisto** [comment]
I created a new PR and that triggered gh actions: https://github.com/plone/volto/pull/1366

**Comment by tisto** [comment]
WTF. Now gh actions run here as well...

**Pull request merged**
