### PR TITLE
Adding droppable placeholder to image block

### PR DESCRIPTION
**Pull request by iFlameing**

### CODE REVIEW

**Comment by sneridagh** [comment]
@iFlameing the image block already has a droppable area. What originated this requirement? Did you try in a vainilla Volto?

**Review by sneridagh — APPROVED** [review]
@iFlameing ok, after looking at the other PRs I see what it's about. We need to document a bit more the PRs and make sure are self-explanatory for people that come completely out of the blue.

**Comment by iFlameing** [comment]
@sneridagh sorry! for the inconvenience.

**Comment by tisto** [comment]
@iFlameing @sneridagh I also have no clue what this PR is about. @iFlameing can you please reference an issue or add a screenshot here please?

**Comment by iFlameing** [comment]
It is related to this issue.

droppable

**Comment by nileshgulia1** [comment]
@iFlameing I can see what's happening here. Although when using drag n drop by default, the pickup file (cursor) changes to '+' icon in the droppable area.

**Review by nileshgulia1 — APPROVED** [review]

**Pull request merged**
