### PR TITLE
Content rules init

### PR DESCRIPTION
**Pull request by andreiggr**
Frontend part for Content-rules.

### CODE REVIEW

**Review by tiberiuichim — COMMENTED** [review]
Could we have SendEmailInput implemented with InlineForm, or some other form of auto-form?

**Comment by avoinea** [comment]
@andreiggr Some unit tests are failing. Also please update changelog.

**Comment by andreiggr** [comment]
> Could we have SendEmailInput implemented with InlineForm, or some other form of auto-form?

Thanks for the tip. I replaced the modals with ModalForms from volto.

**Comment by andreiggr** [comment]
> @andreiggr Some unit tests are failing. Also please update changelog.

Hi. Yes. I'm doing changes on the interface and haven't updated the tests yet. Will do.

**Comment by andreiggr** [comment]
https://user-images.githubusercontent.com/44702393/188179908-5a666177-f4e3-4789-a103-9ab8825faa17.mp4

**Review by avoinea — APPROVED** [review]

**Pull request merged**
