### PR TITLE
Revisit login/logout process, better catching of edge cases (unauthor…

### PR DESCRIPTION
**Pull request by sneridagh**
…ized while developing)

### CODE REVIEW

**Review by ericof — APPROVED** [review]

**Review by ichim-david — APPROVED** [review]

**Comment by ichim-david** [comment]
@plone/volto-team if you want to test this fix and see the before and after here is a simple testcase that is fixed by this pull request.
1. Login and create a private document
2. Logout on that private document
3. You get unauthorised page with link to login, click it
4. Login and you will see before that you are not redirected to the page that requested the login you are left on the login page.
Before you had to click on the logo to go to the homepage and you would see that you were indeed logged in.
Now as soon as you high login you are redirected properly.

It's not very obvious what this pull request fixed, it might fix something else but this is what problem I had before and this pull request fixes this issue for me.

@stevepiercy if you want to add something to the  docs it's all yours :)

**Comment by stevepiercy** [comment]
We have nothing relevant about the logout user experience in the Volto docs: https://6.docs.plone.org/search.html?q=logout&doc_section=volto.

That said, it's yet another reminder that I need to sit down with someone knowledgable to show me how to run Cypress, record screenshots and videos, and store those files in documentation's `_static` directory. I think the student who was looking into this at the Axolotl Sprint has moved on to other things. It's sad that we have only a minimal user manual for Volto in Plone 6 documentation and none for Classic UI.

**Comment by sneridagh** [comment]
@stevepiercy yeah, it's nothing nowhere to be found. "default" login/logout experience is just "given for granted", and it's not specified anywhere, same for the behavior that:

- You can login from anywhere content object, then you return to the same point
- You can logout, you stay in the content object you were located.

I would like having such an asset as a "user guide", we can take a look together at the outcome of what the student left, or maybe plot a plan for moving on from here. Maybe next Volto Team meeting? I think it's important enough to make a plan. Even move it as a PLIP? Let's visibilize it and show that we lack these important documentation part.

Btw, merging this one now, if you don't mind!

**Comment by stevepiercy** [comment]
Yes, please merge.

I never saw anything from the student. I'll make a PLIP, as it pertains to both UIs.

**Pull request merged**
