### PR TITLE
Use proper heading tag (depending on the headline) in default listing template

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by erral** [comment]
https://github.com/plone/volto/blob/master/src/components/manage/Blocks/Listing/schema.js#L35

https://github.com/plone/volto/blob/master/src/components/manage/Blocks/Listing/ListingBody.jsx#L48

**Review by stevepiercy — APPROVED** [review]

**Review by davisagli — COMMENTED** [review]
Semantically, should it even be a heading? It is just an item in a list, not part of the document structure.

**Comment by ionlizarazu** [comment]
> Semantically, should it even be a heading? It is just an item in a list, not part of the document structure.

Even the element should be inside an `<article>` tag for good a11y terms

**Comment by sneridagh** [comment]
The classical problem with headings and a CMS. I'd say that putting it in place a "smart" component won't solve the problem,  we could have edge cases out there. Thinking about it I'd say I lean forward to what @davisagli said. It's a list of elements, which are not part of the doc structure, so they shouldn't be a heading. We can solve it using just classnames for styling.

https://www.a11yproject.com/posts/how-to-accessible-heading-structure/#headings-and-aria%2C-some-discussion

Although it seems sensible indeed that we use the article tag:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article

it also needs a h* ... so we are in the same place as before... 

TBH, I'm kind of torn in this one.

**Review by erral — APPROVED** [review]

**Comment by davisagli** [comment]
There are failing tests

**Comment by sneridagh** [comment]
Next will be green.

**Review by davisagli — APPROVED** [review]

**Pull request merged**
