### PR TITLE
Refactored Display.jsx.

### PR DESCRIPTION
**Pull request by FreakForever**
Refactored Display.jsx from class-based component to functional-based component.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@FreakForever [one of the CI checks failed](https://github.com/plone/volto/actions/runs/10123002990/attempts/1?pr=6204). I [restarted it](https://github.com/plone/volto/actions/runs/10123002990?pr=6204), as it could be a flaky test. What results did you get from running acceptance tests locally, as described in  [Code quality](https://6.docs.plone.org/volto/contributing/index.html#code-quality)?

**Comment by stevepiercy** [comment]
It looks like this may be a duplicate of #5066. @FreakForever please read Item 2 [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).

The last remaining CI check passed.

@plone/volto-team this PR is ready for review, if #5066 does not get merged first.

**Comment by stevepiercy** [comment]
@FreakForever please read [Expectations of first-time contributors](https://6.docs.plone.org/contributing/first-time.html#expectations-of-first-time-contributors), especially the warning.

We are all volunteers with limited time, and this issue is very low priority.

If this is for a class assignment, then please have your instructor contact me directly. It is unfair to you and volunteers for an instructor to raise unrealistic expectations or make demands.

**Comment by FreakForever** [comment]
Sorry for the query, I just wanted to know out of curiosity as it is my
first open source contribution.

Thanks & Regards

**Comment by davisagli** [comment]
Closing as a duplicate of #5066. Thanks for your contribution.

**Pull request closed without merging**
