### PR TITLE
Updated deprecated moment.js code

### PR DESCRIPTION
**Pull request by avimishra18**
See #1809

### CODE REVIEW

**Comment by avimishra18** [comment]
@stevepiercy wanted to ask: 
1. Which CHANGELOG.md file should I update if any? 
1. How to keep a track of which branch indicates which version of `volto`, `scripts` & `generator-volto`?

**Comment by stevepiercy** [comment]
> 1. Which CHANGELOG.md file should I update if any?

https://github.com/plone/volto/blob/master/CHANGELOG.md

> 2. How to keep a track of which branch indicates which version of `volto`, `scripts` & `generator-volto`?

I don't understand the question. Perhaps a maintainer can answer, or you can elaborate?

**Comment by avimishra18** [comment]
```
stevepiercy: I don't understand the question. Perhaps a maintainer can answer, or you can elaborate?
```
My question was which version of Volto does HEAD of master branch corresponds to, I am guessing it is `15.0.0 (unreleased)`.

So, for this PR, I should update the CHANGELOG.md file under the [15.0.0 (unreleased)#bugfix](https://github.com/plone/volto/blob/master/CHANGELOG.md#bugfix) section?

**Comment by nileshgulia1** [comment]
@avimishra18 Yes, the changes needs to go in unreleased versions, ofc :)

**Comment by avimishra18** [comment]
@stevepiercy @nileshgulia1 updated now. Please, review.

**Review by stevepiercy — APPROVED** [review]
This PR also requires review from a maintainer.

**Pull request closed without merging**
