### PR TITLE
Lodash optimization 

### LINKED ISSUE #5672: Lodash full is loading due to dependency from plone/registry
I believe that plone registry isn't using the webpack mechanism to use the tree shaked version of lodash.
https://github.com/plone/volto/blob/main/packages/registry/package.json#L74

running pnpm analyze shows this client bundle:
bundle-analyze-lodash

Checking the bundle stats.json through https://statoscope.tech gave us this reason for the lodash full loading:
lodash

Lodash imports should be optimized so that we don't raise client.js bundle which is served by all Volto websites

### PR DESCRIPTION
**Pull request by ravjot07**
Fixes #5672 
**Replace full Lodash imports with specific module imports.**

### CODE REVIEW

**Comment by sneridagh** [comment]
@ravjot07 @ichim-david we should fix the registry package, who seems to be the offender, probably the build there has to take this into account... I can take a look there.

@ravjot07 the situation in Volto itself was ok, and the webpack config was already taking care that all was ok. Take a look at 17.x.x brach to assess it. There @plone/registry was inside the core code, and I guess that mattered.

**Comment by ravjot07** [comment]
> @ravjot07 @ichim-david we should fix the registry package, who seems to be the offender, probably the build there has to take this into account... I can take a look there.
> 
> @ravjot07 the situation in Volto itself was ok, and the webpack config was already taking care that all was ok. Take a look at 17.x.x brach to assess it. There @plone/registry was inside the core code, and I guess that mattered.

sure @ichim-david @sneridagh

**Comment by ichim-david** [comment]
@ravjot07 I'm sorry for all of your work but unfortunately, it was in vain because the fix lay again in the package with the problem that I've mentioned in the issue and not everywhere lodash was used.

Next time before committing to work on something ensure that you know the codebase well enough and that the task is meant for beginners or not and the issue is marked with needs help or not.

Please read again all of the information given in our first-time contribution documentation
https://6.docs.plone.org/contributing/first-time.html especially the warning and the section https://6.docs.plone.org/contributing/first-time.html#things-not-to-do

**Comment by ravjot07** [comment]
> @ravjot07 I'm sorry for all of your work but unfortunately, it was in vain because the fix lay again in the package with the problem that I've mentioned in the issue and not everywhere lodash was used.
> 
> Next time before committing to work on something ensure that you know the codebase well enough and that the task is meant for beginners or not and the issue is marked with needs help or not.
> 
> Please read again all of the information given in our first-time contribution documentation https://6.docs.plone.org/contributing/first-time.html especially the warning, the section https://6.docs.plone.org/contributing/first-time.html#things-not-to-do and https://6.docs.plone.org/contributing/first-time.html#work-with-github-issues

@ichim-david Ok david Can you assign me some issue that i can work. It will be really helpful for me.....

**Comment by stevepiercy** [comment]
@ravjot07 Don't say "Ok" when you do not read or follow advice that would answer your next question https://6.docs.plone.org/contributing/first-time.html#things-not-to-do. It wastes your time and ours.

**Pull request closed without merging**
