### PR TITLE
Add hindi translation in Volto

### LINKED ISSUE #6015: Add Hindi translation in Volto
I have been working on Volto for 5 years now. I should add my mother tongue to Volto.

### PR DESCRIPTION
**Pull request by iFlameing**
Fix #6015

### CODE REVIEW

**Comment by sneridagh** [comment]
@iFlameing needs a final i18n script run.

**Comment by davisagli** [comment]
@sneridagh @stevepiercy we should probably list the supported languages somewhere in documentation

**Review by davisagli — APPROVED** [review]
Unfortunately I can't review the translation itself. Please invite other Hindi speakers to check it if you want.

**Comment by stevepiercy** [comment]
> @sneridagh @stevepiercy we should probably list the supported languages somewhere in documentation

Agreed, but what would it look like? Would it be just a list of supported languages, links to the repos where you can see which languages are supported, or a combination of both?

[Classic UI](https://github.com/collective/plone.app.locales/tree/master/plone/app/locales/locales) and [Volto](https://github.com/plone/volto/tree/main/packages/volto/locales) have different supported languages, 69 versus 14 plus 1 from this PR, so we need to make that distinction.

I'd suggest adding content to [Internationalization and Localization](https://6.docs.plone.org/i18n-l10n/index.html) in the main documentation.

We should also add a step to each process for adding a new language, where the contributor adds it to the listing in the main documentation, too.

**Review by nileshgulia1 — APPROVED** [review]
@iFlameing Nice!

**Comment by iFlameing** [comment]
@stevepiercy @iRohitSingh Will work on the Hindi translation in Plone core during the sprint.

**Comment by stevepiercy** [comment]
> @stevepiercy @iRohitSingh Will work on the Hindi translation in Plone core during the sprint.

That would be awesome. We have documentation for how to add languages for [Plone Classic UI](https://6.docs.plone.org/i18n-l10n/index.html), but I am not certain if it is correct. Please feel free to submit PRs for that as well.

**Comment by erral** [comment]
> > @stevepiercy @iRohitSingh Will work on the Hindi translation in Plone core during the sprint.
> 
> That would be awesome. We have documentation for how to add languages for [Plone Classic UI](https://6.docs.plone.org/i18n-l10n/index.html), but I am not certain if it is correct. Please feel free to submit PRs for that as well.

That docs are OK. I reviewed them some time ago and they are still OK.

I am waiting for the final approval from Weblate to have a Free plan there and include that documentation too.

Anyway, Weblate can be used also to contribute Classic UI translation right now. Not for Volto (there are still some issues).

**Comment by sneridagh** [comment]
@iFlameing we need to update too: https://github.com/plone/volto/blob/main/packages/volto/src/constants/Languages.js#L7

Thanks!

**Comment by stevepiercy** [comment]
> @iFlameing we need to update too: https://github.com/plone/volto/blob/main/packages/volto/src/constants/Languages.js#L7

And that step needs to be added to the overview in https://6.docs.plone.org/volto/development/i18n.html

**Comment by stevepiercy** [comment]
> > @iFlameing we need to update too: https://github.com/plone/volto/blob/main/packages/volto/src/constants/Languages.js#L7
> 
> And that step needs to be added to the overview in https://6.docs.plone.org/volto/development/i18n.html

Done in https://github.com/plone/volto/pull/6016/commits/f76797982cf36f475484b69c0565492750e52149. I also cleaned up grammar and syntax in the docs.

**Comment by stevepiercy** [comment]
> @sneridagh @stevepiercy we should probably list the supported languages somewhere in documentation

See PR https://github.com/plone/documentation/pull/1664

**Comment by iFlameing** [comment]
@sneridagh done from my side.

**Review by davisagli — COMMENTED** [review]
@iFlameing There is a failing unit test which needs to be updated with a new snapshot that includes Hindi in the list.

**Comment by stevepiercy** [comment]
> @iFlameing There is a failing unit test which needs to be updated with a new snapshot that includes Hindi in the list.

@davisagli help! How to do that? It ain't in the Volto docs.

**Comment by davisagli** [comment]
@stevepiercy There should be a prompt to update the snapshots when the tests are run as documented here: https://6.docs.plone.org/volto/contributing/testing.html#run-jest-tests-on-volto-core

**Comment by stevepiercy** [comment]
> @stevepiercy There should be a prompt to update the snapshots when the tests are run as documented here: https://6.docs.plone.org/volto/contributing/testing.html#run-jest-tests-on-volto-core

Done in [db23888](https://github.com/plone/volto/pull/6016/commits/db23888c25377bc42973900ea9bac3d6c0373563). Thank you!

**Comment by sneridagh** [comment]
> I also noticed that https://6.docs.plone.org/volto/development/i18n.html#broad-overview mentions `.json` files, and see that they are excluded from the repo in `.gitignore`. It's not clear what a developer should do with them or if there is some automation that takes care of it for the developer. Can someone enlighten me so I can update the docs accordingly?

If they are mentioned somewhere, it should be only as a "how does it work". Those JSON files are the `.mo` equivalent in gettext, you should forget they are there.

**Pull request merged**
