### PR TITLE
Update to Plone 6.0.11

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by sneridagh** [comment]
@stevepiercy Netlify builds are failing, any idea why?

```
11:36:05 AM: Exception occurred:
11:36:05 AM:   File "/opt/buildhome/python3.8/lib/python3.8/site-packages/myst_parser/mdit_to_docutils/base.py", line 1925, in html_meta_to_nodes
11:36:05 AM:     meta_node = nodes.meta(content)
11:36:05 AM: AttributeError: module 'docutils.nodes' has no attribute 'meta'
11:36:05 AM: The full traceback has been saved in /tmp/sphinx-err-b4w1zslw.log, if you want to report the issue to the developers.
11:36:05 AM: Please also report this if it was a user error, so that a better error message can be provided next time.
```

**Comment by stevepiercy** [comment]
It's been failing since 2024-04-23:

https://app.netlify.com/sites/volto/deploys/6628a245b1491900090e2c6c

Last known good build, earlier on the same day:

https://app.netlify.com/sites/volto/deploys/66277280ad5f1a0008a4eb52

I think that `myst_parser` had a new release that same day:

https://github.com/executablebooks/MyST-Parser/releases/tag/v3.0.0

I have v0.18.1 installed, but v1.0.0 should work with the versions of the themes and Sphinx we use.

**Comment by stevepiercy** [comment]
Commit pushed. Let's see if that fixes Netlify.

**Comment by stevepiercy** [comment]
Whoopsie, no change in docs, so I had to manually restart it.

**Comment by stevepiercy** [comment]
Meanwhile the README linkcheck fails because https://www.fz-juelich.de/de returns a 404. The entire site is 404. Who should we ping?

**Comment by sneridagh** [comment]
@stevepiercy it should be ok soon, we are on it.

**Pull request merged**
