### PR TITLE
Remove docs any doc tree

### PR DESCRIPTION
**Pull request by sneridagh**
Left `cheatsheet.md` and `releases.md` without doctree reference, but linked releases from the upgrade guide.

### CODE REVIEW

**Comment by sneridagh** [comment]
@stevepiercy Not sure where to place releases.md, we could left it and place it in the right place when we do the reorganisation.

**Review by stevepiercy — APPROVED** [review]
Your changes are good.

**Comment by stevepiercy** [comment]
@sneridagh I pushed a few more commits to manage `cheatsheet.md` and `releases.md`, and added a few other improvements. Would you please review my changes?

**Comment by sneridagh** [comment]
@stevepiercy looks good to me! Thanks!

**Comment by stevepiercy** [comment]
I just fixed a merge conflict in the changelog, so I won't wait for another build that will pass. Merging!

**Pull request merged**
