### PR TITLE
add outline for user-manual for Volto the Plone 6 frontend

### PR DESCRIPTION
**Pull request by MAX-786**
#3827 
This is the proposed structure or outline of first page for user-manual docs for volto frontend. It is only a start to have something to look at and discuss. Feedback welcome.

Proposed:

https://user-images.githubusercontent.com/99530996/205509532-ec2cbf1c-db66-49e0-b3f5-27fc5ddced82.mp4

This PR has been re-opened at #4069. Sorry for the inconvenience.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@MAX-786 @polyester would you both try to straighten out the email configuration on GitHub? @mister-roboto warnings are annoying.

**Comment by stevepiercy** [comment]
Also @MAX-786 please let me know when this is ready to review. Thank you!

**Comment by MAX-786** [comment]
> @MAX-786 @polyester would you both try to straighten out the email configuration on GitHub? @mister-roboto warnings are annoying.

Still, @mister-roboto is showing warnings 🥲. Is there any other way or I am thinking of creating a new branch and making a separate pull request with it? this must be annoying for you guys too, sorry for that.

**Comment by stevepiercy** [comment]
> I am thinking of creating a new branch and making a separate pull request with it

Please do _not_ do that. That makes more work for reviewers and it does not solve the issue with @mister-roboto.

In the future, please do not close PRs where there is a long comment and review history. Now I have to look in two different places to reconcile changes for this PR. I would have much preferred that you reopened the PR you closed and continued work on it. There are a few times when it is better to close a PR and open new, such as a bad merge or rebase where the commit history is a nightmare, but that rarely occurs.

As far as @mister-roboto nagifications, please check that the email you use on GitHub matches the one that you submitted in your signed Contributor Agreement that you sent to agreements@plone.org. If there is a mismatch, then please send an email with the correction to agreements@plone.org, and someone will make the correction internally.

@polyester would you please verify that there is no mismatch between what @MAX-786 submitted and the @mister-roboto configuration?

Thank you, both!

**Comment by polyester** [comment]
The Contributor Agreement is based on github username, and has no concept of email. The PR probably needs a close/reopen, trying that now.

**Comment by polyester** [comment]
So, that didn't help. I will try to find later where the mr.roboto is configured, I have no idea to be honest.

**Comment by MAX-786** [comment]
> > I am thinking of creating a new branch and making a separate pull request with it
> 
> Please do _not_ do that. That makes more work for reviewers and it does not solve the issue with @mister-roboto.
> 
> In the future, please do not close PRs where there is a long comment and review history. Now I have to look in two different places to reconcile changes for this PR. I would have much preferred that you reopened the PR you closed and continued work on it. There are a few times when it is better to close a PR and open new, such as a bad merge or rebase where the commit history is a nightmare, but that rarely occurs.
> 
> As far as @mister-roboto nagifications, please check that the email you use on GitHub matches the one that you submitted in your signed Contributor Agreement that you sent to [agreements@plone.org](mailto:agreements@plone.org). If there is a mismatch, then please send an email with the correction to [agreements@plone.org](mailto:agreements@plone.org), and someone will make the correction internally.
> 
> @polyester would you please verify that there is no mismatch between what @MAX-786 submitted and the @mister-roboto configuration?
> 
> Thank you, both!

Thanks, Steve, 😅I'll keep that in mind next time.

**Comment by MAX-786** [comment]
Sure I'll add that right now,
Also, as `mister-roboto` is not able to recognize my username, though my other [PR](https://github.com/plone/volto/pull/4057) is successfully verified so, I figured that the problem is, for agreement verification of this PR `mister-roboto` is considering [author of this PR for verification](https://github.com/plone/volto/pull/4035/commits/fd251b1941193d0d82f57ac1853f870ef6e5f361) which was my locally configured user.name = 'max_786' 🥲( which I have corrected now ) . I have **googled** it but found nothing.
Thanks, @stevepiercy for your responses but I don't know how this can be fixed 😣.

**Comment by davisagli** [comment]
@MAX-786 I think mr.roboto's check is based on emails rather than usernames. The email in the git commit message needs to match the email on your github account.

**Comment by stevepiercy** [comment]
> @MAX-786 May I propose that you make a new PR? 

Yes, that is a good reason to do so, but let's leave this PR open until we can fix this @mister-roboto issue.

**Comment by MAX-786** [comment]
This PR has been re-opened at #4069. Sorry for the inconvenience.

**Comment by stevepiercy** [comment]
Closed by #4069

**Pull request closed without merging**
