### PR TITLE
Update makefile with Vale and fix linkcheckbroken

### PR DESCRIPTION
**Pull request by stevepiercy**
- Use Vale for spell, grammar, and style checking
- Fix linkcheckbroken to return the correct exit code for broken links

### CODE REVIEW

**Comment by stevepiercy** [comment]
Note that this is a one-time (I hope) fix for all broken links, now that linkcheckbroken once again returns the correct exit code. I fixed a lot of broken links in `CHANGELOG.md`.

**Comment by stevepiercy** [comment]
Hello! Would someone review this PR? It's ready to go and holding up Plone 6 Documentation deployment.

**Comment by stevepiercy** [comment]
🦗 🦗 🦗

**Comment by ksuess** [comment]
The `ifconfig` directive in release notes seems to be ignored.
Running `make docs-linkcheckbroken` raises: 
```
foo/docs/source/release-notes/index.md:11: CRITICAL: Directive "include": error reading file: foo/volto/submodules/volto/CHANGELOG.md
[Errno 2] No such file or directory: 'foo/volto/submodules/volto/CHANGELOG.md'.
```
The code seems to be correct, but I'm not familiar enough to this extension.

**Comment by ksuess** [comment]
And there are still warnings for youtube links:
```
(getting-started/others: line   57) redirect  https://www.youtube.com/playlist?list=PLGN9BI-OAQkQDLQinBwdEXpebDTQCwdGi - with Found to https://consent.youtube.com/ml?continue=https://www.youtube.com/playlist?list%3DPLGN9BI-OAQkQDLQinBwdEXpebDTQCwdGi%26cbrd%3D1&gl=CH&hl=de&pc=yt&src=1
(getting-started/others: line   63) redirect  https://www.youtube.com/playlist?list=PLGN9BI-OAQkQmEqf6O8jeyoFY1b2hD1uL - with Found to https://consent.youtube.com/ml?continue=https://www.youtube.com/playlist?list%3DPLGN9BI-OAQkQmEqf6O8jeyoFY1b2hD1uL%26cbrd%3D1&gl=CH&hl=de&pc=yt&src=1
(getting-started/others: line   58) redirect  https://www.youtube.com/playlist?list=PLGN9BI-OAQkTJPayNdKIZ8lLDm5RVOLV3 - with Found to https://consent.youtube.com/ml?continue=https://www.youtube.com/playlist?list%3DPLGN9BI-OAQkTJPayNdKIZ8lLDm5RVOLV3%26cbrd%3D1&gl=CH&hl=de&pc=yt&src=1
(getting-started/others: line   41) redirect  https://www.youtube.com/playlist?list=PLGN9BI-OAQkQxqQcCZeJefMC8XlA_qv3Z - with Found to https://consent.youtube.com/ml?continue=https://www.youtube.com/playlist?list%3DPLGN9BI-OAQkQxqQcCZeJefMC8XlA_qv3Z%26cbrd%3D1&gl=CH&hl=de&pc=yt&src=1
```

**Comment by ksuess** [comment]
`volto/docs/source/cheatsheet.md:17: WARNING: unknown document: plone:contributing/myst-reference`will be correct with PR in plone/documentation.

**Comment by stevepiercy** [comment]
> The `ifconfig` directive in release notes seems to be ignored. Running `make docs-linkcheckbroken` raises:
> 
> ```
> foo/docs/source/release-notes/index.md:11: CRITICAL: Directive "include": error reading file: foo/volto/submodules/volto/CHANGELOG.md
> [Errno 2] No such file or directory: 'foo/volto/submodules/volto/CHANGELOG.md'.
> ```
> 
> The code seems to be correct, but I'm not familiar enough to this extension.

This is an unfortunate hack because there is no way to have ifconfig resolve a path across both a submodule and its parent. The warning may be safely ignored. I considered alternatives, but found nothing that could do this well, unless we copied the CHANGELOG.md to a resolveable location. That also has issues. I resolved to add it to the pile of ignored warnings, such as the .jsx lexer.

**Comment by stevepiercy** [comment]
> And there are still warnings for youtube links:

Looks like a GDPR issue. I don't see redirects in the US.

We could add youtube to the list of ignored links, or just be aware of it. There is [no open issue in Sphinx about GDPR compliance for linkcheck](https://github.com/sphinx-doc/sphinx/issues?q=linkcheck+gdpr).

Alternatively we could embed the YouTube videos with https://github.com/sphinx-contrib/youtube, as suggested by https://github.com/executablebooks/sphinx-book-theme/issues/354#issuecomment-1046319108, which would remove the links.

**Review by ksuess — APPROVED** [review]

**Pull request merged**
