### PR TITLE
Actions storybook test

### PR DESCRIPTION
**Pull request by Tishasoumya-02**
#4460.
Doubt in this test .

### CODE REVIEW

**Comment by tiberiuichim** [comment]
Cool, too bad the Actions component is not reusable

**Review by tiberiuichim — CHANGES_REQUESTED** [review]
It's an Internal component, rename the story to "Actions menu"

**Comment by stevepiercy** [comment]
@Tishasoumya-02 if you update this branch from `main`, many of the failing GitHub workflows should pass, as `actions/upload-artifact@v1` was updated on `main`. I think you have permission, and should see the `Update branch` button.

**Review by davisagli — APPROVED** [review]

**Comment by Tishasoumya-02** [comment]
@davisagli , I realized that the actions storybook test is in the wrong directory right now. Should I open a new PR to correct this or the changes can be reverted?

**Comment by davisagli** [comment]
@Tishasoumya-02 It's probably easiest to fix it in a new PR.

**Comment by wesleybl** [comment]
@Tishasoumya-02 why do we have a `src` folder in the project root? The `packages` folder is usually used.

**Comment by stevepiercy** [comment]
@wesleybl @Tishasoumya-02 [realized it after merging](https://github.com/plone/volto/pull/5049#issuecomment-2298925772), and will put it in https://github.com/plone/volto/tree/main/packages/volto/src/components/manage/Actions in another PR, or you're welcome to assist.

**Pull request merged**
