### PR TITLE
DefaultView (blocks disabled): Show field name as tip on hover of label

### PR DESCRIPTION
**Pull request by ksuess**

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Review by davisagli — COMMENTED** [review]
This might be okay for editors but I don't think it's something I would want to display in a tooltip for anonymous viewers.

**Comment by tiberiuichim** [comment]
@davisagli that view is very rough. If you're exposing end users to it, you either have bigger problems, or they're the type of users that don't mind that info, or they find it useful.

**Comment by davisagli** [comment]
@tiberiuichim I guess you are probably right in most cases.

**Comment by sneridagh** [comment]
I agree that this view is kind of a rough fallback view, ideally an integrator should always provide a better tailored one.

**Pull request merged**
