### PR TITLE
select volto bind address

### PR DESCRIPTION
**Pull request by achimwilde**

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]
Needs Changelog entry

**Review by tisto — CHANGES_REQUESTED** [review]
LGTM. We just need to add a changelog entry to CHANGELOG.md.

**Comment by achimwilde** [comment]
Since there has been a release after forking my branch, how do I correctly insert a changelog entry?

This is how it would look like:
- Added environment parameter `RAZZLE_BIND_ADDRESS` to be able to bind server to localhost or other specific IPs instead of 0.0.0.0 @achimwilde

**Comment by tiberiuichim** [comment]
@achimwilde merge the current master to your branch, add the changelog entry

**Review by tisto — APPROVED** [review]
@achimwilde thanks for your contribution! I will merge and release this as soon as we are out of the current alpha phase (hopefully in the next days).

**Comment by tisto** [comment]
@achimwilde could you imagine to add a few lines to our Volto docs listing the available RAZZLE_ env vars: https://docs.voltocms.com/configuration/environmentvariables/

**Pull request merged**
