### PR TITLE
Fix `/links-to-item` should be a protected route (#5667)

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Review by ichim-david — APPROVED** [review]

**Comment by ichim-david** [comment]
@sneridagh there was a missing find import which I've added that was legit issue.
There is still a problem with core block test on plone 5 https://github.com/plone/volto/actions/runs/7622476876/job/20760889293#step:5:430
I've tried to re-run a few times hoping it would eventually wake up to reality but no luck, maybe you know more about this error.
I've accepted the pull request making it easier to merge once that flaky test is dealt with

**Comment by iFlameing** [comment]
@sneridagh Ci is failing because of some hiccups in robot server 
```
Successfully installed PySocks-1.7.1 babel-2.14.0 exceptiongroup-1.2.0 furl-2.1.3 h11-0.14.0 orderedmultidict-1.0.1 outcome-1.3.0.post0 plone.app.robotframework-2.0.0 plone.app.testing-7.0.0 plone.rest-3.0.1 plone.restapi-9.2.0 plone.testing-9.0.1 plone.volto-4.1.0 robotframework-7.0 robotframework-pythonlibcore-4.3.0 robotframework-selenium2library-3.0.0 robotframework-seleniumlibrary-6.2.0 robotframework-seleniumtestability-2.1.0 robotsuite-2.3.2 selenium-4.17.0 sniffio-1.3.0 sortedcontainers-2.4.0 trio-0.24.0 trio-websocket-0.11.1 wrapt-1.16.0 wsproto-1.2.0 zope.testrunner-6.2.1
WARNING: You are using pip version 22.0.4; however, version 23.3.2 is available.
You should consider upgrading via the '/app/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/app/bin/robot-server", line 5, in <module>
    from plone.app.robotframework.server import server
  File "/app/lib/python3.8/site-packages/plone/app/robotframework/__init__.py", line 3, in <module>
    from plone.app.robotframework import patches as _patches
  File "/app/lib/python3.8/site-packages/plone/app/robotframework/patches.py", line 4, in <module>
    from selenium.webdriver.common import utils
  File "/app/lib/python3.8/site-packages/selenium/webdriver/__init__.py", line 29, in <module>
    from .firefox.firefox_profile import FirefoxProfile  # noqa
  File "/app/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 31, in <module>
    from typing_extensions import deprecated
ModuleNotFoundError: No module named 'typing_extensions'
make: *** [Makefile:393: start-test-acceptance-server-5] Error 1
/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3900
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                
                
        ```

**Comment by sneridagh** [comment]
@ichim-david crap, a new dependency got in, and broke the build?

**Comment by ichim-david** [comment]
> @ichim-david crap, a new dependency got in, and broke the build?

@sneridagh nope, your backport for some reason was missing the find import for lodash which I've added
https://github.com/plone/volto/pull/5680/commits/ad8bf76000c2cfddc8c46b6faaec4853b145e529
You can see the error being reported here 
https://github.com/plone/volto/actions/runs/7608992736/job/20719287215#step:5:3334

There might be some missing pins in the plone 5 stack for Plone given that failure that @iFlameing has pasted as there were no extra dependencies added in this backport

**Comment by sneridagh** [comment]
@ichim-david but this PR did not touch anything from the backend, if that error shows now, is that the build is broken (for any new PR, from now on). We will have to check that.

**Comment by sneridagh** [comment]
@ichim-david let's see: https://github.com/plone/volto/pull/5685

**Comment by iFlameing** [comment]
@sneridagh ci is green now.

**Pull request merged**
