### PR TITLE
fixed duplicate items in SelectWidget and ArrayWidget

### PR DESCRIPTION
**Pull request by giuliaghisini**
When items were loaded from a vocabulary, items in select and array widget were duplicated. 
Now it's fixed

### CODE REVIEW

**Comment by tisto** [comment]
@giuliaghisini please add a changelog entry.

**Comment by giuliaghisini** [comment]
> @giuliaghisini please add a changelog entry.

sorry! done

**Comment by tisto** [comment]
@giuliaghisini i18n please :)

**Comment by giuliaghisini** [comment]
> @giuliaghisini i18n please :)

pushed!

**Pull request merged**
