### PR TITLE
Documentation update: Update installation method in documentation to use pnpm for package installation instead of yarn.

### LINKED ISSUE #5556: Consolidate install Volto for development docs
Please update the documentation.

- This section should be replaced: https://6.docs.plone.org/volto/contributing/index.html#install-volto-for-development 
- with a link to: https://6.docs.plone.org/volto/contributing/developing-core.html

By following the first one we just end up with the following error:

image

@stevepiercy 
@sneridagh

_Originally posted by @lorstenoplo in https://github.com/plone/volto/issues/3289#issuecomment-1864207374_

### PR DESCRIPTION
**Pull request by Atharvp01**
- fixes #5556, also using npm for installing pnpm installs latest version of pnpm

### CODE REVIEW

**Comment by Atharvp01** [comment]
I've signed the agreement need a review @stevepiercy

**Comment by stevepiercy** [comment]
@Atharvp01 not at this time. As the [instructions clearly state](https://6.docs.plone.org/contributing/first-time.html#plone-contributors-team):

> New contributors should wait for confirmation that they have been added to this team before creating a pull request to a Plone project.

Once you receive the email adding you to the Contributors Team, then you may request a review from anyone.

However, no one will review your work until you follow [Change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry) and all CI checks pass.

**Comment by sneridagh** [comment]
@Atharvp01 @stevepiercy I'd point to the developing-core.md instead of repeating what's in there. So I rather remove things from the index.

**Comment by stevepiercy** [comment]
@Atharvp01 there is already an open PR https://github.com/plone/volto/pull/5564 that addresses the open issue.

@sneridagh we have some issues that need to be addressed with our developer documentation. See https://github.com/plone/volto/issues/5556 where I document my experience and misfortunes of following our documentation.

**Comment by Atharvp01** [comment]
Okay. Should I close this one then? @stevepiercy

**Comment by stevepiercy** [comment]
Closing, as existing PR is being worked on in #5564.

**Pull request closed without merging**
