### PR TITLE
Update pnpm-lock.yaml

### PR DESCRIPTION
**Pull request by wesleybl**
When I ran `pnpm install` the file was updated

### CODE REVIEW

**Comment by davisagli** [comment]
@sneridagh Hmm, how did this happen?

**Comment by sneridagh** [comment]
@wesleybl I just run it in main and for me it does not change. @stevepiercy also noted that. I changed the `yarnhook` for a custom script that does something more appropiate on git checkouts.

I just run pnpm install in main, and it did not changed anything for me. Make sure you are using the corepack pnpm version (this one uses the pnpm version specified in the package.json file). Remove any other pnpm installation from your machine. Don't know if that is the cause of it but it's quite strange.

**Comment by sneridagh** [comment]
@davisagli did it changes for you if you run it now?

**Comment by sneridagh** [comment]
I read that pnpm install does more things than yarn install used to do. I also saw that for something as the hook on git change is better:

```pnpm install --prefer-offline --frozen-lockfile --no-verify-store-integrity```

See: https://github.com/pnpm/pnpm/issues/6229#issuecomment-1475290177

**Comment by wesleybl** [comment]
I had this problem again, even though I had the same version of pnpm used in the CI. So I followed the steps in the link in @sneridagh ' [comment](https://github.com/plone/volto/pull/5852#issuecomment-1981862800):

```
rm -rf node_modules
pnpm i --frozen-lockfile --no-verify-store-integrity
```

This solved the problem. After doing this, `pnpm install` no longer updates `pnpm-lock.yaml`

**Pull request closed without merging**
