### PR TITLE
added toast notifications for form errors

### PR DESCRIPTION
**Pull request by nzambello**
this is nice for extra required fields in CT in tabs different from the first one.
we also have this need for blocks-enabled CT, where in the sidebar the required field is not visible.

### CODE REVIEW

**Comment by giuliaghisini** [comment]
@tisto @sneridagh, do you think this can be merged in to the master?
We would need it for some of our projects
Thank you!

**Comment by avoinea** [comment]
@nzambello Please run `yarn run prettier:fix`

**Comment by nzambello** [comment]
@avoinea Did it, thank you

**Comment by giuliaghisini** [comment]
@tisto @tiberiuichim

**Comment by nzambello** [comment]
@tisto resolved conflicts

**Review by avoinea — APPROVED** [review]
@nzambello I did some adjustment to display also the required field in toast. And fix console error (invalid value array provided to Toast) 

Please take a look. Otherwise LGTM.

**Comment by avoinea** [comment]
@tisto This is more a completion of #1454 than a conflict, thus I think we can merge it first.

**Comment by tisto** [comment]
@avoinea just to be sure. I will merge this PR (#1589) first and then look at your PR, correct?

**Comment by avoinea** [comment]
@tisto Yes :wink:

**Review by tisto — APPROVED** [review]

**Comment by tisto** [comment]
@nzambello works like a charm! Thanks!

**Pull request merged**
