### PR TITLE
Fix autogenerate text area

### PR DESCRIPTION
**Pull request by sans-byte**
Fix for issue #1775 

----
📚 Documentation preview 📚: https://volto--6117.org.readthedocs.build/

### CODE REVIEW

**Comment by sans-byte** [comment]
Hi, @mister-roboto I have already signed the Agreement.

**Comment by stevepiercy** [comment]
@sans-byte see:

- https://6.docs.plone.org/contributing/first-time.html#plone-contributors-team
- https://6.docs.plone.org/contributing/first-time.html#mr-roboto-on-github

Also item 3 in https://6.docs.plone.org/contributing/first-time.html#things-not-to-do

**Comment by stevepiercy** [comment]
@sans-byte please follow up with agreements@plone.org to see what happened with your Plone Contributor Agreement. Your GitHub email is still not recognized.

**Comment by stevepiercy** [comment]
@sans-byte I'm closing this PR as abandoned because:

- Tests fail
- mr-roboto says you have not signed the PCA

Feel free to reopen after you have resolved both issues.

**Pull request closed without merging**
