### PR TITLE
#2487 changed headline color to black for better contrast

### PR DESCRIPTION
**Pull request by ThomasKindermann**
changed the headline color of the table block to black for better contrast with the background.

issue: #2487

### CODE REVIEW

**Comment by tisto** [comment]
@ThomasKindermann can you provide a screenshot of the black color? Maybe it is possible to use a darker grey. cc @sneridagh

**Comment by ThomasKindermann** [comment]
Screenshot 2021-06-04 at 09 32 23

@tisto @sneridagh

**Comment by sneridagh** [comment]
Yeah, before total black is always preferable use a dark grey, like #333. How @textColor variable works? (I don't remember if it's #333 or other dark grey.

**Review by tisto — APPROVED** [review]
LGTM!

**Comment by ThomasKindermann** [comment]
@sneridagh @tisto #333 works for a11y, 
i think @textcolor is the same as @black: rgba(0, 0, 0, 0.87)
should i change it to #333?

**Comment by tisto** [comment]
@ThomasKindermann then go ahead with textcolor.

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
