### PR TITLE
Fix overflow contents view table

### PR DESCRIPTION
**Pull request by giuliaghisini**
Added horizontal scrollbar if table contents exceed content width.

https://user-images.githubusercontent.com/51911425/128003389-1be228ba-d8da-4ec5-9ce2-8ed55c4622f2.mov

### CODE REVIEW

**Comment by nileshgulia1** [comment]
@giuliaghisini same PR here: https://github.com/plone/volto/pull/1697

**Comment by giuliaghisini** [comment]
> @giuliaghisini same PR here: #1697

oh, see now. 
But.. i think this PR is more complete, because scrollbar will appear only if needed. 
If you add only the 'overflow-x: auto' without handle the table styles, scrollbar will appear even if not needed because of .ui.attached.table styles. 
This PR takes care of this and of table styles.

**Review by nileshgulia1 — APPROVED** [review]
LGTM

**Comment by tiberiuichim** [comment]
:) how do we get that last column pinned?

**Review by nzambello — APPROVED** [review]

**Comment by nzambello** [comment]
> :) how do we get that last column pinned?

I guess we don't have any better option if not something _really_ tricky and hacky, and I wouldn't go for that right now

**Review by tiberiuichim — APPROVED** [review]
(not related to the PR, just a place to vent) That Contents.jsx is one of those big component files that need to be refactored, to allow us to "grow" with new functionality

**Comment by ksuess** [comment]
I do not aggree with this PR. The folder contents view is for information and is being used to select an item for editing. The action 'edit' is already hidden in an '...' menu. So this menu should at least be visible, my opinion.
See this suggestion from last year: https://github.com/plone/volto/pull/1568#issuecomment-639467899 and imagine a beautiful designed version of it.

**Comment by nileshgulia1** [comment]
> (not related to the PR, just a place to vent) That Contents.jsx is one of those big component files that need to be refactored, to allow us to "grow" with new functionality

@tiberiuichim one such example https://github.com/plone/volto/pull/2596

**Comment by sneridagh** [comment]
I kind of agree with @ksuess, although is the kind of thing we were all searching for, it has the drawback that the ... menu is potentially not visible at first sight.

For reference, this is the Quanta mockup:

Screenshot 2021-08-18 at 10 02 37

Albert designed it even without it being always visible, I guess to remove visual clutter. I kind of like Google Drive's approach (it's behind a right click on the element), but agreed that it can be a bit too hidden for the average user.

Also, there's the ongoing agreement that the contents folder should have an app-ish look and feel, not to be constrained by the website "frame" structure. So I lean more towards Katja solution + Quanta additions + app-ish look and feel.

**Comment by sneridagh** [comment]
I wonder if using react-table is sensible here:
https://codesandbox.io/s/react-table-fixed-columns-official-kowzlm5jp7

Using fixed columns seems easy. Then we could have all the filtering options.

**Comment by tiberiuichim** [comment]
+1 on adding react-table as a dependency to Volto

**Comment by ksuess** [comment]
- +1 for fixing column 'title' and column 'actions' ('react-table' seems to be an elegant implementation for fixing columns)
- +1 for showing an actions icon like it is done now (not a right click menu like in Google Drive. IMHO it is not obvious enough to be understood by rarely working users)

**Comment by tiberiuichim** [comment]
@plone/volto-team Let's merge this, if possible.

**Comment by sneridagh** [comment]
Agreed to merge unless we have a better approach based on the comments above in:

https://github.com/plone/volto/issues/2991

**Pull request merged**
