### PR TITLE
Improve form validation

### PR DESCRIPTION
**Pull request by giuliaghisini**
In FormValidation testing of required richtext field and realted fields failed because they always had a value, an empty value. 
If field is richtext and it is empty, draftjs always stores some html empty content.
If field is related (like related items or something else) the empty field correspond with an empty array. 

Added test for required fields for these two types of fields.

### CODE REVIEW

**Review by avoinea — APPROVED** [review]

**Review by sneridagh — APPROVED** [review]
Lgtm

**Comment by tisto** [comment]
@plone/volto-team can we start using the "24 status: ready" label for PRs that have at least one positive review and no conflicts or CI failures? This makes it easier for me to spot the low hanging fruits for releases.

**Review by tiberiuichim — APPROVED** [review]

**Comment by tisto** [comment]
@giuliaghisini no clue why the dexterity-controlpanel-schema.js  Cypress test fails. Maybe @avoinea can help here. I am happy to merge and release this PR once the CI is happy.

**Comment by sneridagh** [comment]
It seems that the test pass, but an error is thrown and Cypress captured it... strange that it only failed in one of the builds...

**Comment by giuliaghisini** [comment]
> It seems that the test pass, but an error is thrown and Cypress captured it... strange that it only failed in one of the builds...

probably the problem is in dexterity-controlpanel-schema.js  test

**Comment by giuliaghisini** [comment]
@sneridagh @tisto @tiberiuichim it's ready, are you planning to merge it in master?

**Review by avoinea — APPROVED** [review]

**Comment by sneridagh** [comment]
> Cannot read property 'type' of undefined

in the Cypress test for the DX control panel :/

**Comment by giuliaghisini** [comment]
@sneridagh now it's green

**Pull request merged**
