### PR TITLE
Upgrade Cypress to 13.13.2

### PR DESCRIPTION
**Pull request by wesleybl**
Try to reduce the number of intermittent errors.

### CODE REVIEW

**Comment by ichim-david** [comment]
@wesleybl did you notice any improvement from 13.6?

**Review by stevepiercy — APPROVED** [review]
CI passes now on the first run. Yay! I support saving electricity and time from rerunning failed CI.

**Comment by ichim-david** [comment]
@wesleybl you need to modify also in apps/plone
https://github.com/search?q=repo%3Aplone%2Fvolto%20%2213.6.6%22&type=code
If you look at pnpm-lock.yaml we load still also 13.6.6 due to having this version in the monorepo packages.

**Comment by stevepiercy** [comment]
> @ichim-david I'm seeing the `WebSocket connection closed` error. See:
> 
> https://github.com/plone/volto/actions/runs/10267265488/job/28407419677?pr=4381#step:4:570

I thought you meant this PR, but your link is for a different PR, and now I understand.

FTR, I have also seen numerous similar errors. This was fixed in Cypres 13.13.1. https://docs.cypress.io/guides/references/changelog#13-13-1.

Merging.

**Comment by ichim-david** [comment]
@stevepiercy I wish you would of waited, I have given a feedback that we needed to modify further to truly clean up the use of cypress 13.6.6

**Comment by ichim-david** [comment]
@stevepiercy add another pull request to get rid of the cypress 13.6.6 also from apps/plone so that we truly cleanup the version with problems

**Comment by stevepiercy** [comment]
Sorry, PR incoming.

**Pull request merged**
