### PR TITLE
No listing results

### PR DESCRIPTION
**Pull request by giuliaghisini**
Removed message for 'no results found' in view component of ListingBody for Listing block. 
On the public site it's not always nice to see the message 'no results found'.

### CODE REVIEW

**Comment by sneridagh** [comment]
Merged, in a recent talk with Albert, he said that it's confusing to have the message even in edit, since all the blocks editor seems so WYSIWYG, and that messages are not in the final result.

We will get to that later.

**Comment by sneridagh** [comment]
@giuliaghisini I just released 5.2.0. BTW, I removed the `Breaking` label. The idea is that every time we introduce  breaking thing, we should release a major version. However, that applies to "I introduced something that will hard break existing projects", like in they won't start. For visual and UI changes... I'm a bit reluctant of marking them as breaking, since that will happen quite often... 

Maybe we need to come up with a definition of "breaking". What do you think?
/cc @tisto @pnicolli @tiberiuichim @avoinea @nzambello

**Comment by nzambello** [comment]
@sneridagh I agree with your definition.
This was important but not breaking.
In fact we released a minor, not a major (following semver).

Breaking should be for something which won't make the app to start or to be working (or rendered) well.

If there is something we would like to make in evidence in the changelog, we could arrange like a label before the entry. 🤔

**Comment by sneridagh** [comment]
@nzambello I also thought about the new entry too. Something like a watchout! there's a visual change from this one, even if there's a small one.

**Comment by nzambello** [comment]
Yep, exactly.
It's markdown so it's formattable.

**Pull request merged**
