### PR TITLE
Make the Site Setup control panel responsive for small screen devices

### PR DESCRIPTION
**Pull request by lord2anil**
Before 
https://user-images.githubusercontent.com/97228857/223750492-84f3e344-1fc3-478e-b910-44ec4984ec7b.mp4

After

https://user-images.githubusercontent.com/97228857/223750211-9d8b4c6b-7532-4e93-a0e4-500945739913.mp4

### CODE REVIEW

**Review by avoinea — APPROVED** [review]

**Comment by stevepiercy** [comment]
@lord2anil would you please take a look at the failing builds, and attempt to resolve the broken tests? All tests need to pass before it can be merged.

**Review by stevepiercy — APPROVED** [review]
I can't believe it is that simple for such a good and necessary improvement. Thank you!

**Comment by ksuess** [comment]
> @lord2anil would you please take a look at the failing builds, and attempt to resolve the broken tests? All tests need to pass before it can be merged.

To update snapshots, please run "yarn test" and select all, then type "u" for "update snapshots".

**Comment by lord2anil** [comment]
done

**Pull request merged**
