### PR TITLE
Make dynamic/live teaser without additional requests

### PR DESCRIPTION
**Pull request by pbauer**
PLIP: https://github.com/plone/volto/issues/6023
Depends on PR for plone.restapi: https://github.com/plone/plone.restapi/pull/1788

Replaces #4790

### CODE REVIEW

**Comment by sneridagh** [comment]
@pbauer I pin the p.restapi version to 9.7.0, however, it's still failing in a variety of places, some unrelated to the change :( I can take a look during the sprint.

**Comment by sneridagh** [comment]
@davisagli @pbauer I've fixed the tests but one, the teaser itself. 
Now the docker image gets the right p.restapi version.
I tried to fix it, but I realised that we added the behavior that by default, when the teaser is saved for the first time, the override check is marked (even if you haven't marked it). Is that intentional? Who sets it? the backend? I cannot see code for that in the frontend. Should we set a default in the frontend block data?

@pbauer do you plan to continue working on this PR? I have other places to take care of, it would be great.

**Comment by pbauer** [comment]
By default it should be off. I'm back next week and can have a look.

**Comment by sneridagh** [comment]
Ok, I see it now: https://github.com/plone/plone.restapi/pull/1788/files#diff-1d97712ee7f4214036de21d1867ecf54f50381365e1efccdb84bfc5ea4df9c37R217

I think I can take care of it

**Comment by sneridagh** [comment]
@pbauer @davisagli I think now it's good to go.

@plone/volto-team Can I have a quick review of one of you?

**Comment by tisto** [comment]
@sneridagh I will have a look. I'd like to carefully review this PR and I wouldn't want to rush through things. Do I need to checkout the latest plone.restapi release for this PR or is this taken care of already?

**Comment by sneridagh** [comment]
@tisto already taken care, if you start the docker container:

`make start-backend-docker`

then start the frontend, `pnpm start` in this PR you'll have it ready to test.

**Comment by tisto** [comment]
I get an error when using this branch:

Welcome-to-Plone-6- (5)

Need to double check my node version...

**Comment by tisto** [comment]
Fixed it by removing node_modules.

@sneridagh I tested the following:

- create teaser from existing content object, update title/description/image on target, reflected on teaser -> works
- create teaser from existing content object, choose "override source content", updated title/description/image on target, no change on teaser -> works
- push "reload content" on existing teaser, reloads content from target -> works
- uncheck "override source content", target content is used again -> works

So all good from my side. However, I noticed a wording inconsistency:

Edit-Plone-Site (5)

We agreed on "target", right? Then we should use "target" and not "source" in the checkbox label and description.

**Review by tisto — APPROVED** [review]
Apart from my question regarding the labels I am ok with merging this PR. PLIP review: https://github.com/plone/volto/issues/6023#issuecomment-2170120741

**Comment by davisagli** [comment]
> we added the behavior that by default, when the teaser is saved for the first time, the override check is marked (even if you haven't marked it). Is that intentional? Who sets it? the backend? I cannot see code for that in the frontend. Should we set a default in the frontend block data?

@sneridagh The serializer in the backend adds `overwrite: true` if overwrite is not present in the block data. This is to support blocks created from before we added this feature, and make sure they don't suddenly become dynamic. The frontend must take care of explicitly setting `overwrite: false` for new blocks if we want dynamic teasers to be the default for new blocks.

**Comment by sneridagh** [comment]
@davisagli yeah, I understood the intention while working on it this morning. I added the default in the block's schema, now works as intended.

@tisto I'll take a look tomorrow about the literals.

It also needs a breaking notice in the changelog, since the UI and default behavior have changed.

**Comment by davisagli** [comment]
@sneridagh I wouldn't call it breaking. It's a new feature, and works differently for new blocks, but it doesn't change the behavior for existing content.

**Comment by tisto** [comment]
@davisagli This is a feature that you can not ship to a client and their editors without notice up front. Therefore we should call it "breaking" IMO.

**Comment by davisagli** [comment]
@tisto I thought mentioning it as a new feature in a major release of Volto counts as giving notice, but I agree it's close to the line between feature and breaking in semver terms. It would make sense to mention it in the upgrade guide.

**Comment by tisto** [comment]
@davisagli I agree that this PLIP is in a certain "grey area". However, we are changing the default behavior of a block and the UI. For editors this change is huge. We do not just add a new feature. This would be the case if we had added a new check that says "live teaser".  We decided against this. Therefore I would vote for calling it a "breaking change" and mention it in the upgrade guide.

**Comment by davisagli** [comment]
@tisto Yeah, you convinced me.

**Review by nileshgulia1 — APPROVED** [review]

**Comment by tisto** [comment]
@nileshgulia1 thanks for your review. Could you imagine creating a formal PLIP review, similar to what I did on the PLIP?

https://github.com/plone/volto/issues/6023

**Comment by stevepiercy** [comment]
I have some concerns about the checkbox label and its help text. Please add to the discussion in the PLIP at https://github.com/plone/volto/issues/6023#issuecomment-2170944325.

**Review by stevepiercy — CHANGES_REQUESTED** [review]
See https://github.com/plone/volto/issues/6023#issuecomment-2170944325

**Comment by stevepiercy** [comment]
Added docs in [a8a7dbb](https://github.com/plone/volto/pull/6024/commits/a8a7dbbf93a6f767aa02ee42393aa630a5764a82). Please check them in the RTD preview at https://volto--6024.org.readthedocs.build/user-manual/blocks.html#teaser-block. My screenshot is an assemblage of parts, and not an actual one.

**Comment by stevepiercy** [comment]
i18n is failing, probably due to the change in msgs. I'll see if I can fix that and push.

**Comment by stevepiercy** [comment]
I hope I did that right in [216698f](https://github.com/plone/volto/pull/6024/commits/216698fd3371f4e8c3525e249615f33ac350eba3). I did `yarn i18n` from inside the Volto package, commit, then push.

**Review by stevepiercy — APPROVED** [review]

**Comment by sneridagh** [comment]
@stevepiercy mmm I checked the screenshot of the docs, and the check should be checked. Maybe a screenshot issue?

**Comment by sneridagh** [comment]
@stevepiercy pushed the new image.

**Pull request merged**
