### PR TITLE
Allow editor to edit metadata name during bulk or single upload

### LINKED ISSUE #5549: Allow editors to edit metadata on bulk upload of images
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

285842702-b7c4ef2b-9a6f-4804-b9e9-5ee2293f12ed

285841737-ad8dea61-b9a8-451c-8c16-68cfb6890b16

### PR DESCRIPTION
**Pull request by iFlameing**
Fixes #5549

@tisto screenshot

Screenshot 2023-12-21 at 5 55 00 PM

### CODE REVIEW

**Comment by Aarav238** [comment]
Hey @iFlameing , Can you please help me in passing acceptance test ? I tried all the things that were mentioned in docs

**Comment by iFlameing** [comment]
> Hey @iFlameing , Can you please help me in passing acceptance test ? I tried all the things that were mentioned in docs

In which pr do you need help.

**Comment by stevepiercy** [comment]
@Aarav238 all the acceptance tests in this PR pass, so I don't understand what help you need here.

**Comment by Aarav238** [comment]
Yeah @stevepiercy I am not talking about this PR, I was seeking help for my PR, It was failing for acceptance tests. Now it is working fine. 
Thanks @iFlameing @stevepiercy.

**Review by sneridagh — CHANGES_REQUESTED** [review]
@iFlameing I'd make the input field a bit more wider.

**Comment by iFlameing** [comment]
@sneridagh new screenshot
Screenshot 2024-01-02 at 4 13 33 PM

**Comment by iFlameing** [comment]
@sneridagh ping. You can merge this now.

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
