### PR TITLE
Object browser with max item selectable

### PR DESCRIPTION
**Pull request by giuliaghisini**
If maximumSelectionSize is set in widgetOptions.pattern_options from plone, widget allows to select the maximumSelectionSize items.

This will need to be merged after this pullrequest:
https://github.com/plone/volto/tree/object_browser_with_selectable_types

### CODE REVIEW

**Comment by giuliaghisini** [comment]
@tisto @sneridagh, do you think this can be merged in to the master?
We would need it for some of our projects
Thank you!

**Comment by tisto** [comment]
@giuliaghisini do you have an example how to set pattern_options? Does that happen in the z3c form interface declaration? Sorry for my ignorance here but apart from the very beginning I never worked with patternslib.

PR looks ok to me. We would just need to resolve the merge conflicts...

**Comment by giuliaghisini** [comment]
> @giuliaghisini do you have an example how to set pattern_options? Does that happen in the z3c form interface declaration? Sorry for my ignorance here but apart from the very beginning I never worked with patternslib.
> 
> PR looks ok to me. We would just need to resolve the merge conflicts...

Yes! 
These are  two examples where we set the number of **maximumSelectionSize** when declaring a field for contentype:


  form.widget(
        "a_cura_di",
        RelatedItemsFieldWidget,
        vocabulary="plone.app.vocabularies.Catalog",
        pattern_options={
            "**maximumSelectionSize**": 1,
            "selectableTypes": ["UnitaOrganizzativa"],
        },
    )

 form.widget(
        "notizie_correlate",
        RelatedItemsFieldWidget,
        vocabulary="plone.app.vocabularies.Catalog",
        pattern_options={
            "**maximumSelectionSize**": 10,
            "selectableTypes": ["News Item"],
        },
    )

**Comment by giuliaghisini** [comment]
@tisto this is ready to merge

**Comment by giuliaghisini** [comment]
> @giuliaghisini Can you also add some documentation here? https://github.com/plone/volto/blob/master/docs/source/blocks/editcomponent.md
> 
> The ObjectBrowser is documented there. Also, fix the broken format of that document, it's broken at its end.
> See https://docs.voltocms.com/blocks/editcomponent/ to see how it's rendered.

added and fixed docs!

**Pull request merged**
