### PR TITLE
Fix import path in App.jsx

### PR DESCRIPTION
**Pull request by jimbiscuit**
Fix Import to fix component shadowing App.jsx

### CODE REVIEW

**Review by nileshgulia1 — APPROVED** [review]

**Review by nzambello — APPROVED** [review]
LGTM

**Comment by tiberiuichim** [comment]
The thing is, I'm baffled that this is needed. We use a special webpack resolver plugin that "rewrites" all the imports, so this sort of thing shouldn't be needed.

@jimbiscuit Can I have a confirmation that you've tried to shadow those files and they didn't work? Maybe, if you have time, you can try poking around https://github.com/plone/volto/blob/master/webpack-relative-resolver.js to see if you can get some info on what could be wrong?

**Comment by tiberiuichim** [comment]
Or maybe it's just a problem of "if I shadow App.jsx, then I'll have to rewrite those imports in the shadowed file" ?

**Comment by nileshgulia1** [comment]
I'm +1 on using absolute imports at least in the component level in all volto-core components. @tiberiuichim This can also go into one of https://github.com/plone/volto/issues/2810 :)

**Comment by tiberiuichim** [comment]
@nileshgulia1 I'm conflicted on this one. Personally, as a developer writing Volto code I like being able to reference components and modules with relative paths. It's quicker to write the imports (they're usually shorter), avoids having to add them to the big `components/index.js` index, etc. 

Now, one year ago, Volto code that was written with this style of imports was impossible to customize. For example, if App.jsx imports '../SomeComponent', the `SomeComponent.jsx` file would be impossible to shadow without also shadowing App.jsx. So I wrote the webpack-relative-resolver plugin that fixes the problem, so now we are free to use whatever the code style we want, as we're guaranteed that shadowing will work.

But there's still a problem, though it's an easy fix: when I copy a Volto file in my project, to shadow, if the file contains code with relative imports, I'll have to tweak my copy to fix those imports. Indeed, not the best.

**Review by tiberiuichim — APPROVED** [review]

**Pull request merged**
