### PR TITLE
@@display-file support

### PR DESCRIPTION
**Pull request by cekk**
Plone has a view called **@@display-file** that is similar to **@@download** but only exposes the file and do not add additional header to download it.
It could be useful if we want to show files and not directly download them.

With these changes Volto can handle that endpoint too.

### CODE REVIEW

**Comment by stevepiercy** [comment]
This sounds like a good feature to add to Volto's documentation, too. I'm not sure where, though.

**Review by giuliaghisini — APPROVED** [review]

**Review by nileshgulia1 — APPROVED** [review]

**Review by sneridagh — APPROVED** [review]

**Comment by stevepiercy** [comment]
@sneridagh I found no reference to either `@@download` or `@@display-file` in `plone.api` or `plone.restapi`. At the very least, I think something should be in the Volto docs, even if it is something like "There is no documentation in the backend about how to use this endpoint". Documenting that it is not documented is better than no documentation at all.

**Comment by sneridagh** [comment]
@stevepiercy ^^ :)

**Comment by sneridagh** [comment]
@stevepiercy merging this, I need to have things settled for pushing for the first 16alpha. I hope is fairly ok! We can amend it later.

**Pull request merged**
