### PR TITLE
Add contributing branch policy information

### PR DESCRIPTION
**Pull request by sneridagh**
Related to https://github.com/plone/volto/issues/3574

### CODE REVIEW

**Comment by stevepiercy** [comment]
I pushed a commit to this branch as my review. I needed to see it previewed first, which meant I needed to pull it down anyway. Writing this stuff is _hard_. Check out the preview:

https://637a99381c657b0009bed273--volto.netlify.app/developer-guidelines/contributing.html#branch-policy

@sneridagh @davisagli any other folks who should review?

**Comment by stevepiercy** [comment]
@sneridagh who else should review this?

**Comment by ksuess** [comment]
> @sneridagh who else should review this?

@plone/volto-team

**Review by erral — APPROVED** [review]
As discussed at the Volto Team meeting, I find it OK

**Comment by ksuess** [comment]
Just a short comment. 

I think this belongs to "Contributing". May I suggest to name a main navigation item "Contributing".
Then "Contributing" is the link that can be posted if there is a need to clarify where to target, which branch, what the piep is canary, what means stable, ....

"Developer guidelines" is for both: "understand Volto and make your thing" and also "understand Volto to contribute to Volto". 

I would like to suggest to move "Dev guidelines" in navigation just after " dev recipes".


grafik

**Comment by stevepiercy** [comment]
@ksuess to clarify, this PR is only about adding a new section to the existing page [Contributing to Volto](https://637a99381c657b0009bed273--volto.netlify.app/developer-guidelines/contributing.html#).

Screen Shot 2022-11-25 at 4 05 35 AM

This PR is part of resolving https://github.com/plone/volto/issues/3574.

Your comments would be helpful toward resolving that issue, specifically about how to organize Contributing in the Volto docs. I would like the Volto team to discuss the issue further there before reorganizing and creating a contributing section at the top level.

**Comment by sneridagh** [comment]
@stevepiercy since we agreed on the contents of this PR in the Volto Team meeting, I would merge this, so we are sure that we are on the same page regarding the contents of it, and it's in the docs already.

**Comment by ksuess** [comment]
> @ksuess to clarify, this PR is only about adding a new section to the existing page [Contributing to Volto](https://637a99381c657b0009bed273--volto.netlify.app/developer-guidelines/contributing.html#).
> 
> Screen Shot 2022-11-25 at 4 05 35 AM
> 
> This PR is part of resolving #3574.
> 
> Your comments would be helpful toward resolving that issue, specifically about how to organize Contributing in the Volto docs. I would like the Volto team to discuss the issue further there before reorganizing and creating a contributing section at the top level.

Ah, OK.

**Review by ksuess — APPROVED** [review]

**Pull request merged**
