### PR TITLE
feat: Added initialBlocksFocus to blocks config, to set default focus…

### PR DESCRIPTION
**Pull request by giuliaghisini**
… on non-first block

If we want to default focus a block that is not the first block. 

For example, if we have this configuration:
 ```
config.blocks.initialBlocks = {
    ...config.blocks.initialBlocks,
    Document: ['breadcrumbs', 'title'],
    Project: ['breadcrumbs', 'title'],
    Story: ['breadcrumbs', 'title'],
  };
```
and we want to focus by default the 'title' block, that isn't the first, we could add this in the config:

 ```
config.blocks.initialBlocksFocus = {
    ...config.blocks.initialBlocksFocus,
    Document: 'title',
    Project: 'title',
    Story: 'title',
  };
```

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]
It would be nice to have a test on this.

**Comment by giuliaghisini** [comment]
> It would be nice to have a test on this.

i can not run cypress test because of this error:

```
Version and requirements information containing plone.schema:
  [versions] constraint on plone.schema: 1.2.0
  Requirement of plone.restapi==8.16.2: plone.schema>=1.2.1
While:
  Installing instance.
Error: The requirement ('plone.schema>=1.2.1') is not allowed by your [versions] constraint (1.2.0)
make: *** [test-acceptance-server] Error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @plone/volto@14.0.0-alpha.42 ci:start-api-plone: `make test-acceptance-server`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @plone/volto@14.0.0-alpha.42 ci:start-api-plone script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/giuliaghisini/.npm/_logs/2021-12-17T11_29_08_964Z-debug.log
Error: server closed unexpectedly
    at ChildProcess.onClose (/Users/giuliaghisini/progetti/volto/volto/node_modules/start-server-and-test/src/index.js:68:14)
```

**Comment by nileshgulia1** [comment]
@giuliaghisini Try pinning `plone.restapi=8.13.0` in buildout or if you use docker then in here https://github.com/plone/volto/blob/master/Makefile#L123

**Comment by giuliaghisini** [comment]
> @giuliaghisini Try pinning `plone.restapi=8.13.0` in buildout or if you use docker then in here https://github.com/plone/volto/blob/master/Makefile#L123

i'm trying to use doker but that https://github.com/plone/volto/blob/master/Makefile#L123 doesn't work and fires the error above

**Comment by sneridagh** [comment]
@giuliaghisini sorry, my bad, it seems that the commenting side by side in the buildout lines messed up things.

Now master should be fine.

**Comment by giuliaghisini** [comment]
> 

not yet.

i'm having this error

```
Version and requirements information containing plone.schema:
  [versions] constraint on plone.schema: 1.2.0
  Requirement of plone.restapi==8.16.2: plone.schema>=1.2.1
While:
  Installing instance.
Error: The requirement ('plone.schema>=1.2.1') is not allowed by your [versions] constraint (1.2.0)
make: *** [test-acceptance-server] Error 1
error Command failed with exit code 2.
```

**Comment by sneridagh** [comment]
Strange, I've been doing some decelopment this weekend and all good. I'll take a look later.

**Comment by giuliaghisini** [comment]
@sneridagh @tiberiuichim could we merge it? we need it as soon as possibile

**Review by sneridagh — APPROVED** [review]

**Comment by sneridagh** [comment]
@SaraBianchi signed the contributor agreement already, and she has access to the repo. 

@ableeb There's something else to do? Any clue why Mr.Roboto is complaining? Thanks!

**Pull request merged**
