### PR TITLE
Fixing Typos

### PR DESCRIPTION
**Pull request by FritzHoing**
This MR just fixes some typos i stumbled upon.

----
📚 Documentation preview 📚: https://volto--6109.org.readthedocs.build/

### CODE REVIEW

**Comment by stevepiercy** [comment]
@FritzHoing this is another super useful contribution, but we can't accept it until you sign the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement). This PR should also have a [change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry). Would you please take the necessary steps? Thank you!

**Comment by FritzHoing** [comment]
Thank you very much for your feedback! I signed the Contributor Agreement on monday already and just need to wait for the approval. The changelog entry is now added.

**Comment by stevepiercy** [comment]
@FritzHoing would you please resolve the merge conflicts against `main`? We deleted `api/*`, and there is something up with `packages/volto/src/helpers/Extensions/withBlockExtensions.js`. Thank you!

**Comment by FritzHoing** [comment]
The merge conflicts are resolved by now, but now the towncrier does not notice the changellog.md anymore. Sorry for the back and forth.

**Comment by stevepiercy** [comment]
This is easy to miss in the GitHub UI:

Screenshot 2024-06-21 at 2 22 12 AM

**Comment by stevepiercy** [comment]
I just clicked it, and we'll see if it passes now.

**Comment by stevepiercy** [comment]
I see the issue. Volto is a monorepo which contains multiple packages and apps. Whenever you make a change to any package, you must include a change log entry inside that package.

You changed files in:

- `packages/volto`
- `packages/registry`

You have a change log entry only in:

- `packages/volto/news`

So duplicate that one and place the copy in:

- `packages/registry`

Then all should be good.

**Review by stevepiercy — APPROVED** [review]
LGTM, pending the missing changelog entry.

**Comment by stevepiercy** [comment]
Whoops, when changing the message strings, you need to run `yarn i18n`, as described in https://6.docs.plone.org/volto/development/i18n.html#extract-i18n-strings. That should take care of that one.

**Review by ichim-david — APPROVED** [review]

**Comment by ichim-david** [comment]
@FritzHoing thank you for your contribution, typos might be a minor thing for some but it's an easy contribution for people such as yourself as a first-time contributor and they enhance the quality of our codebase by having propper spelling.

**Pull request merged**
