### PR TITLE
Added placeholder param to widget, to change default placeholder

### PR DESCRIPTION
**Pull request by giuliaghisini**

### CODE REVIEW

**Comment by tiberiuichim** [comment]
@giuliaghisini check if the placeholder is available as a control in all the touched widget stories, start storybook with `yarn storybook`. I think the widgets that define proptypes will have them, but those that don't, won't have them, in which case you should add them as a possible control in the story (maybe even define a custom story for the placeholder option? )

**Comment by giuliaghisini** [comment]
> @giuliaghisini check if the placeholder is available as a control in all the touched widget stories, start storybook with `yarn storybook`. I think the widgets that define proptypes will have them, but those that don't, won't have them, in which case you should add them as a possible control in the story (maybe even define a custom story for the placeholder option? )

@tiberiuichim i've tested the StoryBook and fixed stories

**Comment by giuliaghisini** [comment]
@tiberiuichim @sneridagh

**Comment by giuliaghisini** [comment]
@tiberiuichim @sneridagh

**Review by pnicolli — APPROVED** [review]
LGTM

**Review by nileshgulia1 — APPROVED** [review]

**Review by mamico — APPROVED** [review]

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
