### PR TITLE
change opacity of sidebar toggle button

### LINKED ISSUE #4131: Right side "sidebar handle" button is not noticeable
**Describe the bug**
The right side `sidebar handle`, people had issues and didn't know how to open and close it. What's worse (for new Volto editors), once you close the sidebar, it stays closed and the whole thing is lacking contrast and you won't know how to open it. It's a major UX problem.

**To Reproduce**

1. Open Volto Editor, and click on any block.
2. On the right side, the `sidebar handle` button is not visible clearly.
3. If you click on it and close the sidebar, it will remain closed.

**Expected behavior**
The sidebar handle button should be more opaque so it can be easily noticeable. And also it should open again when you click on any block.

**Screenshots**

https://user-images.githubusercontent.com/99530996/207945357-aff82593-48cd-47de-9087-52e2d92de1b0.mp4

**Software (please complete the following information):**

- Volto Version [e.g. 8.5.0]
- Plone Version [e.g. 5.2.2]
- Plone REST API Version [e.g. 7.0.1]

### PR DESCRIPTION
**Pull request by MAX-786**
fixes #4131 

In "theme/themes/pastanaga/globals/site.variables" changed variable `sidebarToggleButtonNormalOpacity:` from 0.05 to 0.3 and when on hover state changed opacity from 0.3 to 0.5 which makes it more noticeable and improves UX.
### Demo

https://user-images.githubusercontent.com/99530996/208029781-32bd2bca-6886-473c-a439-f825d1f8068a.mp4

### CODE REVIEW

**Comment by tiberiuichim** [comment]
Some time ago on a client project we added an animation which flashed the sidebar toggle on entering the page, to draw attention to it. @sneridagh would that be a good idea here?

**Comment by MAX-786** [comment]
To draw more attention to the sidebar toggle we can add tilting and poping up animation to it everytime page loads.

**Comment by aadarsh-nagrath** [comment]
> Some time ago on a client project we added an animation which flashed the sidebar toggle on entering the page, to draw attention to it. @sneridagh would that be a good idea here?

Blinking does work , but changing its color seems better idea -> like the default grey or blue 
image

**Comment by MAX-786** [comment]
Hi @aadarsh-nagrath, this PR is closed but you can check issue #3910 related to this and the already existing WIP PR #3912 .

**Pull request closed without merging**
