### PR TITLE
Implement the Upgrade Control Panel

### LINKED ISSUE #3832: Implement Upgrade Control Panel
Implement a control panel to manage Plone upgrades

### PR DESCRIPTION
**Pull request by ericof**
Fixes #3832

## Todo

- [ ] Write tests

## Prepare the backemd environment
```shell
mkdir volto-backend
cd volto-backend
mkdir data && sudo chown 500:500 data
```
Create a `Dockerfile`
```Dockerfile
FROM plone/plone-backend:6.0.0b1
RUN /app/bin/pip install plone.restapi==8.32.0 \
    && chown -R plone:plone /app/
```
Create a `start.sh` file
```bash
docker build . -f Dockerfile -t plone-upgrade
docker run -p 8080:8080 -v data:/data -e SITE=Plone plone-upgrade
```
Now, start the backend and create a new site
```shell
chmod +x start.sh
./start.sh
```
Stop the process, and edit `Dockerfile`
```Dockerfile
FROM plone/plone-backend:6.0.0b3
RUN /app/bin/pip install plone.restapi==8.32.0 \
    && chown -R plone:plone /app/
```
Start the backend again:
```shell
./start.sh
```

### CODE REVIEW

**Review by sneridagh — APPROVED** [review]
LGTM so far

**Comment by sneridagh** [comment]
@ericof ready to merge, I'd say

**Comment by stevepiercy** [comment]
Would this be a good candidate to be documented in https://github.com/plone/volto/issues/3827 or elsewhere?

**Comment by sneridagh** [comment]
@stevepiercy by all means

**Pull request merged**
