### PR TITLE
Fix withStylingSchemaEnhancer enhancer mechanism

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Review by tiberiuichim — COMMENTED** [review]
@sneridagh I think we should do a hoc (per your initial design) instead of the component hacks, here https://github.com/plone/volto/blob/4a1df9aa85d7c0080b8fdab7bd4d71bda4a9a8b2/src/components/manage/Blocks/Block/StyleWrapper.jsx#L5

**Comment by sneridagh** [comment]
I tried, but it breaks badly, because of the default values implementation, somehow 😞. Infinite updates I think... Didn't manage to debug it.

**Comment by tiberiuichim** [comment]
@sneridagh then we should avoid avoid doing default values in component useEffects. We need to do it as a proper schema + formlib implementation, with default values computed with proper methods in the schema (even async). Maybe we need to think on using a form lib implementation, such as formik or whatever.

**Comment by sneridagh** [comment]
I couldn't agree more... we should go a step back and evaluate again the defaults inplementation. 

However the including such a lib might be challenging and time consuming 😩

**Comment by sneridagh** [comment]
@tiberiuichim let's merge this and take the suggestions into account.

**Pull request merged**
