### PR TITLE
Used moment-timezone in DatetimeWidget; Added default timezone in config

### PR DESCRIPTION
**Pull request by razvanMiu**

### CODE REVIEW

**Comment by tisto** [comment]
@razvanMiu thanks for the new PR. I just noticed that moment-timezone adds 80kb (gzipped) to our bundle which is really a lot. Would you mind looking into now we could reduce that size? I found https://github.com/moment/moment-timezone/issues/356. Another option would be lazy loading so that we do not bloat the main bundle.

**Comment by razvanMiu** [comment]
I've managed to decrease the size by 35 kB

**Comment by tisto** [comment]
@razvanMiu cool. Let's see what bundlewatch says about it. :)

**Comment by tisto** [comment]
````
File sizes after gzip:

  441.37 KB (-6.59 KB)   build/static/js/5.4892a4b0.chunk.js
  148.27 KB (-323 B)     build/static/js/client.613e1ae4.chunk.js
  101.59 KB (+22.41 KB)  build/static/js/6.0045cfae.chunk.js
  96.95 KB               build/static/css/5.6e205dd0.chunk.css
  32.92 KB               build/static/js/10.ad07c7f4.chunk.js
  30.22 KB               build/static/js/0.26c9cc21.chunk.js
  27.62 KB               build/static/js/7.a343ffb4.chunk.js
  15.38 KB               build/static/css/client.1271873a.chunk.css
  14.3 KB                build/static/js/9.ce139d5c.chunk.js
  13.51 KB               build/static/js/8.39c4a81b.chunk.js
  9.34 KB                build/static/js/16.73348dbe.chunk.js
  8.94 KB                build/static/js/11.92e14ec2.chunk.js
  8.8 KB                 build/static/js/20.cfb24a03.chunk.js
  8.8 KB                 build/static/js/15.d9cab01d.chunk.js
  8.52 KB                build/static/js/14.12733201.chunk.js
  7.84 KB                build/static/js/13.7b80ba7c.chunk.js
  7.49 KB                build/static/js/18.9c72e058.chunk.js
  7.48 KB                build/static/js/19.f1c6f196.chunk.js
  6.14 KB                build/static/js/17.48bfef65.chunk.js
  4.41 KB                build/static/js/12.04fd9d2e.chunk.js
  3.39 KB                build/static/css/6.983e23b6.chunk.css
  2.24 KB (+324 B)       build/static/js/plone-volto-components-manage-Widgets-DatetimeWidget.9784a885.chunk.js
  1.74 KB                build/static/js/runtime~client.3851fdee.js
  1.65 KB                build/static/js/plone-volto-components-theme-View-EventView.a07530b2.chunk.js

✨  Done in 65.98s.
````

**Comment by tisto** [comment]
@plone/volto-team this PR looks good to me. I'd like to see at least one other PR review though.

**Comment by avoinea** [comment]
For the future would be nice to also take in the consideration the backend settings of timezone `Site Setup > Date and Time`:

timezone

**Pull request merged**
