### PR TITLE
Adding PWA Functionality

### LINKED ISSUE #937: Turn Volto into a PWA
- Add the basic manifest.json and neccessary boilerplate
- Add an application shell for better loading experience

### PR DESCRIPTION
**Pull request by iFlameing**
Fixes #937. I am opening this because in previous pr plone test are failing. For more reference please see https://github.com/plone/volto/pull/1063

### CODE REVIEW

**Comment by iFlameing** [comment]
I don't know why Plone and guillotina test are failing. Can you restart the Travis CI?

**Comment by iFlameing** [comment]
@tisto I fixed the plone test only guillotina test are failing due to `unexpected closer of server`. I don't why this happening? Can you take a look on that? This will might be issue with travis CI cache can you please clean the cache and rerun the test?

**Comment by sneridagh** [comment]
Rerun the tests. @iFlameing I would like this to go into Volto 5, not the upcoming 4 final.

**Comment by sneridagh** [comment]
Closing this PR and marking as "Abandoned". 
This feature became uninteresting for the community.
If someone is interested in rescuing it, you can take it as a reference and open a new PR.

**Pull request closed without merging**
