### PR TITLE
Basic required boilerplate for @loadable/component support

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by sneridagh** [comment]
image

**Comment by sneridagh** [comment]
image

**Comment by tiberiuichim** [comment]
Nice work! 

It seems that two of the biggest files are luxon.js and moment.js, they deal with date and time localization. Is there a way this situation could be optimized? I know that some apps strip moment.js of its language support, to only ship with what's needed.

**Comment by sneridagh** [comment]
@tiberiuichim thanks!! Let's merge it, I think it's good enough to start with. Tomorrow I will cut a release.

**Comment by pnicolli** [comment]
❤️ this

**Pull request merged**
