### PR TITLE
Attempt to build the components storybook only when its source files …

### PR DESCRIPTION
**Pull request by stevepiercy**
…change

### CODE REVIEW

**Comment by stevepiercy** [comment]
@sneridagh this one is now ready and working, and I reverted its other PR to clean up the change log history. Note that the [Netlify build for `volto/components`](https://github.com/plone/volto/pull/5600#issuecomment-1876994133) gets cancelled when there are no changes to files in its `src` directory.

**Review by sneridagh — APPROVED** [review]

**Comment by sneridagh** [comment]
@stevepiercy it seems that it does not deploy to production (main) since we merged this. Any idea what could be happening? For the PR deploys works well (the filter) but it never deploys in main :(

**Comment by stevepiercy** [comment]
@sneridagh I'm not clear what you mean. AFAIK, we never deployed the components Storybook to production, only the Volto Storybook. The components Storybook still builds on Netlify at https://plone-components.netlify.app.

**Comment by sneridagh** [comment]
@stevepiercy sure, "production" Netlify. It never deployed again (last time was March).

**Comment by stevepiercy** [comment]
I just manually triggered a deploy. Can you check if you see the expected changes?

It should only build on changes in `packages/components/src`, if I read the config correctly. See:

https://app.netlify.com/sites/plone-components/configuration/deploys#continuous-deployment

I looked back in the history, and ever since Mar 23, 2024, Netlify builds have been cancelled, either because there are no changes in the components storybook or something else I have not yet identified. Can you point me to the first commit after Mar 23, 2024, to `main` where there are changes to files that should have triggered the deploy? Then we can figure out what went wrong.

**Comment by stevepiercy** [comment]
I think this should have built, but was cancelled. I don't know why.

https://app.netlify.com/sites/plone-components/deploys/664b27cd9235660008f4ca86

```
12:37:13 AM: git clone --filter=blob:none https://github.com/plone/volto
12:37:14 AM: Preparing Git Reference refs/heads/main
12:37:16 AM: Custom publish path detected. Proceeding with the specified path: 'packages/components/storybook-static'
12:37:16 AM: Custom ignore command detected. Proceeding with the specified command: 'git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./src/'
12:37:17 AM: Failed during stage 'checking build content for changes': Canceled build due to no content change
12:37:17 AM: manpath: warning: $PATH not set
12:37:17 AM: User-specified ignore command returned exit code 0. Returning early from build.
```

**Comment by stevepiercy** [comment]
I commented out the `ignore` command and force pushed to `main` to test.

- https://github.com/plone/volto/commit/4d0a701a85f2d86e7515dce99d97604e69caeb2b
- https://app.netlify.com/sites/plone-components/deploys/670f7ba167e3f0000843be6e

That works. That implies that we probably had the path for doing a diff wrong all along, but were relying on the root `./src` of the repo before we switched to the monorepo. In fact that's right about when we switched to monorepo, moving `./src` into `packages/volto/src/`, so there were no more changes to detect.

I'll submit a PR to fix the Netlify ignore command so we can get it in the change log. However we can't test it until we have a change in its `src` files, even if it is a trivial space or line break.

**Comment by stevepiercy** [comment]
@sneridagh PR: #6410

**Comment by sneridagh** [comment]
@stevepiercy thanks!!!

**Pull request merged**
