### PR TITLE
Japanese translation

### PR DESCRIPTION
**Pull request by terapyon**
Did not translation yet

### CODE REVIEW

**Comment by tisto** [comment]
@terapyon I updated the branch, fixed a merge conflict and ran i18n on it. Could you pls check if the Japanese translation works now on Volto?

**Comment by terapyon** [comment]
@tisto Thank you for the merging, But I did not check the po file. Please wait merging in a few days.

**Comment by tisto** [comment]
@terapyon sure. Just let me know when you are done and I will review and merge the PR afterward.

**Comment by terapyon** [comment]
@tisto I translate and checked for Japanese, a lot of sentence is good. Please merge.
I think the translation was not enough, so we continue do translation for Japanese.

**Comment by terapyon** [comment]
I translated Volto 4 for Japanese, I already pushed github. But I didn't commit build file, `ja.json`, should I commit the build file?

**Comment by tisto** [comment]
@terapyon yes. please commit the ja.json file.

**Comment by terapyon** [comment]
@tisto Can you merge this? or Not?

**Comment by tisto** [comment]
Travis is green.

**Comment by terapyon** [comment]
@tisto Please re-check.

**Comment by sneridagh** [comment]
@terapyon @tisto changelog needs to be updated, and merged with master

**Comment by terapyon** [comment]
Thank you very much. I wait to release next alpha. And we will translate more sentences.

**Pull request merged**
