### PR TITLE
Fixing the translation of header in babel view

### PR DESCRIPTION
**Pull request by iFlameing**

### CODE REVIEW

**Comment by tisto** [comment]
@giuliaghisini do you recall why you lowercased the "lang" attribute in the babel view? In German (and English), it is a spelling error to lower case the language term ("English", "German", etc.). This PR fixes this problem. I was just wondering about your motivation in the first place and if you are ok with our fix here.

**Comment by tisto** [comment]
@iFlameing pls check CI failures

**Review by giuliaghisini — APPROVED** [review]

**Comment by giuliaghisini** [comment]
> @giuliaghisini do you recall why you lowercased the "lang" attribute in the babel view? In German (and English), it is a spelling error to lower case the language term ("English", "German", etc.). This PR fixes this problem. I was just wondering about your motivation in the first place and if you are ok with our fix here.

There wasn't a particular reason for the lower case language term, in italian it does not matter if it is lower or upper case, so for me there's no problem to change it!

**Comment by tisto** [comment]
@giuliaghisini awesome. Thanks for the swift feedback!

**Comment by iFlameing** [comment]
@tisto can you please merge this :)

**Pull request merged**
