### PR TITLE
4301 pasting something in table block is throwing error

### PR DESCRIPTION
**Pull request by curiousyuvi**
**Fix:** Fixed pasting content in Table Block returns an error.

**Issue:** #4301

**Before:**
table-paste-issue-before

**After:**
table-paste-issue-after

**What I did:**
I turned on the **normalizeExternalData** extension for Table Block.

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Comment by curiousyuvi** [comment]
@tiberiuichim  please merge this, Thank you.

**Comment by curiousyuvi** [comment]
Hey @tiberiuichim, can you please merge this, Thank you.

**Comment by tiberiuichim** [comment]
@curiousyuvi Sorry, I don't merge commits, I'm not Volto's maintainer, that's @sneridagh.

In any case, you have to do two things before it can be merged:

- sign the Plone Developer Contributor agreement (search for it)
- create the PR from a plone/volto branch so that the tests of the CI can run

It would be a good idea, if possible, to add some Cypress tests related to table pasting.

**Comment by curiousyuvi** [comment]
Well, I don't know how to write cypress tests, but I'll make a PR from plone/volto branch, anyways Thank you.

**Comment by stevepiercy** [comment]
> Well, I don't know how to write cypress tests, but I'll make a PR from plone/volto branch, anyways Thank you.

This is an unfortunate response. A better response, showing how curious yuvi is, would have been, "I will [search the frontend docs for Cypress tests](https://6.docs.plone.org/search.html?q=cypress&doc_section=volto) and learn how to do what you request."

**Comment by curiousyuvi** [comment]
Hey @tiberiuichim and @stevepiercy, thanks a lot for your feedback on my PR. I'm sorry for my initial response - I know I could have handled it better. But your suggestions were spot on, and I'm really keen to learn how to write Cypress tests. I'll scour the frontend docs and make sure to include them in the PR.

Oh, and by the way, big thanks to @stevepiercy for helping me remember the word "curious" in my username! It got me thinking about why I created this username in the first place and about how important it is to stay curious, ask questions, and keep learning new things. Thanks again!

**Pull request closed without merging**
