### PR TITLE
Include the news folder in the repo FBO documentation git submodule

### PR DESCRIPTION
**Pull request by stevepiercy**
Before merging, please try to reproduce what I see locally. If you do not see it, then it is my local repo and possibly a symlink issue. This might be related to my work on https://github.com/plone/volto/pull/5135

---

For about the last month, when a submodule tip was included in some pull request, the news folder got dropped. Now `plone/documentation` always says this:

```shell
$ git status
On branch 6.0
Your branch is up to date with 'origin/6.0'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   submodules/volto (untracked content)

no changes added to commit (use "git add" and/or "git commit -a")
```

...even after manually going through those steps. So I think that this pull request will fix that. Now I see:

```shell
$ git status
On branch 6.0
Your branch is up to date with 'origin/6.0'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   submodules/volto (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
```

...which is hopeful.

### CODE REVIEW

**Comment by sneridagh** [comment]
@stevepiercy this one after #5135 right?

**Comment by stevepiercy** [comment]
After building docs locally, if you see that git submodule warning from `git status` _now_, then you can merge this PR now. If not, then after merging #5135, and after building docs locally, if you start to see that git submodule warning, then this PR will solve that issue. Basically I am not entirely sure when it started to appear for me locally, so I hoped someone else could try to reproduce it.

**Comment by sneridagh** [comment]
@stevepiercy the release (17.4.0) went well, no issues whatsoever, how about documentation? I think all good in there too, right? Can we say that this is not needed?

**Comment by stevepiercy** [comment]
I think it is needed.

Go into documentation and `make clean build`. One warning pops up:

```
/Users/stevepiercy/projects/Plone/documentation/docs/volto/index.md:46: WARNING: toctree contains reference to nonexisting document 'volto/news*'
```

...and when going into Volto:

```
 /Users/stevepiercy/projects/Plone/documentation/submodules/volto/docs/source/news/4947.feature: WARNING: document isn't included in any toctree
/Users/stevepiercy/projects/Plone/documentation/submodules/volto/docs/source/news/4949.feature: WARNING: document isn't included in any toctree
/Users/stevepiercy/projects/Plone/documentation/submodules/volto/docs/source/news/5294.breaking: WARNING: document isn't included in any toctree
/Users/stevepiercy/projects/Plone/documentation/submodules/volto/docs/source/news/5363.documentation: WARNING: document isn't included in any toctree
/Users/stevepiercy/projects/Plone/documentation/submodules/volto/docs/source/news/5364.bugfix: WARNING: document isn't included in any toctree
/Users/stevepiercy/projects/Plone/documentation/submodules/volto/docs/source/news/5367.internal: WARNING: document isn't included in any toctree
/Users/stevepiercy/projects/Plone/documentation/submodules/volto/docs/source/news/5368.bugfix: WARNING: document isn't included in any toctree
/Users/stevepiercy/projects/Plone/documentation/submodules/volto/docs/source/news/5370.documentation: WARNING: document isn't included in any toctree
/Users/stevepiercy/projects/Plone/documentation/submodules/volto/docs/source/news/5371.documentation: WARNING: document isn't included in any toctree
```

It appears the problem shifted from the git submodule error to these build errors, at least for me. If you can reproduce these warnings locally, then I would go ahead and merge it. If not, report back what you see, and we can troubleshoot.

**Comment by stevepiercy** [comment]
This PR is no longer necessary, as the issue has gone away. Closing.

**Pull request closed without merging**
