### PR TITLE
Fixed image upload test

### PR DESCRIPTION
**Pull request by zotya**

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Comment by tisto** [comment]
@iFlameing can you pls check this PR?

**Comment by iFlameing** [comment]
@zotya can you please! explain, what problem this pr solves because we really don't need this method ```Cypress.Blob.base64StringToBlob```. we already using cypress.upload which takes care of everything regarding upload.

**Comment by tiberiuichim** [comment]
@iFlameing there are random test failures on travis, which can't be explained by the code changes in the PR. This should fix those.

**Comment by tiberiuichim** [comment]
@iFlameing for example this one: https://github.com/plone/volto/pull/1811/checks?check_run_id=1119773199#step:17:461

**Comment by iFlameing** [comment]
@tiberiuichim thanks! for explaining :)

**Review by iFlameing — APPROVED** [review]

**Comment by tisto** [comment]
Let's give it a shot and monitor if this improves the situation. I prefer to go with the standard Cypress solution but if that's not good enough, we have to find workarounds to make the tests run in a stable manner.

**Pull request merged**
