### PR TITLE
[WIP] Prototype for image crop

### PR DESCRIPTION
**Pull request by iFlameing**
How to test this feature
1. create a news item.
2. select the image field.
you are able to see the crop image feature just select the area which you needed and click on save.

### CODE REVIEW

**Comment by tisto** [comment]
@iFlameing looks good! Can you set an image ratio of 4:3? Saving the image currently does not work but I guess you are aware of this.

**Comment by iFlameing** [comment]
@tisto I am unable to fix the eslint error regarding 
```bash
 missing dependency warning when using useEffect React Hook?
```
I found the problem because we are passing prop function to useEffect.
I tried to disable it but somehow I am unable to do so
```javascript
// eslint-disable-next-line react-hooks/exhaustive-deps
```

**Comment by iFlameing** [comment]
@tisto fixed :)

**Comment by tiberiuichim** [comment]
@iFlameing Please use loadables for the image crop lib

**Comment by tisto** [comment]
@plone/volto-team to preserve the uncropped original image, we need an additional field for the uncropped image on every single image that we have in Volto/Plone. I created a PR for the preview_image in kitconcept.volto:

https://github.com/kitconcept/kitconcept.volto/pull/11

The question here is "do we want to bake in image cropping into Volto/Plone core or not"?

**Comment by sneridagh** [comment]
Closing this PR and marking as "Abandoned". 
This feature became uninteresting for the community.
If someone is interested in rescuing it, you can take it as a reference and open a new PR.

**Comment by tisto** [comment]
@sneridagh I think image cropping is an essential feature for a CMS and should be one of our top priorities. However, I agree that we might have to start over again.

**Pull request closed without merging**
