### PR TITLE
issue: Apply suggestion from browser for password field  #3990

### PR DESCRIPTION
**Pull request by lord2anil**
Apply suggestion from browser for password field

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]
You'll have to fill in the contributor agreement, see the Contributing documentation page. Also, fill in the newsfile for the changelog.

@sneridagh We're changing the id of the login field. I don't think this is a breaking change, but who knows? It may break CSS styling, potentially.

**Comment by lord2anil** [comment]
> You'll have to fill in the contributor agreement, see the Contributing documentation page. Also, fill in the newsfile for the changelog.
> 
> @sneridagh We're changing the id of the login field. I don't think this is a breaking change, but who knows? It may break CSS styling, potentially.

I checked , no css is attched with is='password'.

**Comment by stevepiercy** [comment]
@lord2anil please follow https://6.docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request

**Comment by lord2anil** [comment]
@mister-roboto sir i already filed the Plone Contributor Agreement and sent a mail to [agreements@plone.org]

**Review by stevepiercy — CHANGES_REQUESTED** [review]

**Comment by lord2anil** [comment]
@sneridagh sorry for this , actually i forgot to create new branch.

**Comment by davisagli** [comment]
Closing this PR, because @lord2anil opened #4524 with just the autocomplete fix, and there are other PRs with just the responsiveness fix.

**Pull request closed without merging**
