### PR TITLE
Plone 6 docs

### PR DESCRIPTION
**Pull request by tiberiuichim**
Integration with the sphinx build for plone documentation, at this branch. https://github.com/plone/documentation/tree/6-dev

I've kept the changes minimal. We can adjust and optimize, along the way.

I've added some index files, I think they're needed for sphinx. The ways shinx does the navigation is a bit of a mystery to me, in any case, they're new files, no linked from the mkdocs configuration.

See also related PR at https://github.com/plone/documentation/pull/1160/files

### CODE REVIEW

**Comment by sneridagh** [comment]
@tiberiuichim 

Should we change from mkdocs to a MyST build in Volto as well? What do you think? I'd say so, to maintain coherence before all is settled. During the transition, it would be to maintain docs.voltocms.com up and running using the MyST build.

**Comment by tiberiuichim** [comment]
I've noticed that I've executed the "update md files with headers" script from the plone/documentation branch and it updated all .md files in Volto. I'll need to reset them, we don't want them changed.

**Comment by stevepiercy** [comment]
How do you want to manage branches in the long term? I assume that eventually we would want to pull  from `volto/master` into `documentation/6-dev` (and eventually `documentation/6.0` for release).

How about this process?

1. Create, finalize, and document process to pull volto docs into Plone docs, including how to contribute to volto docs and have those changes reflected back into Plone docs.
2. Convert to MyST and clean up bugs. Do not add new stuff yet.
3. `addMetaData.py` to add blank meta headers for improved SEO. Add content to the blank headers.
4. Any other updates.

I don't know how y'all would want to manage this, but I would think that at the completion of each step, merge this branch to master and cut a release of the docs, then reopen this branch with the next step. Thus we do not need to change the branch in the submodule until it is ready for final release. What do y'all think?

**Comment by tiberiuichim** [comment]
> Thus we do not need to change the branch in the submodule until it is ready for final release. What do y'all think?

Ok with me.

**Comment by nileshgulia1** [comment]
+1 from me. My just 2 cents, we can keep a common documentation for Volto either in Plone/documentation and docs.voltocms, or either link to the current one from Plone 6 docs.

**Comment by stevepiercy** [comment]
What are the next steps for this PR? Please add to the task list:

- [ ] Add MyST and Sphinx configuration from `plone/documentation@6-dev`
- [ ] Update doc tests, if any
- [ ] Update CI/CD to build docs
- [ ] __________

**Review by sneridagh — APPROVED** [review]

**Comment by stevepiercy** [comment]
@sneridagh is this PR really ready to merge to master, per your approval? For stand-alone Volto docs, is it correct that we want to switch from MkDocs to MyST/Sphinx, then when we are happy with the stand-alone build, replace the MkDocs version with the MyST/Sphinx version?

If so, we should make sure that this branch can build and deploy successfully to wherever the docs are hosted, using MyST and Sphinx as the platform.

**Comment by sneridagh** [comment]
@stevepiercy 

> Add MyST and Sphinx configuration from plone/documentation@6-dev

We can do it later, let me test if it still builds in mkdocs. However, we could start redirecting to the new domain asap.

>  Fix all but 2 broken links and redirects #3019

Commented in there. Sorry, busy day, if not I'd do it myself.

>  Update doc tests, if any

Nope.

> Update CI/CD to build docs

Don't think we need any now.

>  Do we migrate storybook and include it in the Plone 6 Documentation under docs/volto/storybook/?

good one, we can ask @ericof for it.

The rest LGTM, let's merge it. 

Then the documentation PR should point to master then, right?

**Comment by sneridagh** [comment]
@stevepiercy Fred has been working in some optimisations in #3010 . Let's merge that one first, then solve merging conflicts (they look ok). Then this one, ok?

**Comment by stevepiercy** [comment]
@sneridagh agreed. Let's see your results of mkdocs build. I expect the changes I made to some links will fail, because I converted them from Markdown to MyST/Sphinx syntax. There might be other issues that come up.

**Comment by sneridagh** [comment]
All good in my build... No worries for the links change, either we point to the new docs asap or we update the build with Sphinx/MyST.

**Review by nileshgulia1 — APPROVED** [review]
Screenshot 2022-02-01 at 9 30 43 PM

> If so, we should make sure that this branch can build and deploy successfully to wherever the docs are hosted, using MyST and Sphinx as the platform.
Fine by me if we are switching to MySt.

**Comment by sneridagh** [comment]
I've talked to Steve, we will wait until this is done and we have the MyST build in place.

So, he will merge the documentation PR, pointing to this PR for now.

**Comment by stevepiercy** [comment]
I caught a few issues that resulted from merging `master` into `plone6-docs`, fixed them, and pushed those commits. We're back into a good clean state on this PR.

From this point forward, please use pull requests to the branch `plone6-docs` to update it. This will allow peer review of work.

**Comment by sneridagh** [comment]
@stevepiercy I've been talking to @tiberiuichim and we both agreed that it would be best to resolve and merge the docs as soon as possible since this "in between, let's backport all the changes" is cumbersome. Since we don't really have a strong reason for not to merge it as soon as possible I'd try to move forward quickly on this one. I'm totally ok with having the Volto docs in https://6-dev-docs.plone.org and a redirect in docs.voltocms.com right away.

So, what is missing now?

/cc @tiberiuichim @ericof @tisto

**Review by stevepiercy — CHANGES_REQUESTED** [review]
These changes must wait. We have several prerequisites that need work before we can enable Sphinx and MyST on the `master` branch:

- https://github.com/plone/volto/issues/3033
- https://github.com/plone/volto/issues/3034
- https://github.com/plone/volto/issues/3036 => https://github.com/plone/volto/pull/3084
- https://github.com/plone/volto/issues/3037
- https://github.com/plone/volto/issues/3043 (Answered)
- https://github.com/plone/volto/issues/3044 => https://github.com/plone/volto/pull/3070
- https://github.com/plone/volto/issues/3071 => https://github.com/plone/documentation/pull/1185

**Comment by stevepiercy** [comment]
Just to confirm, it sounds like we do not need to update any CI/CD for deploying Volto docs, as we will be using Plone 6 Docs for that.

The only thing that you might want to add is something to automatically preview a PR or branch, like we do on Netlify for Plone 6 Docs. If that is needed, we can create an issue to track it. We have an Open Source License with Netlify, and I can add y'all to the team.

**Comment by stevepiercy** [comment]
One more todo, after merge to `master`, we need to update the Plone 6 Docs instructions and `Makefile` to use the `master` branch instead of `plone6-docs`, and update the git submodule. I will prepare a PR for that eventuality.

**Comment by sneridagh** [comment]
@stevepiercy status right now:

These changes must wait. We have several prerequisites that need work before we can enable Sphinx and MyST on the `master` branch:

- https://github.com/plone/volto/issues/3033
- https://github.com/plone/volto/issues/3034
- https://github.com/plone/volto/issues/3036 => https://github.com/plone/volto/pull/3084
- https://github.com/plone/volto/issues/3037 => https://github.com/plone/volto/pull/3085
- https://github.com/plone/volto/issues/3043 (Answered)
- https://github.com/plone/volto/issues/3044 => https://github.com/plone/volto/pull/3070
- https://github.com/plone/volto/issues/3071 => https://github.com/plone/documentation/pull/1185

Let's do this!

**Comment by stevepiercy** [comment]
> * [Docs need meta_html values #3033](https://github.com/plone/volto/issues/3033)

I thought about this one some more. I am OK with removing this as a requirement to merge this PR. There are 211 of these errors currently, and it takes time to create useful meta tags. I would much prefer to have quality SEO than hastily thrown together garbage. Instead whenever we update a page, let's make it a practice to update the `html_meta` values at the top of the page.

**Review by stevepiercy — APPROVED** [review]

**Comment by stevepiercy** [comment]
@sneridagh the final remaining requirements have been resolved. This PR can be merged at anytime. Please do the honors at your convenience.

**Comment by stevepiercy** [comment]
Oops, not so fast. We have two open PRs against this branch:

- [ ] https://github.com/plone/volto/pull/3066
- [ ] https://github.com/plone/volto/pull/3080/

**Comment by sneridagh** [comment]
@stevepiercy 😱 with pleasure! There are also some actions to do in the documentation repo afterwards, right?

**Comment by stevepiercy** [comment]
Correct. https://github.com/plone/documentation/pull/1182 is waiting to merge.

We also need to update the submodule pointer.

**Comment by sneridagh** [comment]
@stevepiercy merged backport, waiting for green on docs.

**Comment by sneridagh** [comment]
@stevepiercy also merged https://github.com/plone/documentation/pull/1182 and updated the tip of the submodule in documentation repo.

**Comment by sneridagh** [comment]
Mmmm Mr.Roboto thinks that the docs repo should be included in the checkouts of coredev? 

/cc @mauritsvanrees @jensens @fredvd @gforcada

**Comment by stevepiercy** [comment]
Thanks for merging both PRs.

Regarding coredev, see https://github.com/plone/buildout.coredev/issues/768

**Pull request merged**
