### PR TITLE
feat(volto.po): refactoring and implementing new portuguese (BR) translate

### PR DESCRIPTION
**Pull request by LeuAlmeida**
_I messed up and ended up setting the wrong remote, and with that I pushed the master branch. Lucky I saw it at the time and, with that, I already reversed. I apologize for the inconvenience._

As I had made these modifications a few days ago (and having had conflicts), I noticed that there were new keys to be translated and therefore I opened a new PR for another fork.

Thanks you all :rocket:

### CODE REVIEW

**Comment by sneridagh** [comment]
@LeuAlmeida can you sync with master and push again?
Thanks!!

**Comment by tisto** [comment]
@LeuAlmeida ping. :) We would love to merge and release this. Could you pls look into the merge conflicts?

**Comment by sneridagh** [comment]
@LeuAlmeida Ping! We cannot fix this if you make a fork. In the future, please open a local branch in the repo.

**Comment by sneridagh** [comment]
I think this is stale, closing. @LeuAlmeida there has been also more developments on the pt_BR translation, please update to master and create a new PR if you feel like so. Thanks!

**Pull request closed without merging**
