### PR TITLE
Fix different querystring filters in the querystring widget

### PR DESCRIPTION
**Pull request by kreafox**
If you add more than one criteria in the querystring widget those options are different from the first, default criteria options. 

Options that are disabled in the `@querystring` endpoint should not be included in the criteria dropdown. This PR filters these options in the first Criteria list as well. 

Solves #2794

### CODE REVIEW

**Comment by sneridagh** [comment]
@kreafox while you are on it :) Do you think that it's easy to remove from the list an already added Criteria? eg. You add a `Type` criteria, then you can add it again... only the last one work. We can merge this one in the meanwhile, of course.

**Comment by fredvd** [comment]
> @kreafox while you are on it :) Do you think that it's easy to remove from the list an already added Criteria? eg. You add a `Type` criteria, then you can add it again... only the last one work. We can merge this one in the meanwhile, of course.

@sneridagh Are you sure this is the most UX friendly behavior? IMHO you shouldn't be able to add the second (duplicate) and criterions in use should be greyed out.

By removing the first already configured criterion, user can unintentionally alter the existing query without noticing. Worse: the previous query cannot be restored, say there was a type criterion with 4 content types set: these are dropped and the current editor cannot remember what they were...

**Comment by sneridagh** [comment]
@fredvd I expressed myself poorly, I meant what you say. We should grey out the criteria already chosen in the dropdown.

@kreafox do you think that you could take a look or should we just merge this one?

**Comment by kreafox** [comment]
@sneridagh Just a small issue: If you select the first option, which in our case is the "Creator" and select another criteria or you open an existing one, the first option "Creator" it doesn't look like a disabled option at first with grey color until you hover it. It is a very strange bug and it is only happening with the first option (you can see in my demo) I couldn't identify yet what's causing it. But other than that it is working as expected.

https://user-images.githubusercontent.com/20109479/167846427-c700bc85-ff89-4847-a30e-123a672931cd.mp4

**Comment by sneridagh** [comment]
@kreafox caught it! :) 🎉 

I will merge on green.

**Pull request merged**
