### PR TITLE
handles condition for yearly frequency in recurrence

### LINKED ISSUE #4498: Wrong recurrence string made in Volto
**Describe the bug**

It seems that the rrule string generated in Volto isn't correct.

**To Reproduce**

How to reproduce it:

- Add an Event
- Set start and end date (end some years in the future)
- Select recurrence: yearly, every 1 year, repeat the same day and stop after 3 recurrences
- Save

**Expected behavior**

Event can be saved with the selected recurrence, but Plone returns an error because the string is not well formatted.
The same setting in Classic Plone Works.

Volto send a string like this:

`RRULE:INTERVAL=1;COUNT=3;BYMONTHDAY=10;BYMONTH=3" `

Same settings in Plone:

`RRULE:FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=10;COUNT=3`

This is the traceback:

> Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 376, in publish_module
  Module ZPublisher.WSGIPublisher, line 271, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module plone.rest.service, line 22, in __call__
  Module plone.restapi.services, line 19, in render
  Module plone.restapi.services.content.add, line 93, in reply
  Module plone.restapi.services.content.utils, line 95, in add
  Module OFS.ObjectManager, line 383, in _setObject
  Module zope.event, line 32, in notify
  Module zope.component.event, line 27, in dispatch
  Module zope.component._api, line 134, in subscribers
  Module zope.interface.registry, line 448, in subscribers
  Module zope.interface.adapter, line 899, in subscribers
  Module zope.component.event, line 36, in objectEventNotify
  Module zope.component._api, line 134, in subscribers
  Module zope.interface.registry, line 448, in subscribers
  Module zope.interface.adapter, line 899, in subscribers
  Module Products.CMFCore.CMFCatalogAware, line 274, in handleContentishEvent
  Module Products.CMFCore.CMFCatalogAware, line 197, in notifyWorkflowCreated
  Module Products.CMFCore.WorkflowTool, line 300, in notifyCreated
  Module Products.CMFCore.WorkflowTool, line 610, in _reindexWorkflowVariables
  Module Products.CMFCore.CMFCatalogAware, line 110, in reindexObjectSecurity
  Module Products.CMFCore.CatalogTool, line 272, in unrestrictedSearchResults
  Module Products.CMFCore.indexing, line 97, in processQueue
  Module Products.CMFCore.indexing, line 227, in process
  Module Products.CMFCore.indexing, line 49, in reindex
  Module Products.CMFCore.CatalogTool, line 368, in _reindexObject
  Module Products.CMFPlone.CatalogTool, line 361, in catalog_object
  Module Products.ZCatalog.ZCatalog, line 507, in catalog_object
  Module Products.ZCatalog.Catalog, line 341, in catalogObject
  Module Products.ZCatalog.Catalog, line 292, in updateMetadata
  Module Products.ZCatalog.Catalog, line 425, in recordify
  Module plone.indexer.wrapper, line 65, in __getattr__
  Module plone.indexer.delegate, line 20, in __call__
  Module plone.app.event.dx.behaviors, line 348, in end_indexer
  Module plone.app.event.dx.behaviors, line 503, in end
  Module plone.app.event.dx.behaviors, line 479, in _recurrence_upcoming_event
  Module plone.app.event.recurrence, line 100, in occurrences
  Module plone.event.recurrence, line 110, in recurrence_sequence_ical
  Module dateutil.rrule, line 1732, in __call__
  Module dateutil.rrule, line 1707, in _parse_rfc
  Module dateutil.rrule, line 1561, in _parse_rfc_rrule
TypeError: __init__() missing 1 required positional argument: 'freq'

The difference seems to be in missing FREQ, but i'm not a dates expert.

**Software (please complete the following information):**

Tested also on https://demo.plone.org

### PR DESCRIPTION
**Pull request by BhuvaneshPatil**
fixes #4498 

This changes handles the condition for yearly recurrence.

The older version of this code, was checking `if(value)` , so `value = 0` will be falsy and will result in unexpected behavior.

### CODE REVIEW

**Comment by cekk** [comment]
This seems fixing the error

**Review by sneridagh — CHANGES_REQUESTED** [review]
LGTM @BhuvaneshPatil we need a changelog entry (towncrier)

**Comment by SaraBianchi** [comment]
Hi @BhuvaneshPatil, @cekk and I may need this fix. 
Could you add the changelog entry please, if you don't know how the reference is here https://6.docs.plone.org/contributing/index.html?highlight=towncrier#change-log-entry. Thanks

**Comment by cekk** [comment]
@BhuvaneshPatil @sneridagh we need this fix for our projects..can i add the changelog for @BhuvaneshPatil so we can close the issue?

**Comment by sneridagh** [comment]
@cekk By all means

**Comment by cekk** [comment]
@sneridagh done!

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
