### PR TITLE
Babel housekeeping

### PR DESCRIPTION
**Pull request by sneridagh**
Trying to simplify the Babel config, using only stage 4 proposals in core, leaving all the work to babel-razzle-preset (which relies on @babel/preset-env

### CODE REVIEW

**Comment by sneridagh** [comment]
@plone/volto-team This is ready to review, I would like to explain and discuss it in the next Volto Team meeting and propose a Volto 9 release relatively soon

**Review by tiberiuichim — APPROVED** [review]
Very nice explanations! Maybe also copy the upgrade guide info to the https://docs.voltocms.com/developer-guidelines/language-features/ ?

**Comment by sneridagh** [comment]
@plone/volto-team I realised that we are not including `browserslist` entry in `package.json` in the generators, thus by default, the bundles are using the defaults:

```
> 0.5%, last 2 versions, Firefox ESR, not dead.
```

I updated Volto to have by default this (but the projects do not inherit it):

```json
  "browserslist": [
    ">1%",
    "last 4 versions",
    "Firefox ESR",
    "not ie 11",
    "not dead"
  ],
```

What do you think of add this config to the generators?

**Review by tiberiuichim — APPROVED** [review]

**Comment by tiberiuichim** [comment]
@sneridagh The preset for generator looks good.

We've had an edge case last year for IE11 compatibility, at some point we were bundling some code from node_modules that was not compatible with IE11. To solve the problem we've added an postinstall script to transpile that code using babel:

```
./node_modules/.bin/babel --presets="@babel/env" XXX --out-dir XXX
```

**Comment by sneridagh** [comment]
@tiberiuichim ^^

**Comment by tisto** [comment]
@plone/volto-team ready for merge for 9.x.x.

**Pull request merged**
