### PR TITLE
bugs: fixes toggle menu

### LINKED ISSUE #5645: Toolbar Menu Toggle and Outside Click Handling Bug
When you click on a toolbar icon, the menu that pops up isn't closing properly with a second click on the same icon. It's supposed to toggle open and closed each time you click, but right now, it just stays open. Secondly, our outside click feature, which is meant to close the menu if you click anywhere else on the screen, isn't working when you click on the user button. Ideally, clicking anywhere outside the menu should close it, but currently, clicking on the user button doesn't have this effect.

**Steps to reproduce the behavior:**

- Open the application and navigate to a page where the toolbar is present.
- Click on any toolbar icon to open the corresponding menu.
- Click on the same icon again. Observe that the menu does not close as expected.
- Now, with the menu open, click on the user button. Notice that the menu remains open instead of closing.-

**Expected behavior**
The menu should toggle (open/close) when the corresponding toolbar icon is clicked.
Any click outside of the open menu, including clicks on the user button, should close the menu.

**Screen Recording **
[sidebar open closing bug.webm](https://github.com/plone/volto/assets/138920477/997b439c-0f2c-4d37-9dce-742239a07301)

### PR DESCRIPTION
**Pull request by ravjot07**
Closes #5645

### CODE REVIEW

**Comment by ravjot07** [comment]
> @ravjot07 you need to sign the Plone Contributor Agreement to merge this pull request.
> 
> Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

I have already signed Plone Contributor Agreement

**Comment by stevepiercy** [comment]
@ravjot07 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), specifically [Sign and return the Plone Contributor Agreement](https://6.docs.plone.org/contributing/index.html#sign-and-return-the-plone-contributor-agreement) for the time.

**Comment by ravjot07** [comment]
My PR closes this issue.

**Comment by stevepiercy** [comment]
@ravjot07 from that link I provided.

> After a member of the Plone Foundation reviews and accepts your signed agreement, your GitHub account will be added to a team in the Plone GitHub organization with appropriate access. This process may take a few business days.

When you receive that email, then you may add another comment to this pull request to notify others that this pull request is ready for review. However you will also need to follow [this tip to update your pull request against the `main` branch](https://6.docs.plone.org/contributing/first-time.html#update-your-pull-request-from-your-fork) before anyone will take a look.

**Comment by ravjot07** [comment]
> @ravjot07 from that link I provided.
> 
> > After a member of the Plone Foundation reviews and accepts your signed agreement, your GitHub account will be added to a team in the Plone GitHub organization with appropriate access. This process may take a few business days.
> 
> When you receive that email, then you may add another comment to this pull request to notify others that this pull request is ready for review. However you will also need to follow [this tip to update your pull request against the `main` branch](https://6.docs.plone.org/contributing/first-time.html#update-your-pull-request-from-your-fork) before anyone will take a look.

@stevepiercy Can u look at my agreement I have signed it more than 15 days ago and I already recieved mail from Paul Roeland from plone team and already a member of zope foundation

**Comment by stevepiercy** [comment]
> @stevepiercy Can u look at my agreement I have signed it more than 15 days ago and I already recieved mail from Paul Roeland from plone team and already a member of zope foundation

Plone and Zope are two different organizations with different contributor agreements. This pull request is in the Plone organization.

I suggest that you contact the same email address to which you sent your agreement, whichever one it was, as well as verify that your username and email address that you use in GitHub match those which you put on your agreement.

**Comment by ravjot07** [comment]
Acceptance Tests / Core Volto Slate (20.x) (pull_request) Failing 
Sir how can i resolve this issue

**Comment by stevepiercy** [comment]
@ravjot07 it's OK not to call me "sir". I was never knighted by the King of England. Maybe someday...

Until then, what do you see when you click the link for[Details](https://github.com/plone/volto/actions/runs/7568865862/job/20610947636?pr=5646) of the failing test?

Sometimes tests in GitHub Workflows fail because of network issues. What happens if you re-run the failing test? I don't know if you have permission to do that.

Do you run tests locally before pushing commits to your pull request?

Did you [update your branch with `main`](https://6.docs.plone.org/contributing/first-time.html#update-your-pull-request-from-your-fork)?

**Comment by ravjot07** [comment]
> @ravjot07 it's OK not to call me "sir". I was never knighted by the King of England. Maybe someday...
> 
> Until then, what do you see when you click the link for[Details](https://github.com/plone/volto/actions/runs/7568865862/job/20610947636?pr=5646) of the failing test?
> 
> Sometimes tests in GitHub Workflows fail because of network issues. What happens if you re-run the failing test? I don't know if you have permission to do that.
> 
> Do you run tests locally before pushing commits to your pull request?
> 
> Did you [update your branch with `main`](https://6.docs.plone.org/contributing/first-time.html#update-your-pull-request-from-your-fork)?

Maybe someday... 
All Test passed......

**Comment by sneridagh** [comment]
@ravjot07 we do use that utility function because of something... Removing them with custom code is not ok.
We do have another utility function, more complete one in the code. Try to use that one: https://github.com/plone/volto/blob/316cadc02acfd09c59cd8d0430b964ce5f934968/packages/volto/src/helpers/Utils/useDetectClickOutside.js

**Comment by stevepiercy** [comment]
@ravjot07 stop! Read and follow item 3 in [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do). Repeat offenses may result in you getting blocked from the organization. Thank you for respecting our community.

**Comment by ravjot07** [comment]
> @ravjot07 stop! Read and follow item 3 in [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do). Repeat offenses may result in you getting blocked from the organization. Thank you for respecting our community.

There was some kind of synchronisation issue from my end my commit were not showing that's why I was trying different approaches. Okiee Steve I will be more carefull next time

**Comment by ravjot07** [comment]
@stevepiercy I have deleted this fork so i have to crate a new PR from my new Fork for this isssue Is that ok? And can you guide me why my test are failing as i have made very little change so i can be careful next time working on the issue

**Comment by stevepiercy** [comment]
As a contributor, you must read how to be a contributor to the project, and learn how to use git and GitHub. This is an open source software community, not a place to be mentored by an individual.

**Pull request closed without merging**
